/** The permissions of the panel, as the master's access package defines them; its tests check that both agree. */
export const permissionIds = [
  "nodes.view",
  "nodes.edit",
  "nodes.certificates",
  "nodes.delete",
  "nodes.enroll",
  "overlay.manage",
  "servers.view",
  "servers.create",
  "servers.start",
  "servers.stop",
  "servers.restart",
  "servers.settings",
  "servers.delete",
  "console.view",
  "console.commands",
  "players.manage",
  "files.read",
  "files.write",
  "properties.edit",
  "plugins.manage",
  "backups.view",
  "backups.create",
  "backups.restore",
  "backups.delete",
  "networks.view",
  "networks.manage",
  "templates.view",
  "templates.manage",
  "filesets.view",
  "filesets.manage",
  "backupjobs.view",
  "backupjobs.manage",
  "policies.view",
  "policies.manage",
  "logs.view",
  "settings.view",
  "settings.edit",
  "terminal.use",
  "users.view",
  "users.manage",
  "groups.manage",
] as const

export type Permission = (typeof permissionIds)[number]
