// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: noryx/v1/backup.proto

package noryxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackupService_ListBackups_FullMethodName     = "/noryx.v1.BackupService/ListBackups"
	BackupService_CreateBackup_FullMethodName    = "/noryx.v1.BackupService/CreateBackup"
	BackupService_RestoreBackup_FullMethodName   = "/noryx.v1.BackupService/RestoreBackup"
	BackupService_DeleteBackup_FullMethodName    = "/noryx.v1.BackupService/DeleteBackup"
	BackupService_UpdateBackup_FullMethodName    = "/noryx.v1.BackupService/UpdateBackup"
	BackupService_ListBackupFiles_FullMethodName = "/noryx.v1.BackupService/ListBackupFiles"
	BackupService_DownloadBackup_FullMethodName  = "/noryx.v1.BackupService/DownloadBackup"
	BackupService_ImportBackup_FullMethodName    = "/noryx.v1.BackupService/ImportBackup"
	BackupService_ImportCopy_FullMethodName      = "/noryx.v1.BackupService/ImportCopy"
	BackupService_DownloadCopy_FullMethodName    = "/noryx.v1.BackupService/DownloadCopy"
	BackupService_DeleteCopy_FullMethodName      = "/noryx.v1.BackupService/DeleteCopy"
)

// BackupServiceClient is the client API for BackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BackupService is served by every agent and keeps backups of its servers on the node, in
// the backups folder of a storage location, where containers can't reach them. A backup is
// a ZIP archive of the selected files and folders of a server.
type BackupServiceClient interface {
	// ListBackups returns the backups of a server, newest first.
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	// CreateBackup archives the selected data of a server. A running game server writes its
	// worlds to disk first and pauses saving meanwhile, so players stay connected.
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error)
	// RestoreBackup replaces the files and folders in a backup, or some of them, with their
	// backed up state. A running server is stopped meanwhile and started again.
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error)
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error)
	// UpdateBackup changes the label of a backup and whether its job keeps it.
	UpdateBackup(ctx context.Context, in *UpdateBackupRequest, opts ...grpc.CallOption) (*UpdateBackupResponse, error)
	// ListBackupFiles lists a folder of a backup's archive, to choose what to restore.
	ListBackupFiles(ctx context.Context, in *ListBackupFilesRequest, opts ...grpc.CallOption) (*ListBackupFilesResponse, error)
	// DownloadBackup sends the archive in chunks. The first message carries its size, if known.
	DownloadBackup(ctx context.Context, in *DownloadBackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadBackupResponse], error)
	// ImportBackup adds a backup of a server that came from another node. The header
	// describes it, the data that follows is its archive.
	ImportBackup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportBackupRequest, ImportBackupResponse], error)
	// ImportCopy keeps a copy of a backup of a server of another node, apart from the backups
	// of the servers of this node, so that the server can be restored if its node is lost. The
	// header names the server, which needn't exist here, and describes the backup. Copies are
	// never restored where they are kept: the master relays them into a server.
	ImportCopy(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportCopyRequest, ImportCopyResponse], error)
	// DownloadCopy sends the archive of a copy in chunks; the first message carries its size.
	DownloadCopy(ctx context.Context, in *DownloadCopyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadCopyResponse], error)
	DeleteCopy(ctx context.Context, in *DeleteCopyRequest, opts ...grpc.CallOption) (*DeleteCopyResponse, error)
}

type backupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupServiceClient(cc grpc.ClientConnInterface) BackupServiceClient {
	return &backupServiceClient{cc}
}

func (c *backupServiceClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, BackupService_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBackupResponse)
	err := c.cc.Invoke(ctx, BackupService_CreateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreBackupResponse)
	err := c.cc.Invoke(ctx, BackupService_RestoreBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBackupResponse)
	err := c.cc.Invoke(ctx, BackupService_DeleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) UpdateBackup(ctx context.Context, in *UpdateBackupRequest, opts ...grpc.CallOption) (*UpdateBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBackupResponse)
	err := c.cc.Invoke(ctx, BackupService_UpdateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ListBackupFiles(ctx context.Context, in *ListBackupFilesRequest, opts ...grpc.CallOption) (*ListBackupFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupFilesResponse)
	err := c.cc.Invoke(ctx, BackupService_ListBackupFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) DownloadBackup(ctx context.Context, in *DownloadBackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadBackupResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackupService_ServiceDesc.Streams[0], BackupService_DownloadBackup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadBackupRequest, DownloadBackupResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_DownloadBackupClient = grpc.ServerStreamingClient[DownloadBackupResponse]

func (c *backupServiceClient) ImportBackup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportBackupRequest, ImportBackupResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackupService_ServiceDesc.Streams[1], BackupService_ImportBackup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportBackupRequest, ImportBackupResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_ImportBackupClient = grpc.ClientStreamingClient[ImportBackupRequest, ImportBackupResponse]

func (c *backupServiceClient) ImportCopy(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportCopyRequest, ImportCopyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackupService_ServiceDesc.Streams[2], BackupService_ImportCopy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportCopyRequest, ImportCopyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_ImportCopyClient = grpc.ClientStreamingClient[ImportCopyRequest, ImportCopyResponse]

func (c *backupServiceClient) DownloadCopy(ctx context.Context, in *DownloadCopyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadCopyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackupService_ServiceDesc.Streams[3], BackupService_DownloadCopy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadCopyRequest, DownloadCopyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_DownloadCopyClient = grpc.ServerStreamingClient[DownloadCopyResponse]

func (c *backupServiceClient) DeleteCopy(ctx context.Context, in *DeleteCopyRequest, opts ...grpc.CallOption) (*DeleteCopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCopyResponse)
	err := c.cc.Invoke(ctx, BackupService_DeleteCopy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServiceServer is the server API for BackupService service.
// All implementations must embed UnimplementedBackupServiceServer
// for forward compatibility.
//
// BackupService is served by every agent and keeps backups of its servers on the node, in
// the backups folder of a storage location, where containers can't reach them. A backup is
// a ZIP archive of the selected files and folders of a server.
type BackupServiceServer interface {
	// ListBackups returns the backups of a server, newest first.
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	// CreateBackup archives the selected data of a server. A running game server writes its
	// worlds to disk first and pauses saving meanwhile, so players stay connected.
	CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error)
	// RestoreBackup replaces the files and folders in a backup, or some of them, with their
	// backed up state. A running server is stopped meanwhile and started again.
	RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error)
	DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error)
	// UpdateBackup changes the label of a backup and whether its job keeps it.
	UpdateBackup(context.Context, *UpdateBackupRequest) (*UpdateBackupResponse, error)
	// ListBackupFiles lists a folder of a backup's archive, to choose what to restore.
	ListBackupFiles(context.Context, *ListBackupFilesRequest) (*ListBackupFilesResponse, error)
	// DownloadBackup sends the archive in chunks. The first message carries its size, if known.
	DownloadBackup(*DownloadBackupRequest, grpc.ServerStreamingServer[DownloadBackupResponse]) error
	// ImportBackup adds a backup of a server that came from another node. The header
	// describes it, the data that follows is its archive.
	ImportBackup(grpc.ClientStreamingServer[ImportBackupRequest, ImportBackupResponse]) error
	// ImportCopy keeps a copy of a backup of a server of another node, apart from the backups
	// of the servers of this node, so that the server can be restored if its node is lost. The
	// header names the server, which needn't exist here, and describes the backup. Copies are
	// never restored where they are kept: the master relays them into a server.
	ImportCopy(grpc.ClientStreamingServer[ImportCopyRequest, ImportCopyResponse]) error
	// DownloadCopy sends the archive of a copy in chunks; the first message carries its size.
	DownloadCopy(*DownloadCopyRequest, grpc.ServerStreamingServer[DownloadCopyResponse]) error
	DeleteCopy(context.Context, *DeleteCopyRequest) (*DeleteCopyResponse, error)
	mustEmbedUnimplementedBackupServiceServer()
}

// UnimplementedBackupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupServiceServer struct{}

func (UnimplementedBackupServiceServer) ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedBackupServiceServer) CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedBackupServiceServer) RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (UnimplementedBackupServiceServer) DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedBackupServiceServer) UpdateBackup(context.Context, *UpdateBackupRequest) (*UpdateBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBackup not implemented")
}
func (UnimplementedBackupServiceServer) ListBackupFiles(context.Context, *ListBackupFilesRequest) (*ListBackupFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackupFiles not implemented")
}
func (UnimplementedBackupServiceServer) DownloadBackup(*DownloadBackupRequest, grpc.ServerStreamingServer[DownloadBackupResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadBackup not implemented")
}
func (UnimplementedBackupServiceServer) ImportBackup(grpc.ClientStreamingServer[ImportBackupRequest, ImportBackupResponse]) error {
	return status.Error(codes.Unimplemented, "method ImportBackup not implemented")
}
func (UnimplementedBackupServiceServer) ImportCopy(grpc.ClientStreamingServer[ImportCopyRequest, ImportCopyResponse]) error {
	return status.Error(codes.Unimplemented, "method ImportCopy not implemented")
}
func (UnimplementedBackupServiceServer) DownloadCopy(*DownloadCopyRequest, grpc.ServerStreamingServer[DownloadCopyResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadCopy not implemented")
}
func (UnimplementedBackupServiceServer) DeleteCopy(context.Context, *DeleteCopyRequest) (*DeleteCopyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCopy not implemented")
}
func (UnimplementedBackupServiceServer) mustEmbedUnimplementedBackupServiceServer() {}
func (UnimplementedBackupServiceServer) testEmbeddedByValue()                       {}

// UnsafeBackupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServiceServer will
// result in compilation errors.
type UnsafeBackupServiceServer interface {
	mustEmbedUnimplementedBackupServiceServer()
}

func RegisterBackupServiceServer(s grpc.ServiceRegistrar, srv BackupServiceServer) {
	// If the following call panics, it indicates UnimplementedBackupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackupService_ServiceDesc, srv)
}

func _BackupService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_CreateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_RestoreBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_DeleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_UpdateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).UpdateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_UpdateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).UpdateBackup(ctx, req.(*UpdateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ListBackupFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ListBackupFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ListBackupFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ListBackupFiles(ctx, req.(*ListBackupFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_DownloadBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadBackupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackupServiceServer).DownloadBackup(m, &grpc.GenericServerStream[DownloadBackupRequest, DownloadBackupResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_DownloadBackupServer = grpc.ServerStreamingServer[DownloadBackupResponse]

func _BackupService_ImportBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackupServiceServer).ImportBackup(&grpc.GenericServerStream[ImportBackupRequest, ImportBackupResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_ImportBackupServer = grpc.ClientStreamingServer[ImportBackupRequest, ImportBackupResponse]

func _BackupService_ImportCopy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackupServiceServer).ImportCopy(&grpc.GenericServerStream[ImportCopyRequest, ImportCopyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_ImportCopyServer = grpc.ClientStreamingServer[ImportCopyRequest, ImportCopyResponse]

func _BackupService_DownloadCopy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadCopyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackupServiceServer).DownloadCopy(m, &grpc.GenericServerStream[DownloadCopyRequest, DownloadCopyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_DownloadCopyServer = grpc.ServerStreamingServer[DownloadCopyResponse]

func _BackupService_DeleteCopy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).DeleteCopy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_DeleteCopy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).DeleteCopy(ctx, req.(*DeleteCopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupService_ServiceDesc is the grpc.ServiceDesc for BackupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noryx.v1.BackupService",
	HandlerType: (*BackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBackups",
			Handler:    _BackupService_ListBackups_Handler,
		},
		{
			MethodName: "CreateBackup",
			Handler:    _BackupService_CreateBackup_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _BackupService_RestoreBackup_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _BackupService_DeleteBackup_Handler,
		},
		{
			MethodName: "UpdateBackup",
			Handler:    _BackupService_UpdateBackup_Handler,
		},
		{
			MethodName: "ListBackupFiles",
			Handler:    _BackupService_ListBackupFiles_Handler,
		},
		{
			MethodName: "DeleteCopy",
			Handler:    _BackupService_DeleteCopy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadBackup",
			Handler:       _BackupService_DownloadBackup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImportBackup",
			Handler:       _BackupService_ImportBackup_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ImportCopy",
			Handler:       _BackupService_ImportCopy_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadCopy",
			Handler:       _BackupService_DownloadCopy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "noryx/v1/backup.proto",
}
