// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: noryx/v1/backup.proto

package noryxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BackupSelection chooses what of a server is backed up.
type BackupSelection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The whole data directory; the other fields are ignored.
	Everything bool `protobuf:"varint,1,opt,name=everything,proto3" json:"everything,omitempty"`
	// Folders with a level.dat, e.g. world and world_nether.
	Worlds bool `protobuf:"varint,2,opt,name=worlds,proto3" json:"worlds,omitempty"`
	// The plugins or mods folder; for mods also config/, where they keep their settings.
	Plugins bool `protobuf:"varint,3,opt,name=plugins,proto3" json:"plugins,omitempty"`
	// Files in the data directory except .jar files and logs, and the config folder.
	Config bool `protobuf:"varint,4,opt,name=config,proto3" json:"config,omitempty"`
	// Further files or folders, relative to the data directory. Missing ones are skipped.
	Paths []string `protobuf:"bytes,5,rep,name=paths,proto3" json:"paths,omitempty"`
	// Files or folders inside the others that are left out, e.g. the tiles of a map plugin.
	// Restoring the backup leaves them as they are. Agents of older versions archive them.
	Exclude       []string `protobuf:"bytes,6,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSelection) Reset() {
	*x = BackupSelection{}
	mi := &file_noryx_v1_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSelection) ProtoMessage() {}

func (x *BackupSelection) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSelection.ProtoReflect.Descriptor instead.
func (*BackupSelection) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupSelection) GetEverything() bool {
	if x != nil {
		return x.Everything
	}
	return false
}

func (x *BackupSelection) GetWorlds() bool {
	if x != nil {
		return x.Worlds
	}
	return false
}

func (x *BackupSelection) GetPlugins() bool {
	if x != nil {
		return x.Plugins
	}
	return false
}

func (x *BackupSelection) GetConfig() bool {
	if x != nil {
		return x.Config
	}
	return false
}

func (x *BackupSelection) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *BackupSelection) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

// BackupRetention tells which backups of a job are kept: the newest ones, and the newest of
// each of the last days, weeks (from Monday) and months that have backups. A backup that
// any of them keeps stays; all zero keeps all.
type BackupRetention struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Last   uint32                 `protobuf:"varint,1,opt,name=last,proto3" json:"last,omitempty"`
	Days   uint32                 `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	Weeks  uint32                 `protobuf:"varint,3,opt,name=weeks,proto3" json:"weeks,omitempty"`
	Months uint32                 `protobuf:"varint,4,opt,name=months,proto3" json:"months,omitempty"`
	// IANA time zone in which days, weeks and months begin, e.g. the job's; empty for UTC.
	TimeZone      string `protobuf:"bytes,5,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRetention) Reset() {
	*x = BackupRetention{}
	mi := &file_noryx_v1_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRetention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRetention) ProtoMessage() {}

func (x *BackupRetention) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRetention.ProtoReflect.Descriptor instead.
func (*BackupRetention) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupRetention) GetLast() uint32 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *BackupRetention) GetDays() uint32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *BackupRetention) GetWeeks() uint32 {
	if x != nil {
		return x.Weeks
	}
	return 0
}

func (x *BackupRetention) GetMonths() uint32 {
	if x != nil {
		return x.Months
	}
	return 0
}

func (x *BackupRetention) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

type Backup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// What the administrator entered, or the name of the job that made the backup.
	Label       string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	CreatedUnix int64  `protobuf:"varint,3,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	Size        int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// Storage location that holds the backup.
	Location string `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// Files and folders in the backup, relative to the data directory; "." is everything.
	Paths []string `protobuf:"bytes,6,rep,name=paths,proto3" json:"paths,omitempty"`
	// Job that made the backup; empty if it was made by hand.
	JobId string `protobuf:"bytes,7,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Files and folders inside the paths that the backup left out.
	Exclude []string `protobuf:"bytes,8,rep,name=exclude,proto3" json:"exclude,omitempty"`
	// Kept backups are never deleted by their job.
	Kept          bool `protobuf:"varint,9,opt,name=kept,proto3" json:"kept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_noryx_v1_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{2}
}

func (x *Backup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Backup) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Backup) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *Backup) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Backup) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Backup) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Backup) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Backup) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *Backup) GetKept() bool {
	if x != nil {
		return x.Kept
	}
	return false
}

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_noryx_v1_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{3}
}

func (x *ListBackupsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ListBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backups       []*Backup              `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsResponse) Reset() {
	*x = ListBackupsResponse{}
	mi := &file_noryx_v1_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResponse) ProtoMessage() {}

func (x *ListBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{4}
}

func (x *ListBackupsResponse) GetBackups() []*Backup {
	if x != nil {
		return x.Backups
	}
	return nil
}

type CreateBackupRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServerId  string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Label     string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Selection *BackupSelection       `protobuf:"bytes,3,opt,name=selection,proto3" json:"selection,omitempty"`
	// Storage location for the backup; empty means the default location.
	Location string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	JobId    string `protobuf:"bytes,5,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Backups of the job to keep for the server, 0 for all. Older ones are deleted once the
	// new backup exists. Backups made by hand, and kept ones, are never deleted this way.
	// Ignored if retention is set, which agents of older versions ignore.
	Keep uint32 `protobuf:"varint,6,opt,name=keep,proto3" json:"keep,omitempty"`
	// Whether a server without any of the selected data, e.g. one that never started, is
	// skipped: the response has no backup then. Otherwise that is an error.
	SkipWithoutData bool `protobuf:"varint,7,opt,name=skip_without_data,json=skipWithoutData,proto3" json:"skip_without_data,omitempty"`
	// Which backups of the job are kept, instead of keep.
	Retention     *BackupRetention `protobuf:"bytes,8,opt,name=retention,proto3" json:"retention,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_noryx_v1_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBackupRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateBackupRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateBackupRequest) GetSelection() *BackupSelection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *CreateBackupRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateBackupRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateBackupRequest) GetKeep() uint32 {
	if x != nil {
		return x.Keep
	}
	return 0
}

func (x *CreateBackupRequest) GetSkipWithoutData() bool {
	if x != nil {
		return x.SkipWithoutData
	}
	return false
}

func (x *CreateBackupRequest) GetRetention() *BackupRetention {
	if x != nil {
		return x.Retention
	}
	return nil
}

type CreateBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backup        *Backup                `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_noryx_v1_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBackupResponse) GetBackup() *Backup {
	if x != nil {
		return x.Backup
	}
	return nil
}

type RestoreBackupRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	BackupId string                 `protobuf:"bytes,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	// Files and folders of the backup to restore, relative to the data directory; empty for
	// all it holds. Each must be in the backup. Agents of older versions restore all.
	Paths []string `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	// Backs up what the restore replaces first, as a backup made by hand in the storage
	// location of the restored one.
	SnapshotFirst bool `protobuf:"varint,4,opt,name=snapshot_first,json=snapshotFirst,proto3" json:"snapshot_first,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupRequest) Reset() {
	*x = RestoreBackupRequest{}
	mi := &file_noryx_v1_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupRequest) ProtoMessage() {}

func (x *RestoreBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreBackupRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RestoreBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *RestoreBackupRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *RestoreBackupRequest) GetSnapshotFirst() bool {
	if x != nil {
		return x.SnapshotFirst
	}
	return false
}

type RestoreBackupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The backup that snapshot_first made; none if the server had none of the paths.
	Snapshot      *Backup `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupResponse) Reset() {
	*x = RestoreBackupResponse{}
	mi := &file_noryx_v1_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupResponse) ProtoMessage() {}

func (x *RestoreBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupResponse.ProtoReflect.Descriptor instead.
func (*RestoreBackupResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{8}
}

func (x *RestoreBackupResponse) GetSnapshot() *Backup {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type DeleteBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	BackupId      string                 `protobuf:"bytes,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_noryx_v1_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBackupRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

type DeleteBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	mi := &file_noryx_v1_backup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{10}
}

type UpdateBackupRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	BackupId string                 `protobuf:"bytes,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	// Only what is set changes.
	Label         *string `protobuf:"bytes,3,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Kept          *bool   `protobuf:"varint,4,opt,name=kept,proto3,oneof" json:"kept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBackupRequest) Reset() {
	*x = UpdateBackupRequest{}
	mi := &file_noryx_v1_backup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBackupRequest) ProtoMessage() {}

func (x *UpdateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBackupRequest.ProtoReflect.Descriptor instead.
func (*UpdateBackupRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateBackupRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *UpdateBackupRequest) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *UpdateBackupRequest) GetKept() bool {
	if x != nil && x.Kept != nil {
		return *x.Kept
	}
	return false
}

type UpdateBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backup        *Backup                `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBackupResponse) Reset() {
	*x = UpdateBackupResponse{}
	mi := &file_noryx_v1_backup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBackupResponse) ProtoMessage() {}

func (x *UpdateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBackupResponse.ProtoReflect.Descriptor instead.
func (*UpdateBackupResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateBackupResponse) GetBackup() *Backup {
	if x != nil {
		return x.Backup
	}
	return nil
}

type ListBackupFilesRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	BackupId string                 `protobuf:"bytes,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	// Folder in the backup, relative to the data directory; empty for its top.
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupFilesRequest) Reset() {
	*x = ListBackupFilesRequest{}
	mi := &file_noryx_v1_backup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupFilesRequest) ProtoMessage() {}

func (x *ListBackupFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupFilesRequest.ProtoReflect.Descriptor instead.
func (*ListBackupFilesRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{13}
}

func (x *ListBackupFilesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListBackupFilesRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *ListBackupFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListBackupFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Folders first, then files, each sorted by name; a folder's size is that of all in it.
	// Files that only hold secrets aren't listed.
	Files []*FileInfo `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	// Set if the folder has more entries than the agent lists.
	Truncated     bool `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupFilesResponse) Reset() {
	*x = ListBackupFilesResponse{}
	mi := &file_noryx_v1_backup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupFilesResponse) ProtoMessage() {}

func (x *ListBackupFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupFilesResponse.ProtoReflect.Descriptor instead.
func (*ListBackupFilesResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{14}
}

func (x *ListBackupFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListBackupFilesResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type DownloadBackupRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	BackupId string                 `protobuf:"bytes,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	// Hides the secrets like ArchiveDirectoryRequest.hide_secrets; the size of the archive
	// isn't known in advance then.
	HideSecrets   bool `protobuf:"varint,3,opt,name=hide_secrets,json=hideSecrets,proto3" json:"hide_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBackupRequest) Reset() {
	*x = DownloadBackupRequest{}
	mi := &file_noryx_v1_backup_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBackupRequest) ProtoMessage() {}

func (x *DownloadBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBackupRequest.ProtoReflect.Descriptor instead.
func (*DownloadBackupRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{15}
}

func (x *DownloadBackupRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DownloadBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *DownloadBackupRequest) GetHideSecrets() bool {
	if x != nil {
		return x.HideSecrets
	}
	return false
}

type DownloadBackupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Size of the archive, 0 if unknown.
	Size          int64  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBackupResponse) Reset() {
	*x = DownloadBackupResponse{}
	mi := &file_noryx_v1_backup_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBackupResponse) ProtoMessage() {}

func (x *DownloadBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBackupResponse.ProtoReflect.Descriptor instead.
func (*DownloadBackupResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{16}
}

func (x *DownloadBackupResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DownloadBackupResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImportBackupHeader struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// The backup keeps its ID; location chooses where it is kept on this node.
	Backup        *Backup `protobuf:"bytes,2,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportBackupHeader) Reset() {
	*x = ImportBackupHeader{}
	mi := &file_noryx_v1_backup_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportBackupHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBackupHeader) ProtoMessage() {}

func (x *ImportBackupHeader) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBackupHeader.ProtoReflect.Descriptor instead.
func (*ImportBackupHeader) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{17}
}

func (x *ImportBackupHeader) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ImportBackupHeader) GetBackup() *Backup {
	if x != nil {
		return x.Backup
	}
	return nil
}

type ImportBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ImportBackupRequest_Header
	//	*ImportBackupRequest_Data
	Content       isImportBackupRequest_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportBackupRequest) Reset() {
	*x = ImportBackupRequest{}
	mi := &file_noryx_v1_backup_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBackupRequest) ProtoMessage() {}

func (x *ImportBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBackupRequest.ProtoReflect.Descriptor instead.
func (*ImportBackupRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{18}
}

func (x *ImportBackupRequest) GetContent() isImportBackupRequest_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ImportBackupRequest) GetHeader() *ImportBackupHeader {
	if x != nil {
		if x, ok := x.Content.(*ImportBackupRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ImportBackupRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Content.(*ImportBackupRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isImportBackupRequest_Content interface {
	isImportBackupRequest_Content()
}

type ImportBackupRequest_Header struct {
	Header *ImportBackupHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type ImportBackupRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ImportBackupRequest_Header) isImportBackupRequest_Content() {}

func (*ImportBackupRequest_Data) isImportBackupRequest_Content() {}

type ImportBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backup        *Backup                `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportBackupResponse) Reset() {
	*x = ImportBackupResponse{}
	mi := &file_noryx_v1_backup_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBackupResponse) ProtoMessage() {}

func (x *ImportBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_backup_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBackupResponse.ProtoReflect.Descriptor instead.
func (*ImportBackupResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_backup_proto_rawDescGZIP(), []int{19}
}

func (x *ImportBackupResponse) GetBackup() *Backup {
	if x != nil {
		return x.Backup
	}
	return nil
}

var File_noryx_v1_backup_proto protoreflect.FileDescriptor

const file_noryx_v1_backup_proto_rawDesc = "" +
	"\n" +
	"\x15noryx/v1/backup.proto\x12\bnoryx.v1\x1a\x13noryx/v1/file.proto\"\xab\x01\n" +
	"\x0fBackupSelection\x12\x1e\n" +
	"\n" +
	"everything\x18\x01 \x01(\bR\n" +
	"everything\x12\x16\n" +
	"\x06worlds\x18\x02 \x01(\bR\x06worlds\x12\x18\n" +
	"\aplugins\x18\x03 \x01(\bR\aplugins\x12\x16\n" +
	"\x06config\x18\x04 \x01(\bR\x06config\x12\x14\n" +
	"\x05paths\x18\x05 \x03(\tR\x05paths\x12\x18\n" +
	"\aexclude\x18\x06 \x03(\tR\aexclude\"\x84\x01\n" +
	"\x0fBackupRetention\x12\x12\n" +
	"\x04last\x18\x01 \x01(\rR\x04last\x12\x12\n" +
	"\x04days\x18\x02 \x01(\rR\x04days\x12\x14\n" +
	"\x05weeks\x18\x03 \x01(\rR\x05weeks\x12\x16\n" +
	"\x06months\x18\x04 \x01(\rR\x06months\x12\x1b\n" +
	"\ttime_zone\x18\x05 \x01(\tR\btimeZone\"\xdc\x01\n" +
	"\x06Backup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12!\n" +
	"\fcreated_unix\x18\x03 \x01(\x03R\vcreatedUnix\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x14\n" +
	"\x05paths\x18\x06 \x03(\tR\x05paths\x12\x15\n" +
	"\x06job_id\x18\a \x01(\tR\x05jobId\x12\x18\n" +
	"\aexclude\x18\b \x03(\tR\aexclude\x12\x12\n" +
	"\x04kept\x18\t \x01(\bR\x04kept\"1\n" +
	"\x12ListBackupsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"A\n" +
	"\x13ListBackupsResponse\x12*\n" +
	"\abackups\x18\x01 \x03(\v2\x10.noryx.v1.BackupR\abackups\"\xad\x02\n" +
	"\x13CreateBackupRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x127\n" +
	"\tselection\x18\x03 \x01(\v2\x19.noryx.v1.BackupSelectionR\tselection\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x15\n" +
	"\x06job_id\x18\x05 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04keep\x18\x06 \x01(\rR\x04keep\x12*\n" +
	"\x11skip_without_data\x18\a \x01(\bR\x0fskipWithoutData\x127\n" +
	"\tretention\x18\b \x01(\v2\x19.noryx.v1.BackupRetentionR\tretention\"@\n" +
	"\x14CreateBackupResponse\x12(\n" +
	"\x06backup\x18\x01 \x01(\v2\x10.noryx.v1.BackupR\x06backup\"\x8d\x01\n" +
	"\x14RestoreBackupRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tbackup_id\x18\x02 \x01(\tR\bbackupId\x12\x14\n" +
	"\x05paths\x18\x03 \x03(\tR\x05paths\x12%\n" +
	"\x0esnapshot_first\x18\x04 \x01(\bR\rsnapshotFirst\"E\n" +
	"\x15RestoreBackupResponse\x12,\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x10.noryx.v1.BackupR\bsnapshot\"O\n" +
	"\x13DeleteBackupRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tbackup_id\x18\x02 \x01(\tR\bbackupId\"\x16\n" +
	"\x14DeleteBackupResponse\"\x96\x01\n" +
	"\x13UpdateBackupRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tbackup_id\x18\x02 \x01(\tR\bbackupId\x12\x19\n" +
	"\x05label\x18\x03 \x01(\tH\x00R\x05label\x88\x01\x01\x12\x17\n" +
	"\x04kept\x18\x04 \x01(\bH\x01R\x04kept\x88\x01\x01B\b\n" +
	"\x06_labelB\a\n" +
	"\x05_kept\"@\n" +
	"\x14UpdateBackupResponse\x12(\n" +
	"\x06backup\x18\x01 \x01(\v2\x10.noryx.v1.BackupR\x06backup\"f\n" +
	"\x16ListBackupFilesRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tbackup_id\x18\x02 \x01(\tR\bbackupId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"a\n" +
	"\x17ListBackupFilesResponse\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.noryx.v1.FileInfoR\x05files\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"t\n" +
	"\x15DownloadBackupRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tbackup_id\x18\x02 \x01(\tR\bbackupId\x12!\n" +
	"\fhide_secrets\x18\x03 \x01(\bR\vhideSecrets\"@\n" +
	"\x16DownloadBackupResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"[\n" +
	"\x12ImportBackupHeader\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12(\n" +
	"\x06backup\x18\x02 \x01(\v2\x10.noryx.v1.BackupR\x06backup\"n\n" +
	"\x13ImportBackupRequest\x126\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.noryx.v1.ImportBackupHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\acontent\"@\n" +
	"\x14ImportBackupResponse\x12(\n" +
	"\x06backup\x18\x01 \x01(\v2\x10.noryx.v1.BackupR\x06backup2\x9a\x05\n" +
	"\rBackupService\x12J\n" +
	"\vListBackups\x12\x1c.noryx.v1.ListBackupsRequest\x1a\x1d.noryx.v1.ListBackupsResponse\x12M\n" +
	"\fCreateBackup\x12\x1d.noryx.v1.CreateBackupRequest\x1a\x1e.noryx.v1.CreateBackupResponse\x12P\n" +
	"\rRestoreBackup\x12\x1e.noryx.v1.RestoreBackupRequest\x1a\x1f.noryx.v1.RestoreBackupResponse\x12M\n" +
	"\fDeleteBackup\x12\x1d.noryx.v1.DeleteBackupRequest\x1a\x1e.noryx.v1.DeleteBackupResponse\x12M\n" +
	"\fUpdateBackup\x12\x1d.noryx.v1.UpdateBackupRequest\x1a\x1e.noryx.v1.UpdateBackupResponse\x12V\n" +
	"\x0fListBackupFiles\x12 .noryx.v1.ListBackupFilesRequest\x1a!.noryx.v1.ListBackupFilesResponse\x12U\n" +
	"\x0eDownloadBackup\x12\x1f.noryx.v1.DownloadBackupRequest\x1a .noryx.v1.DownloadBackupResponse0\x01\x12O\n" +
	"\fImportBackup\x12\x1d.noryx.v1.ImportBackupRequest\x1a\x1e.noryx.v1.ImportBackupResponse(\x01B0Z.github.com/QwikByte/noryx/api/noryx/v1;noryxv1b\x06proto3"

var (
	file_noryx_v1_backup_proto_rawDescOnce sync.Once
	file_noryx_v1_backup_proto_rawDescData []byte
)

func file_noryx_v1_backup_proto_rawDescGZIP() []byte {
	file_noryx_v1_backup_proto_rawDescOnce.Do(func() {
		file_noryx_v1_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noryx_v1_backup_proto_rawDesc), len(file_noryx_v1_backup_proto_rawDesc)))
	})
	return file_noryx_v1_backup_proto_rawDescData
}

var file_noryx_v1_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_noryx_v1_backup_proto_goTypes = []any{
	(*BackupSelection)(nil),         // 0: noryx.v1.BackupSelection
	(*BackupRetention)(nil),         // 1: noryx.v1.BackupRetention
	(*Backup)(nil),                  // 2: noryx.v1.Backup
	(*ListBackupsRequest)(nil),      // 3: noryx.v1.ListBackupsRequest
	(*ListBackupsResponse)(nil),     // 4: noryx.v1.ListBackupsResponse
	(*CreateBackupRequest)(nil),     // 5: noryx.v1.CreateBackupRequest
	(*CreateBackupResponse)(nil),    // 6: noryx.v1.CreateBackupResponse
	(*RestoreBackupRequest)(nil),    // 7: noryx.v1.RestoreBackupRequest
	(*RestoreBackupResponse)(nil),   // 8: noryx.v1.RestoreBackupResponse
	(*DeleteBackupRequest)(nil),     // 9: noryx.v1.DeleteBackupRequest
	(*DeleteBackupResponse)(nil),    // 10: noryx.v1.DeleteBackupResponse
	(*UpdateBackupRequest)(nil),     // 11: noryx.v1.UpdateBackupRequest
	(*UpdateBackupResponse)(nil),    // 12: noryx.v1.UpdateBackupResponse
	(*ListBackupFilesRequest)(nil),  // 13: noryx.v1.ListBackupFilesRequest
	(*ListBackupFilesResponse)(nil), // 14: noryx.v1.ListBackupFilesResponse
	(*DownloadBackupRequest)(nil),   // 15: noryx.v1.DownloadBackupRequest
	(*DownloadBackupResponse)(nil),  // 16: noryx.v1.DownloadBackupResponse
	(*ImportBackupHeader)(nil),      // 17: noryx.v1.ImportBackupHeader
	(*ImportBackupRequest)(nil),     // 18: noryx.v1.ImportBackupRequest
	(*ImportBackupResponse)(nil),    // 19: noryx.v1.ImportBackupResponse
	(*FileInfo)(nil),                // 20: noryx.v1.FileInfo
}
var file_noryx_v1_backup_proto_depIdxs = []int32{
	2,  // 0: noryx.v1.ListBackupsResponse.backups:type_name -> noryx.v1.Backup
	0,  // 1: noryx.v1.CreateBackupRequest.selection:type_name -> noryx.v1.BackupSelection
	1,  // 2: noryx.v1.CreateBackupRequest.retention:type_name -> noryx.v1.BackupRetention
	2,  // 3: noryx.v1.CreateBackupResponse.backup:type_name -> noryx.v1.Backup
	2,  // 4: noryx.v1.RestoreBackupResponse.snapshot:type_name -> noryx.v1.Backup
	2,  // 5: noryx.v1.UpdateBackupResponse.backup:type_name -> noryx.v1.Backup
	20, // 6: noryx.v1.ListBackupFilesResponse.files:type_name -> noryx.v1.FileInfo
	2,  // 7: noryx.v1.ImportBackupHeader.backup:type_name -> noryx.v1.Backup
	17, // 8: noryx.v1.ImportBackupRequest.header:type_name -> noryx.v1.ImportBackupHeader
	2,  // 9: noryx.v1.ImportBackupResponse.backup:type_name -> noryx.v1.Backup
	3,  // 10: noryx.v1.BackupService.ListBackups:input_type -> noryx.v1.ListBackupsRequest
	5,  // 11: noryx.v1.BackupService.CreateBackup:input_type -> noryx.v1.CreateBackupRequest
	7,  // 12: noryx.v1.BackupService.RestoreBackup:input_type -> noryx.v1.RestoreBackupRequest
	9,  // 13: noryx.v1.BackupService.DeleteBackup:input_type -> noryx.v1.DeleteBackupRequest
	11, // 14: noryx.v1.BackupService.UpdateBackup:input_type -> noryx.v1.UpdateBackupRequest
	13, // 15: noryx.v1.BackupService.ListBackupFiles:input_type -> noryx.v1.ListBackupFilesRequest
	15, // 16: noryx.v1.BackupService.DownloadBackup:input_type -> noryx.v1.DownloadBackupRequest
	18, // 17: noryx.v1.BackupService.ImportBackup:input_type -> noryx.v1.ImportBackupRequest
	4,  // 18: noryx.v1.BackupService.ListBackups:output_type -> noryx.v1.ListBackupsResponse
	6,  // 19: noryx.v1.BackupService.CreateBackup:output_type -> noryx.v1.CreateBackupResponse
	8,  // 20: noryx.v1.BackupService.RestoreBackup:output_type -> noryx.v1.RestoreBackupResponse
	10, // 21: noryx.v1.BackupService.DeleteBackup:output_type -> noryx.v1.DeleteBackupResponse
	12, // 22: noryx.v1.BackupService.UpdateBackup:output_type -> noryx.v1.UpdateBackupResponse
	14, // 23: noryx.v1.BackupService.ListBackupFiles:output_type -> noryx.v1.ListBackupFilesResponse
	16, // 24: noryx.v1.BackupService.DownloadBackup:output_type -> noryx.v1.DownloadBackupResponse
	19, // 25: noryx.v1.BackupService.ImportBackup:output_type -> noryx.v1.ImportBackupResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_noryx_v1_backup_proto_init() }
func file_noryx_v1_backup_proto_init() {
	if File_noryx_v1_backup_proto != nil {
		return
	}
	file_noryx_v1_file_proto_init()
	file_noryx_v1_backup_proto_msgTypes[11].OneofWrappers = []any{}
	file_noryx_v1_backup_proto_msgTypes[18].OneofWrappers = []any{
		(*ImportBackupRequest_Header)(nil),
		(*ImportBackupRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noryx_v1_backup_proto_rawDesc), len(file_noryx_v1_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noryx_v1_backup_proto_goTypes,
		DependencyIndexes: file_noryx_v1_backup_proto_depIdxs,
		MessageInfos:      file_noryx_v1_backup_proto_msgTypes,
	}.Build()
	File_noryx_v1_backup_proto = out.File
	file_noryx_v1_backup_proto_goTypes = nil
	file_noryx_v1_backup_proto_depIdxs = nil
}
