// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: noryx/v1/datastore.proto

package noryxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatastoreService_ListDatastores_FullMethodName      = "/noryx.v1.DatastoreService/ListDatastores"
	DatastoreService_CreateDatastore_FullMethodName     = "/noryx.v1.DatastoreService/CreateDatastore"
	DatastoreService_StartDatastore_FullMethodName      = "/noryx.v1.DatastoreService/StartDatastore"
	DatastoreService_StopDatastore_FullMethodName       = "/noryx.v1.DatastoreService/StopDatastore"
	DatastoreService_UpdateDatastore_FullMethodName     = "/noryx.v1.DatastoreService/UpdateDatastore"
	DatastoreService_PublishDatastore_FullMethodName    = "/noryx.v1.DatastoreService/PublishDatastore"
	DatastoreService_DeleteDatastore_FullMethodName     = "/noryx.v1.DatastoreService/DeleteDatastore"
	DatastoreService_EnsureDatabase_FullMethodName      = "/noryx.v1.DatastoreService/EnsureDatabase"
	DatastoreService_DropDatabase_FullMethodName        = "/noryx.v1.DatastoreService/DropDatabase"
	DatastoreService_CreateDump_FullMethodName          = "/noryx.v1.DatastoreService/CreateDump"
	DatastoreService_ListDumps_FullMethodName           = "/noryx.v1.DatastoreService/ListDumps"
	DatastoreService_RestoreDump_FullMethodName         = "/noryx.v1.DatastoreService/RestoreDump"
	DatastoreService_DeleteDump_FullMethodName          = "/noryx.v1.DatastoreService/DeleteDump"
	DatastoreService_DownloadDump_FullMethodName        = "/noryx.v1.DatastoreService/DownloadDump"
	DatastoreService_ImportDump_FullMethodName          = "/noryx.v1.DatastoreService/ImportDump"
	DatastoreService_ListTables_FullMethodName          = "/noryx.v1.DatastoreService/ListTables"
	DatastoreService_BrowseTable_FullMethodName         = "/noryx.v1.DatastoreService/BrowseTable"
	DatastoreService_StreamDatastoreLogs_FullMethodName = "/noryx.v1.DatastoreService/StreamDatastoreLogs"
)

// DatastoreServiceClient is the client API for DatastoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DatastoreService is served by every agent and runs the MariaDB and PostgreSQL servers of
// networks: their containers, their databases, each with a user of the same name, and dumps of
// them. Only the servers of a datastore's network reach it: on its node over a Docker network
// without internet, from other nodes over the private network of the nodes. The superuser's
// password never leaves the node.
type DatastoreServiceClient interface {
	// ListDatastores returns the datastores of the node and the versions the agent runs.
	ListDatastores(ctx context.Context, in *ListDatastoresRequest, opts ...grpc.CallOption) (*ListDatastoresResponse, error)
	CreateDatastore(ctx context.Context, in *CreateDatastoreRequest, opts ...grpc.CallOption) (*CreateDatastoreResponse, error)
	StartDatastore(ctx context.Context, in *StartDatastoreRequest, opts ...grpc.CallOption) (*StartDatastoreResponse, error)
	StopDatastore(ctx context.Context, in *StopDatastoreRequest, opts ...grpc.CallOption) (*StopDatastoreResponse, error)
	// UpdateDatastore changes the limits of a datastore, pulls its image again, moves it to
	// another major version or removes the data a previous version left.
	UpdateDatastore(ctx context.Context, in *UpdateDatastoreRequest, opts ...grpc.CallOption) (*UpdateDatastoreResponse, error)
	// PublishDatastore publishes the port of a datastore at the node's address in the private
	// network of the nodes, for the nodes of its network only, or no longer.
	PublishDatastore(ctx context.Context, in *PublishDatastoreRequest, opts ...grpc.CallOption) (*PublishDatastoreResponse, error)
	// DeleteDatastore removes a datastore with its container, network, data and dumps.
	DeleteDatastore(ctx context.Context, in *DeleteDatastoreRequest, opts ...grpc.CallOption) (*DeleteDatastoreResponse, error)
	// EnsureDatabase creates a database and its user, or sets the user's password, with rights
	// on that database only.
	EnsureDatabase(ctx context.Context, in *EnsureDatabaseRequest, opts ...grpc.CallOption) (*EnsureDatabaseResponse, error)
	DropDatabase(ctx context.Context, in *DropDatabaseRequest, opts ...grpc.CallOption) (*DropDatabaseResponse, error)
	// CreateDump dumps databases of a running datastore into a ZIP archive with one
	// <database>.sql each, kept like the backups of servers.
	CreateDump(ctx context.Context, in *CreateDumpRequest, opts ...grpc.CallOption) (*CreateDumpResponse, error)
	ListDumps(ctx context.Context, in *ListDumpsRequest, opts ...grpc.CallOption) (*ListDumpsResponse, error)
	// RestoreDump drops and creates databases again and loads their dumps as their own users.
	RestoreDump(ctx context.Context, in *RestoreDumpRequest, opts ...grpc.CallOption) (*RestoreDumpResponse, error)
	DeleteDump(ctx context.Context, in *DeleteDumpRequest, opts ...grpc.CallOption) (*DeleteDumpResponse, error)
	// DownloadDump sends a dump in chunks; the first message carries its size.
	DownloadDump(ctx context.Context, in *DownloadDumpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadDumpResponse], error)
	// ImportDump adds a dump made elsewhere, e.g. of a database that moves to Noryx. The first
	// message describes it, the data that follows is a ZIP archive with a <database>.sql for
	// each database, or the SQL of a single database. The agent checks it and keeps it like
	// the dumps it makes, so that RestoreDump loads it as the databases' users.
	ImportDump(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportDumpRequest, ImportDumpResponse], error)
	// ListTables returns the tables of a database of a running datastore.
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	// BrowseTable returns rows of a table as text, with long values cut short. It only reads,
	// with statements the agent builds itself.
	BrowseTable(ctx context.Context, in *BrowseTableRequest, opts ...grpc.CallOption) (*BrowseTableResponse, error)
	// StreamDatastoreLogs sends the last lines of the log of a datastore's container, then
	// follows it until the container stops or the client disconnects, like StreamLogs of
	// servers. The agent hides passwords in the statements that the engines log, e.g. when
	// they fail.
	StreamDatastoreLogs(ctx context.Context, in *StreamDatastoreLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamDatastoreLogsResponse], error)
}

type datastoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatastoreServiceClient(cc grpc.ClientConnInterface) DatastoreServiceClient {
	return &datastoreServiceClient{cc}
}

func (c *datastoreServiceClient) ListDatastores(ctx context.Context, in *ListDatastoresRequest, opts ...grpc.CallOption) (*ListDatastoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatastoresResponse)
	err := c.cc.Invoke(ctx, DatastoreService_ListDatastores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) CreateDatastore(ctx context.Context, in *CreateDatastoreRequest, opts ...grpc.CallOption) (*CreateDatastoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatastoreResponse)
	err := c.cc.Invoke(ctx, DatastoreService_CreateDatastore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) StartDatastore(ctx context.Context, in *StartDatastoreRequest, opts ...grpc.CallOption) (*StartDatastoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDatastoreResponse)
	err := c.cc.Invoke(ctx, DatastoreService_StartDatastore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) StopDatastore(ctx context.Context, in *StopDatastoreRequest, opts ...grpc.CallOption) (*StopDatastoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopDatastoreResponse)
	err := c.cc.Invoke(ctx, DatastoreService_StopDatastore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) UpdateDatastore(ctx context.Context, in *UpdateDatastoreRequest, opts ...grpc.CallOption) (*UpdateDatastoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDatastoreResponse)
	err := c.cc.Invoke(ctx, DatastoreService_UpdateDatastore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) PublishDatastore(ctx context.Context, in *PublishDatastoreRequest, opts ...grpc.CallOption) (*PublishDatastoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishDatastoreResponse)
	err := c.cc.Invoke(ctx, DatastoreService_PublishDatastore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) DeleteDatastore(ctx context.Context, in *DeleteDatastoreRequest, opts ...grpc.CallOption) (*DeleteDatastoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDatastoreResponse)
	err := c.cc.Invoke(ctx, DatastoreService_DeleteDatastore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) EnsureDatabase(ctx context.Context, in *EnsureDatabaseRequest, opts ...grpc.CallOption) (*EnsureDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureDatabaseResponse)
	err := c.cc.Invoke(ctx, DatastoreService_EnsureDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) DropDatabase(ctx context.Context, in *DropDatabaseRequest, opts ...grpc.CallOption) (*DropDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropDatabaseResponse)
	err := c.cc.Invoke(ctx, DatastoreService_DropDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) CreateDump(ctx context.Context, in *CreateDumpRequest, opts ...grpc.CallOption) (*CreateDumpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDumpResponse)
	err := c.cc.Invoke(ctx, DatastoreService_CreateDump_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) ListDumps(ctx context.Context, in *ListDumpsRequest, opts ...grpc.CallOption) (*ListDumpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDumpsResponse)
	err := c.cc.Invoke(ctx, DatastoreService_ListDumps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) RestoreDump(ctx context.Context, in *RestoreDumpRequest, opts ...grpc.CallOption) (*RestoreDumpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreDumpResponse)
	err := c.cc.Invoke(ctx, DatastoreService_RestoreDump_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) DeleteDump(ctx context.Context, in *DeleteDumpRequest, opts ...grpc.CallOption) (*DeleteDumpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDumpResponse)
	err := c.cc.Invoke(ctx, DatastoreService_DeleteDump_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) DownloadDump(ctx context.Context, in *DownloadDumpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadDumpResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatastoreService_ServiceDesc.Streams[0], DatastoreService_DownloadDump_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadDumpRequest, DownloadDumpResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatastoreService_DownloadDumpClient = grpc.ServerStreamingClient[DownloadDumpResponse]

func (c *datastoreServiceClient) ImportDump(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportDumpRequest, ImportDumpResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatastoreService_ServiceDesc.Streams[1], DatastoreService_ImportDump_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportDumpRequest, ImportDumpResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatastoreService_ImportDumpClient = grpc.ClientStreamingClient[ImportDumpRequest, ImportDumpResponse]

func (c *datastoreServiceClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTablesResponse)
	err := c.cc.Invoke(ctx, DatastoreService_ListTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) BrowseTable(ctx context.Context, in *BrowseTableRequest, opts ...grpc.CallOption) (*BrowseTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowseTableResponse)
	err := c.cc.Invoke(ctx, DatastoreService_BrowseTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) StreamDatastoreLogs(ctx context.Context, in *StreamDatastoreLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamDatastoreLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatastoreService_ServiceDesc.Streams[2], DatastoreService_StreamDatastoreLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamDatastoreLogsRequest, StreamDatastoreLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatastoreService_StreamDatastoreLogsClient = grpc.ServerStreamingClient[StreamDatastoreLogsResponse]

// DatastoreServiceServer is the server API for DatastoreService service.
// All implementations must embed UnimplementedDatastoreServiceServer
// for forward compatibility.
//
// DatastoreService is served by every agent and runs the MariaDB and PostgreSQL servers of
// networks: their containers, their databases, each with a user of the same name, and dumps of
// them. Only the servers of a datastore's network reach it: on its node over a Docker network
// without internet, from other nodes over the private network of the nodes. The superuser's
// password never leaves the node.
type DatastoreServiceServer interface {
	// ListDatastores returns the datastores of the node and the versions the agent runs.
	ListDatastores(context.Context, *ListDatastoresRequest) (*ListDatastoresResponse, error)
	CreateDatastore(context.Context, *CreateDatastoreRequest) (*CreateDatastoreResponse, error)
	StartDatastore(context.Context, *StartDatastoreRequest) (*StartDatastoreResponse, error)
	StopDatastore(context.Context, *StopDatastoreRequest) (*StopDatastoreResponse, error)
	// UpdateDatastore changes the limits of a datastore, pulls its image again, moves it to
	// another major version or removes the data a previous version left.
	UpdateDatastore(context.Context, *UpdateDatastoreRequest) (*UpdateDatastoreResponse, error)
	// PublishDatastore publishes the port of a datastore at the node's address in the private
	// network of the nodes, for the nodes of its network only, or no longer.
	PublishDatastore(context.Context, *PublishDatastoreRequest) (*PublishDatastoreResponse, error)
	// DeleteDatastore removes a datastore with its container, network, data and dumps.
	DeleteDatastore(context.Context, *DeleteDatastoreRequest) (*DeleteDatastoreResponse, error)
	// EnsureDatabase creates a database and its user, or sets the user's password, with rights
	// on that database only.
	EnsureDatabase(context.Context, *EnsureDatabaseRequest) (*EnsureDatabaseResponse, error)
	DropDatabase(context.Context, *DropDatabaseRequest) (*DropDatabaseResponse, error)
	// CreateDump dumps databases of a running datastore into a ZIP archive with one
	// <database>.sql each, kept like the backups of servers.
	CreateDump(context.Context, *CreateDumpRequest) (*CreateDumpResponse, error)
	ListDumps(context.Context, *ListDumpsRequest) (*ListDumpsResponse, error)
	// RestoreDump drops and creates databases again and loads their dumps as their own users.
	RestoreDump(context.Context, *RestoreDumpRequest) (*RestoreDumpResponse, error)
	DeleteDump(context.Context, *DeleteDumpRequest) (*DeleteDumpResponse, error)
	// DownloadDump sends a dump in chunks; the first message carries its size.
	DownloadDump(*DownloadDumpRequest, grpc.ServerStreamingServer[DownloadDumpResponse]) error
	// ImportDump adds a dump made elsewhere, e.g. of a database that moves to Noryx. The first
	// message describes it, the data that follows is a ZIP archive with a <database>.sql for
	// each database, or the SQL of a single database. The agent checks it and keeps it like
	// the dumps it makes, so that RestoreDump loads it as the databases' users.
	ImportDump(grpc.ClientStreamingServer[ImportDumpRequest, ImportDumpResponse]) error
	// ListTables returns the tables of a database of a running datastore.
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	// BrowseTable returns rows of a table as text, with long values cut short. It only reads,
	// with statements the agent builds itself.
	BrowseTable(context.Context, *BrowseTableRequest) (*BrowseTableResponse, error)
	// StreamDatastoreLogs sends the last lines of the log of a datastore's container, then
	// follows it until the container stops or the client disconnects, like StreamLogs of
	// servers. The agent hides passwords in the statements that the engines log, e.g. when
	// they fail.
	StreamDatastoreLogs(*StreamDatastoreLogsRequest, grpc.ServerStreamingServer[StreamDatastoreLogsResponse]) error
	mustEmbedUnimplementedDatastoreServiceServer()
}

// UnimplementedDatastoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatastoreServiceServer struct{}

func (UnimplementedDatastoreServiceServer) ListDatastores(context.Context, *ListDatastoresRequest) (*ListDatastoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatastores not implemented")
}
func (UnimplementedDatastoreServiceServer) CreateDatastore(context.Context, *CreateDatastoreRequest) (*CreateDatastoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDatastore not implemented")
}
func (UnimplementedDatastoreServiceServer) StartDatastore(context.Context, *StartDatastoreRequest) (*StartDatastoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDatastore not implemented")
}
func (UnimplementedDatastoreServiceServer) StopDatastore(context.Context, *StopDatastoreRequest) (*StopDatastoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopDatastore not implemented")
}
func (UnimplementedDatastoreServiceServer) UpdateDatastore(context.Context, *UpdateDatastoreRequest) (*UpdateDatastoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDatastore not implemented")
}
func (UnimplementedDatastoreServiceServer) PublishDatastore(context.Context, *PublishDatastoreRequest) (*PublishDatastoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishDatastore not implemented")
}
func (UnimplementedDatastoreServiceServer) DeleteDatastore(context.Context, *DeleteDatastoreRequest) (*DeleteDatastoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDatastore not implemented")
}
func (UnimplementedDatastoreServiceServer) EnsureDatabase(context.Context, *EnsureDatabaseRequest) (*EnsureDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureDatabase not implemented")
}
func (UnimplementedDatastoreServiceServer) DropDatabase(context.Context, *DropDatabaseRequest) (*DropDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropDatabase not implemented")
}
func (UnimplementedDatastoreServiceServer) CreateDump(context.Context, *CreateDumpRequest) (*CreateDumpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDump not implemented")
}
func (UnimplementedDatastoreServiceServer) ListDumps(context.Context, *ListDumpsRequest) (*ListDumpsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDumps not implemented")
}
func (UnimplementedDatastoreServiceServer) RestoreDump(context.Context, *RestoreDumpRequest) (*RestoreDumpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreDump not implemented")
}
func (UnimplementedDatastoreServiceServer) DeleteDump(context.Context, *DeleteDumpRequest) (*DeleteDumpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDump not implemented")
}
func (UnimplementedDatastoreServiceServer) DownloadDump(*DownloadDumpRequest, grpc.ServerStreamingServer[DownloadDumpResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadDump not implemented")
}
func (UnimplementedDatastoreServiceServer) ImportDump(grpc.ClientStreamingServer[ImportDumpRequest, ImportDumpResponse]) error {
	return status.Error(codes.Unimplemented, "method ImportDump not implemented")
}
func (UnimplementedDatastoreServiceServer) ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTables not implemented")
}
func (UnimplementedDatastoreServiceServer) BrowseTable(context.Context, *BrowseTableRequest) (*BrowseTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BrowseTable not implemented")
}
func (UnimplementedDatastoreServiceServer) StreamDatastoreLogs(*StreamDatastoreLogsRequest, grpc.ServerStreamingServer[StreamDatastoreLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamDatastoreLogs not implemented")
}
func (UnimplementedDatastoreServiceServer) mustEmbedUnimplementedDatastoreServiceServer() {}
func (UnimplementedDatastoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeDatastoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatastoreServiceServer will
// result in compilation errors.
type UnsafeDatastoreServiceServer interface {
	mustEmbedUnimplementedDatastoreServiceServer()
}

func RegisterDatastoreServiceServer(s grpc.ServiceRegistrar, srv DatastoreServiceServer) {
	// If the following call panics, it indicates UnimplementedDatastoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatastoreService_ServiceDesc, srv)
}

func _DatastoreService_ListDatastores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatastoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).ListDatastores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_ListDatastores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).ListDatastores(ctx, req.(*ListDatastoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_CreateDatastore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatastoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).CreateDatastore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_CreateDatastore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).CreateDatastore(ctx, req.(*CreateDatastoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_StartDatastore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDatastoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).StartDatastore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_StartDatastore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).StartDatastore(ctx, req.(*StartDatastoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_StopDatastore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDatastoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).StopDatastore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_StopDatastore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).StopDatastore(ctx, req.(*StopDatastoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_UpdateDatastore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatastoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).UpdateDatastore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_UpdateDatastore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).UpdateDatastore(ctx, req.(*UpdateDatastoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_PublishDatastore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishDatastoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).PublishDatastore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_PublishDatastore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).PublishDatastore(ctx, req.(*PublishDatastoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_DeleteDatastore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatastoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).DeleteDatastore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_DeleteDatastore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).DeleteDatastore(ctx, req.(*DeleteDatastoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_EnsureDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).EnsureDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_EnsureDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).EnsureDatabase(ctx, req.(*EnsureDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_DropDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).DropDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_DropDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).DropDatabase(ctx, req.(*DropDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_CreateDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).CreateDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_CreateDump_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).CreateDump(ctx, req.(*CreateDumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_ListDumps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDumpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).ListDumps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_ListDumps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).ListDumps(ctx, req.(*ListDumpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_RestoreDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreDumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).RestoreDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_RestoreDump_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).RestoreDump(ctx, req.(*RestoreDumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_DeleteDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).DeleteDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_DeleteDump_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).DeleteDump(ctx, req.(*DeleteDumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_DownloadDump_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadDumpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatastoreServiceServer).DownloadDump(m, &grpc.GenericServerStream[DownloadDumpRequest, DownloadDumpResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatastoreService_DownloadDumpServer = grpc.ServerStreamingServer[DownloadDumpResponse]

func _DatastoreService_ImportDump_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatastoreServiceServer).ImportDump(&grpc.GenericServerStream[ImportDumpRequest, ImportDumpResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatastoreService_ImportDumpServer = grpc.ClientStreamingServer[ImportDumpRequest, ImportDumpResponse]

func _DatastoreService_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_ListTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_BrowseTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).BrowseTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreService_BrowseTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).BrowseTable(ctx, req.(*BrowseTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_StreamDatastoreLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDatastoreLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatastoreServiceServer).StreamDatastoreLogs(m, &grpc.GenericServerStream[StreamDatastoreLogsRequest, StreamDatastoreLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatastoreService_StreamDatastoreLogsServer = grpc.ServerStreamingServer[StreamDatastoreLogsResponse]

// DatastoreService_ServiceDesc is the grpc.ServiceDesc for DatastoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatastoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noryx.v1.DatastoreService",
	HandlerType: (*DatastoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDatastores",
			Handler:    _DatastoreService_ListDatastores_Handler,
		},
		{
			MethodName: "CreateDatastore",
			Handler:    _DatastoreService_CreateDatastore_Handler,
		},
		{
			MethodName: "StartDatastore",
			Handler:    _DatastoreService_StartDatastore_Handler,
		},
		{
			MethodName: "StopDatastore",
			Handler:    _DatastoreService_StopDatastore_Handler,
		},
		{
			MethodName: "UpdateDatastore",
			Handler:    _DatastoreService_UpdateDatastore_Handler,
		},
		{
			MethodName: "PublishDatastore",
			Handler:    _DatastoreService_PublishDatastore_Handler,
		},
		{
			MethodName: "DeleteDatastore",
			Handler:    _DatastoreService_DeleteDatastore_Handler,
		},
		{
			MethodName: "EnsureDatabase",
			Handler:    _DatastoreService_EnsureDatabase_Handler,
		},
		{
			MethodName: "DropDatabase",
			Handler:    _DatastoreService_DropDatabase_Handler,
		},
		{
			MethodName: "CreateDump",
			Handler:    _DatastoreService_CreateDump_Handler,
		},
		{
			MethodName: "ListDumps",
			Handler:    _DatastoreService_ListDumps_Handler,
		},
		{
			MethodName: "RestoreDump",
			Handler:    _DatastoreService_RestoreDump_Handler,
		},
		{
			MethodName: "DeleteDump",
			Handler:    _DatastoreService_DeleteDump_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _DatastoreService_ListTables_Handler,
		},
		{
			MethodName: "BrowseTable",
			Handler:    _DatastoreService_BrowseTable_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadDump",
			Handler:       _DatastoreService_DownloadDump_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImportDump",
			Handler:       _DatastoreService_ImportDump_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamDatastoreLogs",
			Handler:       _DatastoreService_StreamDatastoreLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "noryx/v1/datastore.proto",
}
