// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: noryx/v1/fileset.proto

package noryxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileSetAction int32

const (
	FileSetAction_FILE_SET_ACTION_UNSPECIFIED FileSetAction = 0
	FileSetAction_FILE_SET_ACTION_UNCHANGED   FileSetAction = 1
	FileSetAction_FILE_SET_ACTION_CREATED     FileSetAction = 2
	FileSetAction_FILE_SET_ACTION_CHANGED     FileSetAction = 3
	FileSetAction_FILE_SET_ACTION_REMOVED     FileSetAction = 4
	// The set no longer has the file, which changed on the server since it was written, so it
	// stays as a file of the server.
	FileSetAction_FILE_SET_ACTION_KEPT FileSetAction = 5
)

// Enum value maps for FileSetAction.
var (
	FileSetAction_name = map[int32]string{
		0: "FILE_SET_ACTION_UNSPECIFIED",
		1: "FILE_SET_ACTION_UNCHANGED",
		2: "FILE_SET_ACTION_CREATED",
		3: "FILE_SET_ACTION_CHANGED",
		4: "FILE_SET_ACTION_REMOVED",
		5: "FILE_SET_ACTION_KEPT",
	}
	FileSetAction_value = map[string]int32{
		"FILE_SET_ACTION_UNSPECIFIED": 0,
		"FILE_SET_ACTION_UNCHANGED":   1,
		"FILE_SET_ACTION_CREATED":     2,
		"FILE_SET_ACTION_CHANGED":     3,
		"FILE_SET_ACTION_REMOVED":     4,
		"FILE_SET_ACTION_KEPT":        5,
	}
)

func (x FileSetAction) Enum() *FileSetAction {
	p := new(FileSetAction)
	*p = x
	return p
}

func (x FileSetAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileSetAction) Descriptor() protoreflect.EnumDescriptor {
	return file_noryx_v1_fileset_proto_enumTypes[0].Descriptor()
}

func (FileSetAction) Type() protoreflect.EnumType {
	return &file_noryx_v1_fileset_proto_enumTypes[0]
}

func (x FileSetAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileSetAction.Descriptor instead.
func (FileSetAction) EnumDescriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{0}
}

type FileSetRemoval int32

const (
	FileSetRemoval_FILE_SET_REMOVAL_UNSPECIFIED FileSetRemoval = 0
	// Removes the files with secrets. The others stay part of the set, until applying it
	// removes them.
	FileSetRemoval_FILE_SET_REMOVAL_SECRETS FileSetRemoval = 1
	// Removes the files with secrets and the others that didn't change since they were
	// written. Changed files stay as files of the server.
	FileSetRemoval_FILE_SET_REMOVAL_UNCHANGED FileSetRemoval = 2
	// Removes the files with secrets. The others stay as files of the server.
	FileSetRemoval_FILE_SET_REMOVAL_FORGET FileSetRemoval = 3
)

// Enum value maps for FileSetRemoval.
var (
	FileSetRemoval_name = map[int32]string{
		0: "FILE_SET_REMOVAL_UNSPECIFIED",
		1: "FILE_SET_REMOVAL_SECRETS",
		2: "FILE_SET_REMOVAL_UNCHANGED",
		3: "FILE_SET_REMOVAL_FORGET",
	}
	FileSetRemoval_value = map[string]int32{
		"FILE_SET_REMOVAL_UNSPECIFIED": 0,
		"FILE_SET_REMOVAL_SECRETS":     1,
		"FILE_SET_REMOVAL_UNCHANGED":   2,
		"FILE_SET_REMOVAL_FORGET":      3,
	}
)

func (x FileSetRemoval) Enum() *FileSetRemoval {
	p := new(FileSetRemoval)
	*p = x
	return p
}

func (x FileSetRemoval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileSetRemoval) Descriptor() protoreflect.EnumDescriptor {
	return file_noryx_v1_fileset_proto_enumTypes[1].Descriptor()
}

func (FileSetRemoval) Type() protoreflect.EnumType {
	return &file_noryx_v1_fileset_proto_enumTypes[1]
}

func (x FileSetRemoval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileSetRemoval.Descriptor instead.
func (FileSetRemoval) EnumDescriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{1}
}

type FileSetFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative to the server's data directory, with forward slashes.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// UTF-8 text. {{secret:<name>}} and {{datastore:<name>.<database>.password}} are filled
	// in from the secrets of the request.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Writes the file only if the server has none, for files that plugins rewrite.
	OnlyIfMissing bool `protobuf:"varint,3,opt,name=only_if_missing,json=onlyIfMissing,proto3" json:"only_if_missing,omitempty"`
	// The content of a binary file, e.g. an image, instead of content; nothing is filled in.
	// Agents that don't report binary_files in ListFileSetsResponse ignore it.
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSetFile) Reset() {
	*x = FileSetFile{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSetFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSetFile) ProtoMessage() {}

func (x *FileSetFile) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSetFile.ProtoReflect.Descriptor instead.
func (*FileSetFile) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{0}
}

func (x *FileSetFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileSetFile) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileSetFile) GetOnlyIfMissing() bool {
	if x != nil {
		return x.OnlyIfMissing
	}
	return false
}

func (x *FileSetFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApplyFileSetRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SetId    string                 `protobuf:"bytes,2,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	// The set's name, which the file manager shows next to its files.
	SetName string `protobuf:"bytes,3,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	Version int64  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// Identifies what the master sent, which ListFileSets returns; the master tells by it
	// whether the server has the newest state of the set.
	Revision string         `protobuf:"bytes,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Files    []*FileSetFile `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
	// The values of the placeholders that only the agent fills in, by what is between the
	// braces, e.g. secret:db-password or datastore:main.luckperms.password.
	Secrets map[string]string `protobuf:"bytes,7,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Only tells what would change.
	DryRun        bool `protobuf:"varint,8,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyFileSetRequest) Reset() {
	*x = ApplyFileSetRequest{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFileSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFileSetRequest) ProtoMessage() {}

func (x *ApplyFileSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFileSetRequest.ProtoReflect.Descriptor instead.
func (*ApplyFileSetRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyFileSetRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ApplyFileSetRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *ApplyFileSetRequest) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

func (x *ApplyFileSetRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ApplyFileSetRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ApplyFileSetRequest) GetFiles() []*FileSetFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ApplyFileSetRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ApplyFileSetRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type FileSetChange struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Path   string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Action FileSetAction          `protobuf:"varint,2,opt,name=action,proto3,enum=noryx.v1.FileSetAction" json:"action,omitempty"`
	// The file holds secrets, so the panel never shows it.
	Secret        bool `protobuf:"varint,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSetChange) Reset() {
	*x = FileSetChange{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSetChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSetChange) ProtoMessage() {}

func (x *FileSetChange) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSetChange.ProtoReflect.Descriptor instead.
func (*FileSetChange) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{2}
}

func (x *FileSetChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileSetChange) GetAction() FileSetAction {
	if x != nil {
		return x.Action
	}
	return FileSetAction_FILE_SET_ACTION_UNSPECIFIED
}

func (x *FileSetChange) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

type ApplyFileSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*FileSetChange       `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyFileSetResponse) Reset() {
	*x = ApplyFileSetResponse{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFileSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFileSetResponse) ProtoMessage() {}

func (x *ApplyFileSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFileSetResponse.ProtoReflect.Descriptor instead.
func (*ApplyFileSetResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyFileSetResponse) GetChanges() []*FileSetChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type RemoveFileSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SetId         string                 `protobuf:"bytes,2,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	Removal       FileSetRemoval         `protobuf:"varint,3,opt,name=removal,proto3,enum=noryx.v1.FileSetRemoval" json:"removal,omitempty"`
	DryRun        bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileSetRequest) Reset() {
	*x = RemoveFileSetRequest{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileSetRequest) ProtoMessage() {}

func (x *RemoveFileSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileSetRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileSetRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFileSetRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RemoveFileSetRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *RemoveFileSetRequest) GetRemoval() FileSetRemoval {
	if x != nil {
		return x.Removal
	}
	return FileSetRemoval_FILE_SET_REMOVAL_UNSPECIFIED
}

func (x *RemoveFileSetRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type RemoveFileSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*FileSetChange       `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileSetResponse) Reset() {
	*x = RemoveFileSetResponse{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileSetResponse) ProtoMessage() {}

func (x *RemoveFileSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileSetResponse.ProtoReflect.Descriptor instead.
func (*RemoveFileSetResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveFileSetResponse) GetChanges() []*FileSetChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type ListFileSetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileSetsRequest) Reset() {
	*x = ListFileSetsRequest{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileSetsRequest) ProtoMessage() {}

func (x *ListFileSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileSetsRequest.ProtoReflect.Descriptor instead.
func (*ListFileSetsRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{6}
}

type ListFileSetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only servers that have files of sets.
	Servers []*ServerFileSets `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// The agent writes binary files (FileSetFile.data). Older agents would write them empty,
	// so the master sends them none.
	BinaryFiles bool `protobuf:"varint,2,opt,name=binary_files,json=binaryFiles,proto3" json:"binary_files,omitempty"`
	// The agent fills in the passwords of databases. Older agents refuse them.
	DatabasePasswords bool `protobuf:"varint,3,opt,name=database_passwords,json=databasePasswords,proto3" json:"database_passwords,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListFileSetsResponse) Reset() {
	*x = ListFileSetsResponse{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileSetsResponse) ProtoMessage() {}

func (x *ListFileSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileSetsResponse.ProtoReflect.Descriptor instead.
func (*ListFileSetsResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{7}
}

func (x *ListFileSetsResponse) GetServers() []*ServerFileSets {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ListFileSetsResponse) GetBinaryFiles() bool {
	if x != nil {
		return x.BinaryFiles
	}
	return false
}

func (x *ListFileSetsResponse) GetDatabasePasswords() bool {
	if x != nil {
		return x.DatabasePasswords
	}
	return false
}

type ServerFileSets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Sets          []*AppliedFileSet      `protobuf:"bytes,2,rep,name=sets,proto3" json:"sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFileSets) Reset() {
	*x = ServerFileSets{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFileSets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFileSets) ProtoMessage() {}

func (x *ServerFileSets) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFileSets.ProtoReflect.Descriptor instead.
func (*ServerFileSets) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{8}
}

func (x *ServerFileSets) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerFileSets) GetSets() []*AppliedFileSet {
	if x != nil {
		return x.Sets
	}
	return nil
}

type AppliedFileSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetId         string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Revision      string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Files         []*AppliedFile         `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppliedFileSet) Reset() {
	*x = AppliedFileSet{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedFileSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedFileSet) ProtoMessage() {}

func (x *AppliedFileSet) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedFileSet.ProtoReflect.Descriptor instead.
func (*AppliedFileSet) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{9}
}

func (x *AppliedFileSet) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *AppliedFileSet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AppliedFileSet) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *AppliedFileSet) GetFiles() []*AppliedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type AppliedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Secret        bool                   `protobuf:"varint,2,opt,name=secret,proto3" json:"secret,omitempty"`
	OnlyIfMissing bool                   `protobuf:"varint,3,opt,name=only_if_missing,json=onlyIfMissing,proto3" json:"only_if_missing,omitempty"`
	// The file differs from what was written, or is gone.
	Changed       bool `protobuf:"varint,4,opt,name=changed,proto3" json:"changed,omitempty"`
	Missing       bool `protobuf:"varint,5,opt,name=missing,proto3" json:"missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppliedFile) Reset() {
	*x = AppliedFile{}
	mi := &file_noryx_v1_fileset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedFile) ProtoMessage() {}

func (x *AppliedFile) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_fileset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedFile.ProtoReflect.Descriptor instead.
func (*AppliedFile) Descriptor() ([]byte, []int) {
	return file_noryx_v1_fileset_proto_rawDescGZIP(), []int{10}
}

func (x *AppliedFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AppliedFile) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *AppliedFile) GetOnlyIfMissing() bool {
	if x != nil {
		return x.OnlyIfMissing
	}
	return false
}

func (x *AppliedFile) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *AppliedFile) GetMissing() bool {
	if x != nil {
		return x.Missing
	}
	return false
}

var File_noryx_v1_fileset_proto protoreflect.FileDescriptor

const file_noryx_v1_fileset_proto_rawDesc = "" +
	"\n" +
	"\x16noryx/v1/fileset.proto\x12\bnoryx.v1\"w\n" +
	"\vFileSetFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12&\n" +
	"\x0fonly_if_missing\x18\x03 \x01(\bR\ronlyIfMissing\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xe2\x02\n" +
	"\x13ApplyFileSetRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x15\n" +
	"\x06set_id\x18\x02 \x01(\tR\x05setId\x12\x19\n" +
	"\bset_name\x18\x03 \x01(\tR\asetName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\tR\brevision\x12+\n" +
	"\x05files\x18\x06 \x03(\v2\x15.noryx.v1.FileSetFileR\x05files\x12D\n" +
	"\asecrets\x18\a \x03(\v2*.noryx.v1.ApplyFileSetRequest.SecretsEntryR\asecrets\x12\x17\n" +
	"\adry_run\x18\b \x01(\bR\x06dryRun\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\rFileSetChange\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12/\n" +
	"\x06action\x18\x02 \x01(\x0e2\x17.noryx.v1.FileSetActionR\x06action\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\bR\x06secret\"I\n" +
	"\x14ApplyFileSetResponse\x121\n" +
	"\achanges\x18\x01 \x03(\v2\x17.noryx.v1.FileSetChangeR\achanges\"\x97\x01\n" +
	"\x14RemoveFileSetRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x15\n" +
	"\x06set_id\x18\x02 \x01(\tR\x05setId\x122\n" +
	"\aremoval\x18\x03 \x01(\x0e2\x18.noryx.v1.FileSetRemovalR\aremoval\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"J\n" +
	"\x15RemoveFileSetResponse\x121\n" +
	"\achanges\x18\x01 \x03(\v2\x17.noryx.v1.FileSetChangeR\achanges\"\x15\n" +
	"\x13ListFileSetsRequest\"\x9c\x01\n" +
	"\x14ListFileSetsResponse\x122\n" +
	"\aservers\x18\x01 \x03(\v2\x18.noryx.v1.ServerFileSetsR\aservers\x12!\n" +
	"\fbinary_files\x18\x02 \x01(\bR\vbinaryFiles\x12-\n" +
	"\x12database_passwords\x18\x03 \x01(\bR\x11databasePasswords\"[\n" +
	"\x0eServerFileSets\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12,\n" +
	"\x04sets\x18\x02 \x03(\v2\x18.noryx.v1.AppliedFileSetR\x04sets\"\x8a\x01\n" +
	"\x0eAppliedFileSet\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12+\n" +
	"\x05files\x18\x04 \x03(\v2\x15.noryx.v1.AppliedFileR\x05files\"\x95\x01\n" +
	"\vAppliedFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\bR\x06secret\x12&\n" +
	"\x0fonly_if_missing\x18\x03 \x01(\bR\ronlyIfMissing\x12\x18\n" +
	"\achanged\x18\x04 \x01(\bR\achanged\x12\x18\n" +
	"\amissing\x18\x05 \x01(\bR\amissing*\xc0\x01\n" +
	"\rFileSetAction\x12\x1f\n" +
	"\x1bFILE_SET_ACTION_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FILE_SET_ACTION_UNCHANGED\x10\x01\x12\x1b\n" +
	"\x17FILE_SET_ACTION_CREATED\x10\x02\x12\x1b\n" +
	"\x17FILE_SET_ACTION_CHANGED\x10\x03\x12\x1b\n" +
	"\x17FILE_SET_ACTION_REMOVED\x10\x04\x12\x18\n" +
	"\x14FILE_SET_ACTION_KEPT\x10\x05*\x8d\x01\n" +
	"\x0eFileSetRemoval\x12 \n" +
	"\x1cFILE_SET_REMOVAL_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FILE_SET_REMOVAL_SECRETS\x10\x01\x12\x1e\n" +
	"\x1aFILE_SET_REMOVAL_UNCHANGED\x10\x02\x12\x1b\n" +
	"\x17FILE_SET_REMOVAL_FORGET\x10\x032\x80\x02\n" +
	"\x0eFileSetService\x12M\n" +
	"\fApplyFileSet\x12\x1d.noryx.v1.ApplyFileSetRequest\x1a\x1e.noryx.v1.ApplyFileSetResponse\x12P\n" +
	"\rRemoveFileSet\x12\x1e.noryx.v1.RemoveFileSetRequest\x1a\x1f.noryx.v1.RemoveFileSetResponse\x12M\n" +
	"\fListFileSets\x12\x1d.noryx.v1.ListFileSetsRequest\x1a\x1e.noryx.v1.ListFileSetsResponseB0Z.github.com/QwikByte/noryx/api/noryx/v1;noryxv1b\x06proto3"

var (
	file_noryx_v1_fileset_proto_rawDescOnce sync.Once
	file_noryx_v1_fileset_proto_rawDescData []byte
)

func file_noryx_v1_fileset_proto_rawDescGZIP() []byte {
	file_noryx_v1_fileset_proto_rawDescOnce.Do(func() {
		file_noryx_v1_fileset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noryx_v1_fileset_proto_rawDesc), len(file_noryx_v1_fileset_proto_rawDesc)))
	})
	return file_noryx_v1_fileset_proto_rawDescData
}

var file_noryx_v1_fileset_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_noryx_v1_fileset_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_noryx_v1_fileset_proto_goTypes = []any{
	(FileSetAction)(0),            // 0: noryx.v1.FileSetAction
	(FileSetRemoval)(0),           // 1: noryx.v1.FileSetRemoval
	(*FileSetFile)(nil),           // 2: noryx.v1.FileSetFile
	(*ApplyFileSetRequest)(nil),   // 3: noryx.v1.ApplyFileSetRequest
	(*FileSetChange)(nil),         // 4: noryx.v1.FileSetChange
	(*ApplyFileSetResponse)(nil),  // 5: noryx.v1.ApplyFileSetResponse
	(*RemoveFileSetRequest)(nil),  // 6: noryx.v1.RemoveFileSetRequest
	(*RemoveFileSetResponse)(nil), // 7: noryx.v1.RemoveFileSetResponse
	(*ListFileSetsRequest)(nil),   // 8: noryx.v1.ListFileSetsRequest
	(*ListFileSetsResponse)(nil),  // 9: noryx.v1.ListFileSetsResponse
	(*ServerFileSets)(nil),        // 10: noryx.v1.ServerFileSets
	(*AppliedFileSet)(nil),        // 11: noryx.v1.AppliedFileSet
	(*AppliedFile)(nil),           // 12: noryx.v1.AppliedFile
	nil,                           // 13: noryx.v1.ApplyFileSetRequest.SecretsEntry
}
var file_noryx_v1_fileset_proto_depIdxs = []int32{
	2,  // 0: noryx.v1.ApplyFileSetRequest.files:type_name -> noryx.v1.FileSetFile
	13, // 1: noryx.v1.ApplyFileSetRequest.secrets:type_name -> noryx.v1.ApplyFileSetRequest.SecretsEntry
	0,  // 2: noryx.v1.FileSetChange.action:type_name -> noryx.v1.FileSetAction
	4,  // 3: noryx.v1.ApplyFileSetResponse.changes:type_name -> noryx.v1.FileSetChange
	1,  // 4: noryx.v1.RemoveFileSetRequest.removal:type_name -> noryx.v1.FileSetRemoval
	4,  // 5: noryx.v1.RemoveFileSetResponse.changes:type_name -> noryx.v1.FileSetChange
	10, // 6: noryx.v1.ListFileSetsResponse.servers:type_name -> noryx.v1.ServerFileSets
	11, // 7: noryx.v1.ServerFileSets.sets:type_name -> noryx.v1.AppliedFileSet
	12, // 8: noryx.v1.AppliedFileSet.files:type_name -> noryx.v1.AppliedFile
	3,  // 9: noryx.v1.FileSetService.ApplyFileSet:input_type -> noryx.v1.ApplyFileSetRequest
	6,  // 10: noryx.v1.FileSetService.RemoveFileSet:input_type -> noryx.v1.RemoveFileSetRequest
	8,  // 11: noryx.v1.FileSetService.ListFileSets:input_type -> noryx.v1.ListFileSetsRequest
	5,  // 12: noryx.v1.FileSetService.ApplyFileSet:output_type -> noryx.v1.ApplyFileSetResponse
	7,  // 13: noryx.v1.FileSetService.RemoveFileSet:output_type -> noryx.v1.RemoveFileSetResponse
	9,  // 14: noryx.v1.FileSetService.ListFileSets:output_type -> noryx.v1.ListFileSetsResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_noryx_v1_fileset_proto_init() }
func file_noryx_v1_fileset_proto_init() {
	if File_noryx_v1_fileset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noryx_v1_fileset_proto_rawDesc), len(file_noryx_v1_fileset_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noryx_v1_fileset_proto_goTypes,
		DependencyIndexes: file_noryx_v1_fileset_proto_depIdxs,
		EnumInfos:         file_noryx_v1_fileset_proto_enumTypes,
		MessageInfos:      file_noryx_v1_fileset_proto_msgTypes,
	}.Build()
	File_noryx_v1_fileset_proto = out.File
	file_noryx_v1_fileset_proto_goTypes = nil
	file_noryx_v1_fileset_proto_depIdxs = nil
}
