// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: noryx/v1/fileset.proto

package noryxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileSetService_ApplyFileSet_FullMethodName  = "/noryx.v1.FileSetService/ApplyFileSet"
	FileSetService_RemoveFileSet_FullMethodName = "/noryx.v1.FileSetService/RemoveFileSet"
	FileSetService_ListFileSets_FullMethodName  = "/noryx.v1.FileSetService/ListFileSets"
)

// FileSetServiceClient is the client API for FileSetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FileSetService is served by every agent and keeps the files of file sets on its servers:
// files that the master manages for groups of servers, e.g. the configuration of a plugin or
// an image. Each server records in its data which set wrote which file. Files that hold
// secrets of a set are hidden like the RCON password, also after they left the set.
type FileSetServiceClient interface {
	// ApplyFileSet writes the files of a set to a server, with its secrets filled in, and
	// removes those the set no longer has unless they changed on the server since. An unknown
	// placeholder, a missing secret or a path that another set wrote fails before anything
	// is written.
	ApplyFileSet(ctx context.Context, in *ApplyFileSetRequest, opts ...grpc.CallOption) (*ApplyFileSetResponse, error)
	// RemoveFileSet takes a set off a server, e.g. as it is no longer a target.
	RemoveFileSet(ctx context.Context, in *RemoveFileSetRequest, opts ...grpc.CallOption) (*RemoveFileSetResponse, error)
	// ListFileSets returns the sets on each server of the node, and which files changed since
	// they were written.
	ListFileSets(ctx context.Context, in *ListFileSetsRequest, opts ...grpc.CallOption) (*ListFileSetsResponse, error)
}

type fileSetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileSetServiceClient(cc grpc.ClientConnInterface) FileSetServiceClient {
	return &fileSetServiceClient{cc}
}

func (c *fileSetServiceClient) ApplyFileSet(ctx context.Context, in *ApplyFileSetRequest, opts ...grpc.CallOption) (*ApplyFileSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyFileSetResponse)
	err := c.cc.Invoke(ctx, FileSetService_ApplyFileSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSetServiceClient) RemoveFileSet(ctx context.Context, in *RemoveFileSetRequest, opts ...grpc.CallOption) (*RemoveFileSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFileSetResponse)
	err := c.cc.Invoke(ctx, FileSetService_RemoveFileSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSetServiceClient) ListFileSets(ctx context.Context, in *ListFileSetsRequest, opts ...grpc.CallOption) (*ListFileSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileSetsResponse)
	err := c.cc.Invoke(ctx, FileSetService_ListFileSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileSetServiceServer is the server API for FileSetService service.
// All implementations must embed UnimplementedFileSetServiceServer
// for forward compatibility.
//
// FileSetService is served by every agent and keeps the files of file sets on its servers:
// files that the master manages for groups of servers, e.g. the configuration of a plugin or
// an image. Each server records in its data which set wrote which file. Files that hold
// secrets of a set are hidden like the RCON password, also after they left the set.
type FileSetServiceServer interface {
	// ApplyFileSet writes the files of a set to a server, with its secrets filled in, and
	// removes those the set no longer has unless they changed on the server since. An unknown
	// placeholder, a missing secret or a path that another set wrote fails before anything
	// is written.
	ApplyFileSet(context.Context, *ApplyFileSetRequest) (*ApplyFileSetResponse, error)
	// RemoveFileSet takes a set off a server, e.g. as it is no longer a target.
	RemoveFileSet(context.Context, *RemoveFileSetRequest) (*RemoveFileSetResponse, error)
	// ListFileSets returns the sets on each server of the node, and which files changed since
	// they were written.
	ListFileSets(context.Context, *ListFileSetsRequest) (*ListFileSetsResponse, error)
	mustEmbedUnimplementedFileSetServiceServer()
}

// UnimplementedFileSetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileSetServiceServer struct{}

func (UnimplementedFileSetServiceServer) ApplyFileSet(context.Context, *ApplyFileSetRequest) (*ApplyFileSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyFileSet not implemented")
}
func (UnimplementedFileSetServiceServer) RemoveFileSet(context.Context, *RemoveFileSetRequest) (*RemoveFileSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFileSet not implemented")
}
func (UnimplementedFileSetServiceServer) ListFileSets(context.Context, *ListFileSetsRequest) (*ListFileSetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFileSets not implemented")
}
func (UnimplementedFileSetServiceServer) mustEmbedUnimplementedFileSetServiceServer() {}
func (UnimplementedFileSetServiceServer) testEmbeddedByValue()                        {}

// UnsafeFileSetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileSetServiceServer will
// result in compilation errors.
type UnsafeFileSetServiceServer interface {
	mustEmbedUnimplementedFileSetServiceServer()
}

func RegisterFileSetServiceServer(s grpc.ServiceRegistrar, srv FileSetServiceServer) {
	// If the following call panics, it indicates UnimplementedFileSetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileSetService_ServiceDesc, srv)
}

func _FileSetService_ApplyFileSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyFileSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSetServiceServer).ApplyFileSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSetService_ApplyFileSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSetServiceServer).ApplyFileSet(ctx, req.(*ApplyFileSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSetService_RemoveFileSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFileSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSetServiceServer).RemoveFileSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSetService_RemoveFileSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSetServiceServer).RemoveFileSet(ctx, req.(*RemoveFileSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSetService_ListFileSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSetServiceServer).ListFileSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSetService_ListFileSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSetServiceServer).ListFileSets(ctx, req.(*ListFileSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileSetService_ServiceDesc is the grpc.ServiceDesc for FileSetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileSetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noryx.v1.FileSetService",
	HandlerType: (*FileSetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyFileSet",
			Handler:    _FileSetService_ApplyFileSet_Handler,
		},
		{
			MethodName: "RemoveFileSet",
			Handler:    _FileSetService_RemoveFileSet_Handler,
		},
		{
			MethodName: "ListFileSets",
			Handler:    _FileSetService_ListFileSets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noryx/v1/fileset.proto",
}
