// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: noryx/v1/node.proto

package noryxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_noryx_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_node_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname     string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os           string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	CpuCount     uint32                 `protobuf:"varint,4,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryBytes  uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// Container runtime driving the servers, e.g. "docker 29.0.0", or "unavailable"
	// while the agent can't reach it; os, cpu_count and memory_bytes are empty then.
	Runtime string `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Where servers can keep their data; the default location comes first.
	Storage []*StorageLocation `protobuf:"bytes,7,rep,name=storage,proto3" json:"storage,omitempty"`
	// When the certificate the agent presents to the master expires.
	CertificateNotAfterUnix int64 `protobuf:"varint,8,opt,name=certificate_not_after_unix,json=certificateNotAfterUnix,proto3" json:"certificate_not_after_unix,omitempty"`
	// The container runtime the agent is set to use, "docker" or "podman", also while it
	// can't reach it, and its version, e.g. "29.0.0", empty then. Older agents leave both
	// empty, as they only run Docker; runtime tells its version.
	RuntimeName    string `protobuf:"bytes,9,opt,name=runtime_name,json=runtimeName,proto3" json:"runtime_name,omitempty"`
	RuntimeVersion string `protobuf:"bytes,10,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_noryx_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *GetInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetInfoResponse) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *GetInfoResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *GetInfoResponse) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *GetInfoResponse) GetStorage() []*StorageLocation {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *GetInfoResponse) GetCertificateNotAfterUnix() int64 {
	if x != nil {
		return x.CertificateNotAfterUnix
	}
	return 0
}

func (x *GetInfoResponse) GetRuntimeName() string {
	if x != nil {
		return x.RuntimeName
	}
	return ""
}

func (x *GetInfoResponse) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

// StorageLocation is a directory the node's administrator allowed for server data.
type StorageLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,3,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageLocation) Reset() {
	*x = StorageLocation{}
	mi := &file_noryx_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageLocation) ProtoMessage() {}

func (x *StorageLocation) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageLocation.ProtoReflect.Descriptor instead.
func (*StorageLocation) Descriptor() ([]byte, []int) {
	return file_noryx_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *StorageLocation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageLocation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StorageLocation) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *StorageLocation) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type CreateCSRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCSRRequest) Reset() {
	*x = CreateCSRRequest{}
	mi := &file_noryx_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCSRRequest) ProtoMessage() {}

func (x *CreateCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCSRRequest.ProtoReflect.Descriptor instead.
func (*CreateCSRRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_node_proto_rawDescGZIP(), []int{3}
}

type CreateCSRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrDer        []byte                 `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCSRResponse) Reset() {
	*x = CreateCSRResponse{}
	mi := &file_noryx_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCSRResponse) ProtoMessage() {}

func (x *CreateCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCSRResponse.ProtoReflect.Descriptor instead.
func (*CreateCSRResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCSRResponse) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type InstallCertificateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificateDer []byte                 `protobuf:"bytes,1,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstallCertificateRequest) Reset() {
	*x = InstallCertificateRequest{}
	mi := &file_noryx_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallCertificateRequest) ProtoMessage() {}

func (x *InstallCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallCertificateRequest.ProtoReflect.Descriptor instead.
func (*InstallCertificateRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *InstallCertificateRequest) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

type InstallCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallCertificateResponse) Reset() {
	*x = InstallCertificateResponse{}
	mi := &file_noryx_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallCertificateResponse) ProtoMessage() {}

func (x *InstallCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallCertificateResponse.ProtoReflect.Descriptor instead.
func (*InstallCertificateResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_node_proto_rawDescGZIP(), []int{6}
}

type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Release to install, e.g. "v1.2.0".
	Version       string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_noryx_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_noryx_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_node_proto_rawDescGZIP(), []int{8}
}

var File_noryx_v1_node_proto protoreflect.FileDescriptor

const file_noryx_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x13noryx/v1/node.proto\x12\bnoryx.v1\"\x10\n" +
	"\x0eGetInfoRequest\"\xfa\x02\n" +
	"\x0fGetInfoResponse\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1b\n" +
	"\tcpu_count\x18\x04 \x01(\rR\bcpuCount\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12\x18\n" +
	"\aruntime\x18\x06 \x01(\tR\aruntime\x123\n" +
	"\astorage\x18\a \x03(\v2\x19.noryx.v1.StorageLocationR\astorage\x12;\n" +
	"\x1acertificate_not_after_unix\x18\b \x01(\x03R\x17certificateNotAfterUnix\x12!\n" +
	"\fruntime_name\x18\t \x01(\tR\vruntimeName\x12'\n" +
	"\x0fruntime_version\x18\n" +
	" \x01(\tR\x0eruntimeVersion\"y\n" +
	"\x0fStorageLocation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x03 \x01(\x04R\tfreeBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\"\x12\n" +
	"\x10CreateCSRRequest\",\n" +
	"\x11CreateCSRResponse\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\"D\n" +
	"\x19InstallCertificateRequest\x12'\n" +
	"\x0fcertificate_der\x18\x01 \x01(\fR\x0ecertificateDer\"\x1c\n" +
	"\x1aInstallCertificateResponse\")\n" +
	"\rUpdateRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x10\n" +
	"\x0eUpdateResponse2\xb1\x02\n" +
	"\vNodeService\x12>\n" +
	"\aGetInfo\x12\x18.noryx.v1.GetInfoRequest\x1a\x19.noryx.v1.GetInfoResponse\x12D\n" +
	"\tCreateCSR\x12\x1a.noryx.v1.CreateCSRRequest\x1a\x1b.noryx.v1.CreateCSRResponse\x12_\n" +
	"\x12InstallCertificate\x12#.noryx.v1.InstallCertificateRequest\x1a$.noryx.v1.InstallCertificateResponse\x12;\n" +
	"\x06Update\x12\x17.noryx.v1.UpdateRequest\x1a\x18.noryx.v1.UpdateResponseB0Z.github.com/QwikByte/noryx/api/noryx/v1;noryxv1b\x06proto3"

var (
	file_noryx_v1_node_proto_rawDescOnce sync.Once
	file_noryx_v1_node_proto_rawDescData []byte
)

func file_noryx_v1_node_proto_rawDescGZIP() []byte {
	file_noryx_v1_node_proto_rawDescOnce.Do(func() {
		file_noryx_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noryx_v1_node_proto_rawDesc), len(file_noryx_v1_node_proto_rawDesc)))
	})
	return file_noryx_v1_node_proto_rawDescData
}

var file_noryx_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_noryx_v1_node_proto_goTypes = []any{
	(*GetInfoRequest)(nil),             // 0: noryx.v1.GetInfoRequest
	(*GetInfoResponse)(nil),            // 1: noryx.v1.GetInfoResponse
	(*StorageLocation)(nil),            // 2: noryx.v1.StorageLocation
	(*CreateCSRRequest)(nil),           // 3: noryx.v1.CreateCSRRequest
	(*CreateCSRResponse)(nil),          // 4: noryx.v1.CreateCSRResponse
	(*InstallCertificateRequest)(nil),  // 5: noryx.v1.InstallCertificateRequest
	(*InstallCertificateResponse)(nil), // 6: noryx.v1.InstallCertificateResponse
	(*UpdateRequest)(nil),              // 7: noryx.v1.UpdateRequest
	(*UpdateResponse)(nil),             // 8: noryx.v1.UpdateResponse
}
var file_noryx_v1_node_proto_depIdxs = []int32{
	2, // 0: noryx.v1.GetInfoResponse.storage:type_name -> noryx.v1.StorageLocation
	0, // 1: noryx.v1.NodeService.GetInfo:input_type -> noryx.v1.GetInfoRequest
	3, // 2: noryx.v1.NodeService.CreateCSR:input_type -> noryx.v1.CreateCSRRequest
	5, // 3: noryx.v1.NodeService.InstallCertificate:input_type -> noryx.v1.InstallCertificateRequest
	7, // 4: noryx.v1.NodeService.Update:input_type -> noryx.v1.UpdateRequest
	1, // 5: noryx.v1.NodeService.GetInfo:output_type -> noryx.v1.GetInfoResponse
	4, // 6: noryx.v1.NodeService.CreateCSR:output_type -> noryx.v1.CreateCSRResponse
	6, // 7: noryx.v1.NodeService.InstallCertificate:output_type -> noryx.v1.InstallCertificateResponse
	8, // 8: noryx.v1.NodeService.Update:output_type -> noryx.v1.UpdateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_noryx_v1_node_proto_init() }
func file_noryx_v1_node_proto_init() {
	if File_noryx_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noryx_v1_node_proto_rawDesc), len(file_noryx_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noryx_v1_node_proto_goTypes,
		DependencyIndexes: file_noryx_v1_node_proto_depIdxs,
		MessageInfos:      file_noryx_v1_node_proto_msgTypes,
	}.Build()
	File_noryx_v1_node_proto = out.File
	file_noryx_v1_node_proto_goTypes = nil
	file_noryx_v1_node_proto_depIdxs = nil
}
