// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: noryx/v1/overlay.proto

package noryxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOverlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverlayRequest) Reset() {
	*x = GetOverlayRequest{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverlayRequest) ProtoMessage() {}

func (x *GetOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverlayRequest.ProtoReflect.Descriptor instead.
func (*GetOverlayRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{0}
}

type GetOverlayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's administrator allowed the node to join.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Why the node can't run WireGuard, e.g. as its kernel lacks it; empty if it can.
	Unsupported string `protobuf:"bytes,2,opt,name=unsupported,proto3" json:"unsupported,omitempty"`
	// The node's public key, base64; empty unless it is allowed.
	PublicKey string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The node's address with the prefix of the network, e.g. 10.213.0.3/24; empty unless it
	// is a member.
	Address       string               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Peers         []*OverlayPeerStatus `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverlayResponse) Reset() {
	*x = GetOverlayResponse{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverlayResponse) ProtoMessage() {}

func (x *GetOverlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverlayResponse.ProtoReflect.Descriptor instead.
func (*GetOverlayResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{1}
}

func (x *GetOverlayResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *GetOverlayResponse) GetUnsupported() string {
	if x != nil {
		return x.Unsupported
	}
	return ""
}

func (x *GetOverlayResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetOverlayResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetOverlayResponse) GetPeers() []*OverlayPeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

type OverlayPeerStatus struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PublicKey string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// host:port the peer last sent from, or is reached at.
	Endpoint string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// 0 if there was none yet.
	LatestHandshakeUnix int64  `protobuf:"varint,3,opt,name=latest_handshake_unix,json=latestHandshakeUnix,proto3" json:"latest_handshake_unix,omitempty"`
	ReceivedBytes       uint64 `protobuf:"varint,4,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	SentBytes           uint64 `protobuf:"varint,5,opt,name=sent_bytes,json=sentBytes,proto3" json:"sent_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OverlayPeerStatus) Reset() {
	*x = OverlayPeerStatus{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverlayPeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverlayPeerStatus) ProtoMessage() {}

func (x *OverlayPeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverlayPeerStatus.ProtoReflect.Descriptor instead.
func (*OverlayPeerStatus) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{2}
}

func (x *OverlayPeerStatus) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *OverlayPeerStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OverlayPeerStatus) GetLatestHandshakeUnix() int64 {
	if x != nil {
		return x.LatestHandshakeUnix
	}
	return 0
}

func (x *OverlayPeerStatus) GetReceivedBytes() uint64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *OverlayPeerStatus) GetSentBytes() uint64 {
	if x != nil {
		return x.SentBytes
	}
	return 0
}

type ConfigureOverlayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's address with the prefix of the network, e.g. 10.213.0.3/24. The network is a
	// private IPv4 range that overlaps no address or route of the node.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The UDP port at which WireGuard listens.
	Port          uint32         `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Mtu           uint32         `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Peers         []*OverlayPeer `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureOverlayRequest) Reset() {
	*x = ConfigureOverlayRequest{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureOverlayRequest) ProtoMessage() {}

func (x *ConfigureOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureOverlayRequest.ProtoReflect.Descriptor instead.
func (*ConfigureOverlayRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureOverlayRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConfigureOverlayRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConfigureOverlayRequest) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ConfigureOverlayRequest) GetPeers() []*OverlayPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type OverlayPeer struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PublicKey string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Its address in the network, e.g. 10.213.0.4, the only one it may send from.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// host:port at which it is reached; the agent resolves host names.
	Endpoint      string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverlayPeer) Reset() {
	*x = OverlayPeer{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverlayPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverlayPeer) ProtoMessage() {}

func (x *OverlayPeer) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverlayPeer.ProtoReflect.Descriptor instead.
func (*OverlayPeer) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{4}
}

func (x *OverlayPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *OverlayPeer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OverlayPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type ConfigureOverlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureOverlayResponse) Reset() {
	*x = ConfigureOverlayResponse{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureOverlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureOverlayResponse) ProtoMessage() {}

func (x *ConfigureOverlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureOverlayResponse.ProtoReflect.Descriptor instead.
func (*ConfigureOverlayResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{5}
}

type RotateOverlayKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateOverlayKeyRequest) Reset() {
	*x = RotateOverlayKeyRequest{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateOverlayKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateOverlayKeyRequest) ProtoMessage() {}

func (x *RotateOverlayKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateOverlayKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateOverlayKeyRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{6}
}

type RotateOverlayKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateOverlayKeyResponse) Reset() {
	*x = RotateOverlayKeyResponse{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateOverlayKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateOverlayKeyResponse) ProtoMessage() {}

func (x *RotateOverlayKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateOverlayKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateOverlayKeyResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{7}
}

func (x *RotateOverlayKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type LeaveOverlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveOverlayRequest) Reset() {
	*x = LeaveOverlayRequest{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveOverlayRequest) ProtoMessage() {}

func (x *LeaveOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveOverlayRequest.ProtoReflect.Descriptor instead.
func (*LeaveOverlayRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{8}
}

type LeaveOverlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveOverlayResponse) Reset() {
	*x = LeaveOverlayResponse{}
	mi := &file_noryx_v1_overlay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveOverlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveOverlayResponse) ProtoMessage() {}

func (x *LeaveOverlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_overlay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveOverlayResponse.ProtoReflect.Descriptor instead.
func (*LeaveOverlayResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_overlay_proto_rawDescGZIP(), []int{9}
}

var File_noryx_v1_overlay_proto protoreflect.FileDescriptor

const file_noryx_v1_overlay_proto_rawDesc = "" +
	"\n" +
	"\x16noryx/v1/overlay.proto\x12\bnoryx.v1\"\x13\n" +
	"\x11GetOverlayRequest\"\xbc\x01\n" +
	"\x12GetOverlayResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12 \n" +
	"\vunsupported\x18\x02 \x01(\tR\vunsupported\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x121\n" +
	"\x05peers\x18\x05 \x03(\v2\x1b.noryx.v1.OverlayPeerStatusR\x05peers\"\xc8\x01\n" +
	"\x11OverlayPeerStatus\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x122\n" +
	"\x15latest_handshake_unix\x18\x03 \x01(\x03R\x13latestHandshakeUnix\x12%\n" +
	"\x0ereceived_bytes\x18\x04 \x01(\x04R\rreceivedBytes\x12\x1d\n" +
	"\n" +
	"sent_bytes\x18\x05 \x01(\x04R\tsentBytes\"\x86\x01\n" +
	"\x17ConfigureOverlayRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x10\n" +
	"\x03mtu\x18\x03 \x01(\rR\x03mtu\x12+\n" +
	"\x05peers\x18\x04 \x03(\v2\x15.noryx.v1.OverlayPeerR\x05peers\"b\n" +
	"\vOverlayPeer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"\x1a\n" +
	"\x18ConfigureOverlayResponse\"\x19\n" +
	"\x17RotateOverlayKeyRequest\"9\n" +
	"\x18RotateOverlayKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"\x15\n" +
	"\x13LeaveOverlayRequest\"\x16\n" +
	"\x14LeaveOverlayResponse2\xde\x02\n" +
	"\x0eOverlayService\x12G\n" +
	"\n" +
	"GetOverlay\x12\x1b.noryx.v1.GetOverlayRequest\x1a\x1c.noryx.v1.GetOverlayResponse\x12Y\n" +
	"\x10ConfigureOverlay\x12!.noryx.v1.ConfigureOverlayRequest\x1a\".noryx.v1.ConfigureOverlayResponse\x12Y\n" +
	"\x10RotateOverlayKey\x12!.noryx.v1.RotateOverlayKeyRequest\x1a\".noryx.v1.RotateOverlayKeyResponse\x12M\n" +
	"\fLeaveOverlay\x12\x1d.noryx.v1.LeaveOverlayRequest\x1a\x1e.noryx.v1.LeaveOverlayResponseB0Z.github.com/QwikByte/noryx/api/noryx/v1;noryxv1b\x06proto3"

var (
	file_noryx_v1_overlay_proto_rawDescOnce sync.Once
	file_noryx_v1_overlay_proto_rawDescData []byte
)

func file_noryx_v1_overlay_proto_rawDescGZIP() []byte {
	file_noryx_v1_overlay_proto_rawDescOnce.Do(func() {
		file_noryx_v1_overlay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noryx_v1_overlay_proto_rawDesc), len(file_noryx_v1_overlay_proto_rawDesc)))
	})
	return file_noryx_v1_overlay_proto_rawDescData
}

var file_noryx_v1_overlay_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_noryx_v1_overlay_proto_goTypes = []any{
	(*GetOverlayRequest)(nil),        // 0: noryx.v1.GetOverlayRequest
	(*GetOverlayResponse)(nil),       // 1: noryx.v1.GetOverlayResponse
	(*OverlayPeerStatus)(nil),        // 2: noryx.v1.OverlayPeerStatus
	(*ConfigureOverlayRequest)(nil),  // 3: noryx.v1.ConfigureOverlayRequest
	(*OverlayPeer)(nil),              // 4: noryx.v1.OverlayPeer
	(*ConfigureOverlayResponse)(nil), // 5: noryx.v1.ConfigureOverlayResponse
	(*RotateOverlayKeyRequest)(nil),  // 6: noryx.v1.RotateOverlayKeyRequest
	(*RotateOverlayKeyResponse)(nil), // 7: noryx.v1.RotateOverlayKeyResponse
	(*LeaveOverlayRequest)(nil),      // 8: noryx.v1.LeaveOverlayRequest
	(*LeaveOverlayResponse)(nil),     // 9: noryx.v1.LeaveOverlayResponse
}
var file_noryx_v1_overlay_proto_depIdxs = []int32{
	2, // 0: noryx.v1.GetOverlayResponse.peers:type_name -> noryx.v1.OverlayPeerStatus
	4, // 1: noryx.v1.ConfigureOverlayRequest.peers:type_name -> noryx.v1.OverlayPeer
	0, // 2: noryx.v1.OverlayService.GetOverlay:input_type -> noryx.v1.GetOverlayRequest
	3, // 3: noryx.v1.OverlayService.ConfigureOverlay:input_type -> noryx.v1.ConfigureOverlayRequest
	6, // 4: noryx.v1.OverlayService.RotateOverlayKey:input_type -> noryx.v1.RotateOverlayKeyRequest
	8, // 5: noryx.v1.OverlayService.LeaveOverlay:input_type -> noryx.v1.LeaveOverlayRequest
	1, // 6: noryx.v1.OverlayService.GetOverlay:output_type -> noryx.v1.GetOverlayResponse
	5, // 7: noryx.v1.OverlayService.ConfigureOverlay:output_type -> noryx.v1.ConfigureOverlayResponse
	7, // 8: noryx.v1.OverlayService.RotateOverlayKey:output_type -> noryx.v1.RotateOverlayKeyResponse
	9, // 9: noryx.v1.OverlayService.LeaveOverlay:output_type -> noryx.v1.LeaveOverlayResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_noryx_v1_overlay_proto_init() }
func file_noryx_v1_overlay_proto_init() {
	if File_noryx_v1_overlay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noryx_v1_overlay_proto_rawDesc), len(file_noryx_v1_overlay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noryx_v1_overlay_proto_goTypes,
		DependencyIndexes: file_noryx_v1_overlay_proto_depIdxs,
		MessageInfos:      file_noryx_v1_overlay_proto_msgTypes,
	}.Build()
	File_noryx_v1_overlay_proto = out.File
	file_noryx_v1_overlay_proto_goTypes = nil
	file_noryx_v1_overlay_proto_depIdxs = nil
}
