// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: noryx/v1/overlay.proto

package noryxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OverlayService_GetOverlay_FullMethodName       = "/noryx.v1.OverlayService/GetOverlay"
	OverlayService_ConfigureOverlay_FullMethodName = "/noryx.v1.OverlayService/ConfigureOverlay"
	OverlayService_RotateOverlayKey_FullMethodName = "/noryx.v1.OverlayService/RotateOverlayKey"
	OverlayService_LeaveOverlay_FullMethodName     = "/noryx.v1.OverlayService/LeaveOverlay"
	OverlayService_TestOverlayPeer_FullMethodName  = "/noryx.v1.OverlayService/TestOverlayPeer"
)

// OverlayServiceClient is the client API for OverlayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OverlayService is served by every agent and joins its node to the private network of the
// nodes: a WireGuard interface over which proxies reach the backends of other nodes. Only
// nodes whose administrator allowed it, with noryx-agent overlay allow, join.
type OverlayServiceClient interface {
	// GetOverlay tells whether the node may and can join, and returns its public key, which it
	// creates the first time, and the state of its interface and peers.
	GetOverlay(ctx context.Context, in *GetOverlayRequest, opts ...grpc.CallOption) (*GetOverlayResponse, error)
	// ConfigureOverlay sets the node's address, port, MTU and peers. Applying the same again
	// keeps the sessions with the peers.
	ConfigureOverlay(ctx context.Context, in *ConfigureOverlayRequest, opts ...grpc.CallOption) (*ConfigureOverlayResponse, error)
	// RotateOverlayKey replaces the node's key and returns the new public key. Until the peers
	// have it, they don't reach the node.
	RotateOverlayKey(ctx context.Context, in *RotateOverlayKeyRequest, opts ...grpc.CallOption) (*RotateOverlayKeyResponse, error)
	// LeaveOverlay removes the interface and its firewall rules. The key stays.
	LeaveOverlay(ctx context.Context, in *LeaveOverlayRequest, opts ...grpc.CallOption) (*LeaveOverlayResponse, error)
	// TestOverlayPeer opens TCP connections through the interface to a peer's address in the
	// network, at ports that the peer publishes for this node, and closes them at once without
	// sending anything. The agent connects only to the address that its configuration gives
	// the peer, and only to the ports that its configuration says the peer publishes for it.
	TestOverlayPeer(ctx context.Context, in *TestOverlayPeerRequest, opts ...grpc.CallOption) (*TestOverlayPeerResponse, error)
}

type overlayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOverlayServiceClient(cc grpc.ClientConnInterface) OverlayServiceClient {
	return &overlayServiceClient{cc}
}

func (c *overlayServiceClient) GetOverlay(ctx context.Context, in *GetOverlayRequest, opts ...grpc.CallOption) (*GetOverlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOverlayResponse)
	err := c.cc.Invoke(ctx, OverlayService_GetOverlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayServiceClient) ConfigureOverlay(ctx context.Context, in *ConfigureOverlayRequest, opts ...grpc.CallOption) (*ConfigureOverlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureOverlayResponse)
	err := c.cc.Invoke(ctx, OverlayService_ConfigureOverlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayServiceClient) RotateOverlayKey(ctx context.Context, in *RotateOverlayKeyRequest, opts ...grpc.CallOption) (*RotateOverlayKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateOverlayKeyResponse)
	err := c.cc.Invoke(ctx, OverlayService_RotateOverlayKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayServiceClient) LeaveOverlay(ctx context.Context, in *LeaveOverlayRequest, opts ...grpc.CallOption) (*LeaveOverlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveOverlayResponse)
	err := c.cc.Invoke(ctx, OverlayService_LeaveOverlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayServiceClient) TestOverlayPeer(ctx context.Context, in *TestOverlayPeerRequest, opts ...grpc.CallOption) (*TestOverlayPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestOverlayPeerResponse)
	err := c.cc.Invoke(ctx, OverlayService_TestOverlayPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OverlayServiceServer is the server API for OverlayService service.
// All implementations must embed UnimplementedOverlayServiceServer
// for forward compatibility.
//
// OverlayService is served by every agent and joins its node to the private network of the
// nodes: a WireGuard interface over which proxies reach the backends of other nodes. Only
// nodes whose administrator allowed it, with noryx-agent overlay allow, join.
type OverlayServiceServer interface {
	// GetOverlay tells whether the node may and can join, and returns its public key, which it
	// creates the first time, and the state of its interface and peers.
	GetOverlay(context.Context, *GetOverlayRequest) (*GetOverlayResponse, error)
	// ConfigureOverlay sets the node's address, port, MTU and peers. Applying the same again
	// keeps the sessions with the peers.
	ConfigureOverlay(context.Context, *ConfigureOverlayRequest) (*ConfigureOverlayResponse, error)
	// RotateOverlayKey replaces the node's key and returns the new public key. Until the peers
	// have it, they don't reach the node.
	RotateOverlayKey(context.Context, *RotateOverlayKeyRequest) (*RotateOverlayKeyResponse, error)
	// LeaveOverlay removes the interface and its firewall rules. The key stays.
	LeaveOverlay(context.Context, *LeaveOverlayRequest) (*LeaveOverlayResponse, error)
	// TestOverlayPeer opens TCP connections through the interface to a peer's address in the
	// network, at ports that the peer publishes for this node, and closes them at once without
	// sending anything. The agent connects only to the address that its configuration gives
	// the peer, and only to the ports that its configuration says the peer publishes for it.
	TestOverlayPeer(context.Context, *TestOverlayPeerRequest) (*TestOverlayPeerResponse, error)
	mustEmbedUnimplementedOverlayServiceServer()
}

// UnimplementedOverlayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOverlayServiceServer struct{}

func (UnimplementedOverlayServiceServer) GetOverlay(context.Context, *GetOverlayRequest) (*GetOverlayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverlay not implemented")
}
func (UnimplementedOverlayServiceServer) ConfigureOverlay(context.Context, *ConfigureOverlayRequest) (*ConfigureOverlayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureOverlay not implemented")
}
func (UnimplementedOverlayServiceServer) RotateOverlayKey(context.Context, *RotateOverlayKeyRequest) (*RotateOverlayKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateOverlayKey not implemented")
}
func (UnimplementedOverlayServiceServer) LeaveOverlay(context.Context, *LeaveOverlayRequest) (*LeaveOverlayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveOverlay not implemented")
}
func (UnimplementedOverlayServiceServer) TestOverlayPeer(context.Context, *TestOverlayPeerRequest) (*TestOverlayPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestOverlayPeer not implemented")
}
func (UnimplementedOverlayServiceServer) mustEmbedUnimplementedOverlayServiceServer() {}
func (UnimplementedOverlayServiceServer) testEmbeddedByValue()                        {}

// UnsafeOverlayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OverlayServiceServer will
// result in compilation errors.
type UnsafeOverlayServiceServer interface {
	mustEmbedUnimplementedOverlayServiceServer()
}

func RegisterOverlayServiceServer(s grpc.ServiceRegistrar, srv OverlayServiceServer) {
	// If the following call panics, it indicates UnimplementedOverlayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OverlayService_ServiceDesc, srv)
}

func _OverlayService_GetOverlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServiceServer).GetOverlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverlayService_GetOverlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServiceServer).GetOverlay(ctx, req.(*GetOverlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverlayService_ConfigureOverlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureOverlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServiceServer).ConfigureOverlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverlayService_ConfigureOverlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServiceServer).ConfigureOverlay(ctx, req.(*ConfigureOverlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverlayService_RotateOverlayKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateOverlayKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServiceServer).RotateOverlayKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverlayService_RotateOverlayKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServiceServer).RotateOverlayKey(ctx, req.(*RotateOverlayKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverlayService_LeaveOverlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveOverlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServiceServer).LeaveOverlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverlayService_LeaveOverlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServiceServer).LeaveOverlay(ctx, req.(*LeaveOverlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverlayService_TestOverlayPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestOverlayPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServiceServer).TestOverlayPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverlayService_TestOverlayPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServiceServer).TestOverlayPeer(ctx, req.(*TestOverlayPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OverlayService_ServiceDesc is the grpc.ServiceDesc for OverlayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OverlayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noryx.v1.OverlayService",
	HandlerType: (*OverlayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOverlay",
			Handler:    _OverlayService_GetOverlay_Handler,
		},
		{
			MethodName: "ConfigureOverlay",
			Handler:    _OverlayService_ConfigureOverlay_Handler,
		},
		{
			MethodName: "RotateOverlayKey",
			Handler:    _OverlayService_RotateOverlayKey_Handler,
		},
		{
			MethodName: "LeaveOverlay",
			Handler:    _OverlayService_LeaveOverlay_Handler,
		},
		{
			MethodName: "TestOverlayPeer",
			Handler:    _OverlayService_TestOverlayPeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noryx/v1/overlay.proto",
}
