// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: noryx/v1/player.proto

package noryxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerAction int32

const (
	PlayerAction_PLAYER_ACTION_UNSPECIFIED      PlayerAction = 0
	PlayerAction_PLAYER_ACTION_KICK             PlayerAction = 1
	PlayerAction_PLAYER_ACTION_BAN              PlayerAction = 2
	PlayerAction_PLAYER_ACTION_PARDON           PlayerAction = 3
	PlayerAction_PLAYER_ACTION_WHITELIST_ADD    PlayerAction = 4
	PlayerAction_PLAYER_ACTION_WHITELIST_REMOVE PlayerAction = 5
	PlayerAction_PLAYER_ACTION_OP               PlayerAction = 6
	PlayerAction_PLAYER_ACTION_DEOP             PlayerAction = 7
	// Turning the whitelist on or off takes no player.
	PlayerAction_PLAYER_ACTION_WHITELIST_ON  PlayerAction = 8
	PlayerAction_PLAYER_ACTION_WHITELIST_OFF PlayerAction = 9
)

// Enum value maps for PlayerAction.
var (
	PlayerAction_name = map[int32]string{
		0: "PLAYER_ACTION_UNSPECIFIED",
		1: "PLAYER_ACTION_KICK",
		2: "PLAYER_ACTION_BAN",
		3: "PLAYER_ACTION_PARDON",
		4: "PLAYER_ACTION_WHITELIST_ADD",
		5: "PLAYER_ACTION_WHITELIST_REMOVE",
		6: "PLAYER_ACTION_OP",
		7: "PLAYER_ACTION_DEOP",
		8: "PLAYER_ACTION_WHITELIST_ON",
		9: "PLAYER_ACTION_WHITELIST_OFF",
	}
	PlayerAction_value = map[string]int32{
		"PLAYER_ACTION_UNSPECIFIED":      0,
		"PLAYER_ACTION_KICK":             1,
		"PLAYER_ACTION_BAN":              2,
		"PLAYER_ACTION_PARDON":           3,
		"PLAYER_ACTION_WHITELIST_ADD":    4,
		"PLAYER_ACTION_WHITELIST_REMOVE": 5,
		"PLAYER_ACTION_OP":               6,
		"PLAYER_ACTION_DEOP":             7,
		"PLAYER_ACTION_WHITELIST_ON":     8,
		"PLAYER_ACTION_WHITELIST_OFF":    9,
	}
)

func (x PlayerAction) Enum() *PlayerAction {
	p := new(PlayerAction)
	*p = x
	return p
}

func (x PlayerAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerAction) Descriptor() protoreflect.EnumDescriptor {
	return file_noryx_v1_player_proto_enumTypes[0].Descriptor()
}

func (PlayerAction) Type() protoreflect.EnumType {
	return &file_noryx_v1_player_proto_enumTypes[0]
}

func (x PlayerAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerAction.Descriptor instead.
func (PlayerAction) EnumDescriptor() ([]byte, []int) {
	return file_noryx_v1_player_proto_rawDescGZIP(), []int{0}
}

type GetPlayerListsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerListsRequest) Reset() {
	*x = GetPlayerListsRequest{}
	mi := &file_noryx_v1_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerListsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerListsRequest) ProtoMessage() {}

func (x *GetPlayerListsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerListsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerListsRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_player_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayerListsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetPlayerListsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Banned           []*ListedPlayer        `protobuf:"bytes,1,rep,name=banned,proto3" json:"banned,omitempty"`
	Whitelisted      []*ListedPlayer        `protobuf:"bytes,2,rep,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	Operators        []*ListedPlayer        `protobuf:"bytes,3,rep,name=operators,proto3" json:"operators,omitempty"`
	WhitelistEnabled bool                   `protobuf:"varint,4,opt,name=whitelist_enabled,json=whitelistEnabled,proto3" json:"whitelist_enabled,omitempty"`
	// Changes that wait for the server to run, in their order.
	Pending       []*PlayerChange `protobuf:"bytes,5,rep,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerListsResponse) Reset() {
	*x = GetPlayerListsResponse{}
	mi := &file_noryx_v1_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerListsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerListsResponse) ProtoMessage() {}

func (x *GetPlayerListsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerListsResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerListsResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_player_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerListsResponse) GetBanned() []*ListedPlayer {
	if x != nil {
		return x.Banned
	}
	return nil
}

func (x *GetPlayerListsResponse) GetWhitelisted() []*ListedPlayer {
	if x != nil {
		return x.Whitelisted
	}
	return nil
}

func (x *GetPlayerListsResponse) GetOperators() []*ListedPlayer {
	if x != nil {
		return x.Operators
	}
	return nil
}

func (x *GetPlayerListsResponse) GetWhitelistEnabled() bool {
	if x != nil {
		return x.WhitelistEnabled
	}
	return false
}

func (x *GetPlayerListsResponse) GetPending() []*PlayerChange {
	if x != nil {
		return x.Pending
	}
	return nil
}

type ListedPlayer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid  string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Why, since when and by whom a player is banned; empty in the other lists.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedUnix   int64  `protobuf:"varint,4,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	Source        string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListedPlayer) Reset() {
	*x = ListedPlayer{}
	mi := &file_noryx_v1_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListedPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListedPlayer) ProtoMessage() {}

func (x *ListedPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListedPlayer.ProtoReflect.Descriptor instead.
func (*ListedPlayer) Descriptor() ([]byte, []int) {
	return file_noryx_v1_player_proto_rawDescGZIP(), []int{2}
}

func (x *ListedPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListedPlayer) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ListedPlayer) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ListedPlayer) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *ListedPlayer) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type PlayerChange struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Action PlayerAction           `protobuf:"varint,1,opt,name=action,proto3,enum=noryx.v1.PlayerAction" json:"action,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Shown to a player who is kicked or banned.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerChange) Reset() {
	*x = PlayerChange{}
	mi := &file_noryx_v1_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerChange) ProtoMessage() {}

func (x *PlayerChange) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerChange.ProtoReflect.Descriptor instead.
func (*PlayerChange) Descriptor() ([]byte, []int) {
	return file_noryx_v1_player_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerChange) GetAction() PlayerAction {
	if x != nil {
		return x.Action
	}
	return PlayerAction_PLAYER_ACTION_UNSPECIFIED
}

func (x *PlayerChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ChangePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Change        *PlayerChange          `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePlayerRequest) Reset() {
	*x = ChangePlayerRequest{}
	mi := &file_noryx_v1_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePlayerRequest) ProtoMessage() {}

func (x *ChangePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePlayerRequest.ProtoReflect.Descriptor instead.
func (*ChangePlayerRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_player_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePlayerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ChangePlayerRequest) GetChange() *PlayerChange {
	if x != nil {
		return x.Change
	}
	return nil
}

type ChangePlayerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server doesn't run and runs the command once it does.
	Pending bool `protobuf:"varint,1,opt,name=pending,proto3" json:"pending,omitempty"`
	// What the server answered, without formatting.
	Output        string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePlayerResponse) Reset() {
	*x = ChangePlayerResponse{}
	mi := &file_noryx_v1_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePlayerResponse) ProtoMessage() {}

func (x *ChangePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePlayerResponse.ProtoReflect.Descriptor instead.
func (*ChangePlayerResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_player_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePlayerResponse) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *ChangePlayerResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_noryx_v1_player_proto protoreflect.FileDescriptor

const file_noryx_v1_player_proto_rawDesc = "" +
	"\n" +
	"\x15noryx/v1/player.proto\x12\bnoryx.v1\"4\n" +
	"\x15GetPlayerListsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\x97\x02\n" +
	"\x16GetPlayerListsResponse\x12.\n" +
	"\x06banned\x18\x01 \x03(\v2\x16.noryx.v1.ListedPlayerR\x06banned\x128\n" +
	"\vwhitelisted\x18\x02 \x03(\v2\x16.noryx.v1.ListedPlayerR\vwhitelisted\x124\n" +
	"\toperators\x18\x03 \x03(\v2\x16.noryx.v1.ListedPlayerR\toperators\x12+\n" +
	"\x11whitelist_enabled\x18\x04 \x01(\bR\x10whitelistEnabled\x120\n" +
	"\apending\x18\x05 \x03(\v2\x16.noryx.v1.PlayerChangeR\apending\"\x89\x01\n" +
	"\fListedPlayer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\fcreated_unix\x18\x04 \x01(\x03R\vcreatedUnix\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"j\n" +
	"\fPlayerChange\x12.\n" +
	"\x06action\x18\x01 \x01(\x0e2\x16.noryx.v1.PlayerActionR\x06action\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"b\n" +
	"\x13ChangePlayerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12.\n" +
	"\x06change\x18\x02 \x01(\v2\x16.noryx.v1.PlayerChangeR\x06change\"H\n" +
	"\x14ChangePlayerResponse\x12\x18\n" +
	"\apending\x18\x01 \x01(\bR\apending\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output*\xaa\x02\n" +
	"\fPlayerAction\x12\x1d\n" +
	"\x19PLAYER_ACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PLAYER_ACTION_KICK\x10\x01\x12\x15\n" +
	"\x11PLAYER_ACTION_BAN\x10\x02\x12\x18\n" +
	"\x14PLAYER_ACTION_PARDON\x10\x03\x12\x1f\n" +
	"\x1bPLAYER_ACTION_WHITELIST_ADD\x10\x04\x12\"\n" +
	"\x1ePLAYER_ACTION_WHITELIST_REMOVE\x10\x05\x12\x14\n" +
	"\x10PLAYER_ACTION_OP\x10\x06\x12\x16\n" +
	"\x12PLAYER_ACTION_DEOP\x10\a\x12\x1e\n" +
	"\x1aPLAYER_ACTION_WHITELIST_ON\x10\b\x12\x1f\n" +
	"\x1bPLAYER_ACTION_WHITELIST_OFF\x10\t2\xb3\x01\n" +
	"\rPlayerService\x12S\n" +
	"\x0eGetPlayerLists\x12\x1f.noryx.v1.GetPlayerListsRequest\x1a .noryx.v1.GetPlayerListsResponse\x12M\n" +
	"\fChangePlayer\x12\x1d.noryx.v1.ChangePlayerRequest\x1a\x1e.noryx.v1.ChangePlayerResponseB0Z.github.com/QwikByte/noryx/api/noryx/v1;noryxv1b\x06proto3"

var (
	file_noryx_v1_player_proto_rawDescOnce sync.Once
	file_noryx_v1_player_proto_rawDescData []byte
)

func file_noryx_v1_player_proto_rawDescGZIP() []byte {
	file_noryx_v1_player_proto_rawDescOnce.Do(func() {
		file_noryx_v1_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noryx_v1_player_proto_rawDesc), len(file_noryx_v1_player_proto_rawDesc)))
	})
	return file_noryx_v1_player_proto_rawDescData
}

var file_noryx_v1_player_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_noryx_v1_player_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_noryx_v1_player_proto_goTypes = []any{
	(PlayerAction)(0),              // 0: noryx.v1.PlayerAction
	(*GetPlayerListsRequest)(nil),  // 1: noryx.v1.GetPlayerListsRequest
	(*GetPlayerListsResponse)(nil), // 2: noryx.v1.GetPlayerListsResponse
	(*ListedPlayer)(nil),           // 3: noryx.v1.ListedPlayer
	(*PlayerChange)(nil),           // 4: noryx.v1.PlayerChange
	(*ChangePlayerRequest)(nil),    // 5: noryx.v1.ChangePlayerRequest
	(*ChangePlayerResponse)(nil),   // 6: noryx.v1.ChangePlayerResponse
}
var file_noryx_v1_player_proto_depIdxs = []int32{
	3, // 0: noryx.v1.GetPlayerListsResponse.banned:type_name -> noryx.v1.ListedPlayer
	3, // 1: noryx.v1.GetPlayerListsResponse.whitelisted:type_name -> noryx.v1.ListedPlayer
	3, // 2: noryx.v1.GetPlayerListsResponse.operators:type_name -> noryx.v1.ListedPlayer
	4, // 3: noryx.v1.GetPlayerListsResponse.pending:type_name -> noryx.v1.PlayerChange
	0, // 4: noryx.v1.PlayerChange.action:type_name -> noryx.v1.PlayerAction
	4, // 5: noryx.v1.ChangePlayerRequest.change:type_name -> noryx.v1.PlayerChange
	1, // 6: noryx.v1.PlayerService.GetPlayerLists:input_type -> noryx.v1.GetPlayerListsRequest
	5, // 7: noryx.v1.PlayerService.ChangePlayer:input_type -> noryx.v1.ChangePlayerRequest
	2, // 8: noryx.v1.PlayerService.GetPlayerLists:output_type -> noryx.v1.GetPlayerListsResponse
	6, // 9: noryx.v1.PlayerService.ChangePlayer:output_type -> noryx.v1.ChangePlayerResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_noryx_v1_player_proto_init() }
func file_noryx_v1_player_proto_init() {
	if File_noryx_v1_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noryx_v1_player_proto_rawDesc), len(file_noryx_v1_player_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noryx_v1_player_proto_goTypes,
		DependencyIndexes: file_noryx_v1_player_proto_depIdxs,
		EnumInfos:         file_noryx_v1_player_proto_enumTypes,
		MessageInfos:      file_noryx_v1_player_proto_msgTypes,
	}.Build()
	File_noryx_v1_player_proto = out.File
	file_noryx_v1_player_proto_goTypes = nil
	file_noryx_v1_player_proto_depIdxs = nil
}
