// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: noryx/v1/plugin.proto

package noryxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the .jar file in the plugin folder.
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size     int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Hex-encoded SHA-512 of the file, which identifies it on Modrinth.
	Sha512 string `protobuf:"bytes,3,opt,name=sha512,proto3" json:"sha512,omitempty"`
	// Hex-encoded SHA-256 of the file, which identifies it on Hangar.
	Sha256 string `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// The file is turned off: it is in the folder of turned-off plugins.
	Disabled bool `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Folder of the plugin's settings in the plugin folder, e.g. LuckPerms, if it has one:
	// the name it gives itself in its plugin.yml, paper-plugin.yml, bungee.yml or
	// velocity-plugin.json. See ValidPluginFolder.
	Settings      string `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginFile) Reset() {
	*x = PluginFile{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginFile) ProtoMessage() {}

func (x *PluginFile) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginFile.ProtoReflect.Descriptor instead.
func (*PluginFile) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PluginFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PluginFile) GetSha512() string {
	if x != nil {
		return x.Sha512
	}
	return ""
}

func (x *PluginFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *PluginFile) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *PluginFile) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

type ListPluginsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Lists the turned-off files too, which older masters don't know.
	IncludeDisabled bool `protobuf:"varint,2,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ListPluginsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListPluginsRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type ListPluginsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "plugins" or "mods", relative to the server's data directory.
	Folder        string        `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Plugins       []*PluginFile `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ListPluginsResponse) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *ListPluginsResponse) GetPlugins() []*PluginFile {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type InstallPluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*InstallPluginRequest_Header
	//	*InstallPluginRequest_Data
	Content       isInstallPluginRequest_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginRequest) Reset() {
	*x = InstallPluginRequest{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginRequest) ProtoMessage() {}

func (x *InstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginRequest.ProtoReflect.Descriptor instead.
func (*InstallPluginRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *InstallPluginRequest) GetContent() isInstallPluginRequest_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InstallPluginRequest) GetHeader() *InstallPluginHeader {
	if x != nil {
		if x, ok := x.Content.(*InstallPluginRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *InstallPluginRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Content.(*InstallPluginRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isInstallPluginRequest_Content interface {
	isInstallPluginRequest_Content()
}

type InstallPluginRequest_Header struct {
	Header *InstallPluginHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type InstallPluginRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*InstallPluginRequest_Header) isInstallPluginRequest_Content() {}

func (*InstallPluginRequest_Data) isInstallPluginRequest_Content() {}

type InstallPluginHeader struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	FileName string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// File of another version of the plugin, which is removed once the new one is written.
	Replaces string `protobuf:"bytes,3,opt,name=replaces,proto3" json:"replaces,omitempty"`
	// Writes the file into the folder of turned-off plugins, where replaces is too.
	Disabled      bool `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginHeader) Reset() {
	*x = InstallPluginHeader{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginHeader) ProtoMessage() {}

func (x *InstallPluginHeader) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginHeader.ProtoReflect.Descriptor instead.
func (*InstallPluginHeader) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *InstallPluginHeader) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *InstallPluginHeader) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *InstallPluginHeader) GetReplaces() string {
	if x != nil {
		return x.Replaces
	}
	return ""
}

func (x *InstallPluginHeader) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type InstallPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        *PluginFile            `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginResponse) Reset() {
	*x = InstallPluginResponse{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginResponse) ProtoMessage() {}

func (x *InstallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginResponse.ProtoReflect.Descriptor instead.
func (*InstallPluginResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *InstallPluginResponse) GetPlugin() *PluginFile {
	if x != nil {
		return x.Plugin
	}
	return nil
}

type RemovePluginRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	FileName string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// Removes a turned-off file.
	Disabled      bool `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePluginRequest) Reset() {
	*x = RemovePluginRequest{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePluginRequest) ProtoMessage() {}

func (x *RemovePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePluginRequest.ProtoReflect.Descriptor instead.
func (*RemovePluginRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *RemovePluginRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RemovePluginRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *RemovePluginRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type RemovePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePluginResponse) Reset() {
	*x = RemovePluginResponse{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePluginResponse) ProtoMessage() {}

func (x *RemovePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePluginResponse.ProtoReflect.Descriptor instead.
func (*RemovePluginResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{7}
}

type EnablePluginRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	FileName string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// Turns the file on; otherwise off.
	Enabled       bool `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePluginRequest) Reset() {
	*x = EnablePluginRequest{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePluginRequest) ProtoMessage() {}

func (x *EnablePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePluginRequest.ProtoReflect.Descriptor instead.
func (*EnablePluginRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *EnablePluginRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *EnablePluginRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *EnablePluginRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type EnablePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePluginResponse) Reset() {
	*x = EnablePluginResponse{}
	mi := &file_noryx_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePluginResponse) ProtoMessage() {}

func (x *EnablePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePluginResponse.ProtoReflect.Descriptor instead.
func (*EnablePluginResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_plugin_proto_rawDescGZIP(), []int{9}
}

var File_noryx_v1_plugin_proto protoreflect.FileDescriptor

const file_noryx_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x15noryx/v1/plugin.proto\x12\bnoryx.v1\"\xa5\x01\n" +
	"\n" +
	"PluginFile\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha512\x18\x03 \x01(\tR\x06sha512\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x1a\n" +
	"\bdisabled\x18\x05 \x01(\bR\bdisabled\x12\x1a\n" +
	"\bsettings\x18\x06 \x01(\tR\bsettings\"\\\n" +
	"\x12ListPluginsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12)\n" +
	"\x10include_disabled\x18\x02 \x01(\bR\x0fincludeDisabled\"]\n" +
	"\x13ListPluginsResponse\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12.\n" +
	"\aplugins\x18\x02 \x03(\v2\x14.noryx.v1.PluginFileR\aplugins\"p\n" +
	"\x14InstallPluginRequest\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1d.noryx.v1.InstallPluginHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\acontent\"\x87\x01\n" +
	"\x13InstallPluginHeader\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\breplaces\x18\x03 \x01(\tR\breplaces\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\"E\n" +
	"\x15InstallPluginResponse\x12,\n" +
	"\x06plugin\x18\x01 \x01(\v2\x14.noryx.v1.PluginFileR\x06plugin\"k\n" +
	"\x13RemovePluginRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\"\x16\n" +
	"\x14RemovePluginResponse\"i\n" +
	"\x13EnablePluginRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"\x16\n" +
	"\x14EnablePluginResponse2\xcd\x02\n" +
	"\rPluginService\x12J\n" +
	"\vListPlugins\x12\x1c.noryx.v1.ListPluginsRequest\x1a\x1d.noryx.v1.ListPluginsResponse\x12R\n" +
	"\rInstallPlugin\x12\x1e.noryx.v1.InstallPluginRequest\x1a\x1f.noryx.v1.InstallPluginResponse(\x01\x12M\n" +
	"\fRemovePlugin\x12\x1d.noryx.v1.RemovePluginRequest\x1a\x1e.noryx.v1.RemovePluginResponse\x12M\n" +
	"\fEnablePlugin\x12\x1d.noryx.v1.EnablePluginRequest\x1a\x1e.noryx.v1.EnablePluginResponseB0Z.github.com/QwikByte/noryx/api/noryx/v1;noryxv1b\x06proto3"

var (
	file_noryx_v1_plugin_proto_rawDescOnce sync.Once
	file_noryx_v1_plugin_proto_rawDescData []byte
)

func file_noryx_v1_plugin_proto_rawDescGZIP() []byte {
	file_noryx_v1_plugin_proto_rawDescOnce.Do(func() {
		file_noryx_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noryx_v1_plugin_proto_rawDesc), len(file_noryx_v1_plugin_proto_rawDesc)))
	})
	return file_noryx_v1_plugin_proto_rawDescData
}

var file_noryx_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_noryx_v1_plugin_proto_goTypes = []any{
	(*PluginFile)(nil),            // 0: noryx.v1.PluginFile
	(*ListPluginsRequest)(nil),    // 1: noryx.v1.ListPluginsRequest
	(*ListPluginsResponse)(nil),   // 2: noryx.v1.ListPluginsResponse
	(*InstallPluginRequest)(nil),  // 3: noryx.v1.InstallPluginRequest
	(*InstallPluginHeader)(nil),   // 4: noryx.v1.InstallPluginHeader
	(*InstallPluginResponse)(nil), // 5: noryx.v1.InstallPluginResponse
	(*RemovePluginRequest)(nil),   // 6: noryx.v1.RemovePluginRequest
	(*RemovePluginResponse)(nil),  // 7: noryx.v1.RemovePluginResponse
	(*EnablePluginRequest)(nil),   // 8: noryx.v1.EnablePluginRequest
	(*EnablePluginResponse)(nil),  // 9: noryx.v1.EnablePluginResponse
}
var file_noryx_v1_plugin_proto_depIdxs = []int32{
	0, // 0: noryx.v1.ListPluginsResponse.plugins:type_name -> noryx.v1.PluginFile
	4, // 1: noryx.v1.InstallPluginRequest.header:type_name -> noryx.v1.InstallPluginHeader
	0, // 2: noryx.v1.InstallPluginResponse.plugin:type_name -> noryx.v1.PluginFile
	1, // 3: noryx.v1.PluginService.ListPlugins:input_type -> noryx.v1.ListPluginsRequest
	3, // 4: noryx.v1.PluginService.InstallPlugin:input_type -> noryx.v1.InstallPluginRequest
	6, // 5: noryx.v1.PluginService.RemovePlugin:input_type -> noryx.v1.RemovePluginRequest
	8, // 6: noryx.v1.PluginService.EnablePlugin:input_type -> noryx.v1.EnablePluginRequest
	2, // 7: noryx.v1.PluginService.ListPlugins:output_type -> noryx.v1.ListPluginsResponse
	5, // 8: noryx.v1.PluginService.InstallPlugin:output_type -> noryx.v1.InstallPluginResponse
	7, // 9: noryx.v1.PluginService.RemovePlugin:output_type -> noryx.v1.RemovePluginResponse
	9, // 10: noryx.v1.PluginService.EnablePlugin:output_type -> noryx.v1.EnablePluginResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_noryx_v1_plugin_proto_init() }
func file_noryx_v1_plugin_proto_init() {
	if File_noryx_v1_plugin_proto != nil {
		return
	}
	file_noryx_v1_plugin_proto_msgTypes[3].OneofWrappers = []any{
		(*InstallPluginRequest_Header)(nil),
		(*InstallPluginRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noryx_v1_plugin_proto_rawDesc), len(file_noryx_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noryx_v1_plugin_proto_goTypes,
		DependencyIndexes: file_noryx_v1_plugin_proto_depIdxs,
		MessageInfos:      file_noryx_v1_plugin_proto_msgTypes,
	}.Build()
	File_noryx_v1_plugin_proto = out.File
	file_noryx_v1_plugin_proto_goTypes = nil
	file_noryx_v1_plugin_proto_depIdxs = nil
}
