// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: noryx/v1/plugin.proto

package noryxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_ListPlugins_FullMethodName   = "/noryx.v1.PluginService/ListPlugins"
	PluginService_InstallPlugin_FullMethodName = "/noryx.v1.PluginService/InstallPlugin"
	PluginService_RemovePlugin_FullMethodName  = "/noryx.v1.PluginService/RemovePlugin"
	PluginService_EnablePlugin_FullMethodName  = "/noryx.v1.PluginService/EnablePlugin"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService is served by every agent and manages the plugins of a server, or the
// mods of a modded one. The agent chooses the folder by the server type: plugins/ for
// Paper, Purpur and proxies, mods/ for Fabric, Forge and NeoForge. Vanilla servers
// load neither. Servers load plugins when they start. Turned-off plugins are kept in the
// folder .disabled of the plugin folder, which no server loads.
type PluginServiceClient interface {
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	// InstallPlugin writes a plugin file. The first message names it, the others carry
	// its content. A file with the same name is replaced once the new one is complete.
	InstallPlugin(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InstallPluginRequest, InstallPluginResponse], error)
	RemovePlugin(ctx context.Context, in *RemovePluginRequest, opts ...grpc.CallOption) (*RemovePluginResponse, error)
	// EnablePlugin turns a plugin file off, by moving it into the folder of turned-off
	// plugins, or on again. A file of the same name where it goes is never replaced.
	EnablePlugin(ctx context.Context, in *EnablePluginRequest, opts ...grpc.CallOption) (*EnablePluginResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, PluginService_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) InstallPlugin(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InstallPluginRequest, InstallPluginResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginService_ServiceDesc.Streams[0], PluginService_InstallPlugin_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstallPluginRequest, InstallPluginResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginService_InstallPluginClient = grpc.ClientStreamingClient[InstallPluginRequest, InstallPluginResponse]

func (c *pluginServiceClient) RemovePlugin(ctx context.Context, in *RemovePluginRequest, opts ...grpc.CallOption) (*RemovePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePluginResponse)
	err := c.cc.Invoke(ctx, PluginService_RemovePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) EnablePlugin(ctx context.Context, in *EnablePluginRequest, opts ...grpc.CallOption) (*EnablePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnablePluginResponse)
	err := c.cc.Invoke(ctx, PluginService_EnablePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService is served by every agent and manages the plugins of a server, or the
// mods of a modded one. The agent chooses the folder by the server type: plugins/ for
// Paper, Purpur and proxies, mods/ for Fabric, Forge and NeoForge. Vanilla servers
// load neither. Servers load plugins when they start. Turned-off plugins are kept in the
// folder .disabled of the plugin folder, which no server loads.
type PluginServiceServer interface {
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	// InstallPlugin writes a plugin file. The first message names it, the others carry
	// its content. A file with the same name is replaced once the new one is complete.
	InstallPlugin(grpc.ClientStreamingServer[InstallPluginRequest, InstallPluginResponse]) error
	RemovePlugin(context.Context, *RemovePluginRequest) (*RemovePluginResponse, error)
	// EnablePlugin turns a plugin file off, by moving it into the folder of turned-off
	// plugins, or on again. A file of the same name where it goes is never replaced.
	EnablePlugin(context.Context, *EnablePluginRequest) (*EnablePluginResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedPluginServiceServer) InstallPlugin(grpc.ClientStreamingServer[InstallPluginRequest, InstallPluginResponse]) error {
	return status.Error(codes.Unimplemented, "method InstallPlugin not implemented")
}
func (UnimplementedPluginServiceServer) RemovePlugin(context.Context, *RemovePluginRequest) (*RemovePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePlugin not implemented")
}
func (UnimplementedPluginServiceServer) EnablePlugin(context.Context, *EnablePluginRequest) (*EnablePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnablePlugin not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_InstallPlugin_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginServiceServer).InstallPlugin(&grpc.GenericServerStream[InstallPluginRequest, InstallPluginResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginService_InstallPluginServer = grpc.ClientStreamingServer[InstallPluginRequest, InstallPluginResponse]

func _PluginService_RemovePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).RemovePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_RemovePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).RemovePlugin(ctx, req.(*RemovePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_EnablePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnablePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).EnablePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_EnablePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).EnablePlugin(ctx, req.(*EnablePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noryx.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlugins",
			Handler:    _PluginService_ListPlugins_Handler,
		},
		{
			MethodName: "RemovePlugin",
			Handler:    _PluginService_RemovePlugin_Handler,
		},
		{
			MethodName: "EnablePlugin",
			Handler:    _PluginService_EnablePlugin_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InstallPlugin",
			Handler:       _PluginService_InstallPlugin_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "noryx/v1/plugin.proto",
}
