// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: noryx/v1/progress.proto

package noryxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProgressService_WatchProgress_FullMethodName = "/noryx.v1.ProgressService/WatchProgress"
)

// ProgressServiceClient is the client API for ProgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProgressService tells how long calls of the agent are getting on, e.g. one that downloads
// a server image. The master names such a call with the metadata key noryx-operation and
// watches it under that name; calls without it report nothing.
type ProgressServiceClient interface {
	// WatchProgress sends the progress of the named call whenever it changes, until the call
	// ends. It may start before the call does.
	WatchProgress(ctx context.Context, in *WatchProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchProgressResponse], error)
}

type progressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgressServiceClient(cc grpc.ClientConnInterface) ProgressServiceClient {
	return &progressServiceClient{cc}
}

func (c *progressServiceClient) WatchProgress(ctx context.Context, in *WatchProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchProgressResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProgressService_ServiceDesc.Streams[0], ProgressService_WatchProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchProgressRequest, WatchProgressResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProgressService_WatchProgressClient = grpc.ServerStreamingClient[WatchProgressResponse]

// ProgressServiceServer is the server API for ProgressService service.
// All implementations must embed UnimplementedProgressServiceServer
// for forward compatibility.
//
// ProgressService tells how long calls of the agent are getting on, e.g. one that downloads
// a server image. The master names such a call with the metadata key noryx-operation and
// watches it under that name; calls without it report nothing.
type ProgressServiceServer interface {
	// WatchProgress sends the progress of the named call whenever it changes, until the call
	// ends. It may start before the call does.
	WatchProgress(*WatchProgressRequest, grpc.ServerStreamingServer[WatchProgressResponse]) error
	mustEmbedUnimplementedProgressServiceServer()
}

// UnimplementedProgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgressServiceServer struct{}

func (UnimplementedProgressServiceServer) WatchProgress(*WatchProgressRequest, grpc.ServerStreamingServer[WatchProgressResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchProgress not implemented")
}
func (UnimplementedProgressServiceServer) mustEmbedUnimplementedProgressServiceServer() {}
func (UnimplementedProgressServiceServer) testEmbeddedByValue()                         {}

// UnsafeProgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgressServiceServer will
// result in compilation errors.
type UnsafeProgressServiceServer interface {
	mustEmbedUnimplementedProgressServiceServer()
}

func RegisterProgressServiceServer(s grpc.ServiceRegistrar, srv ProgressServiceServer) {
	// If the following call panics, it indicates UnimplementedProgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgressService_ServiceDesc, srv)
}

func _ProgressService_WatchProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProgressServiceServer).WatchProgress(m, &grpc.GenericServerStream[WatchProgressRequest, WatchProgressResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProgressService_WatchProgressServer = grpc.ServerStreamingServer[WatchProgressResponse]

// ProgressService_ServiceDesc is the grpc.ServiceDesc for ProgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noryx.v1.ProgressService",
	HandlerType: (*ProgressServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchProgress",
			Handler:       _ProgressService_WatchProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "noryx/v1/progress.proto",
}
