// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: noryx/v1/progress.proto

package noryxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProgressRequest) Reset() {
	*x = WatchProgressRequest{}
	mi := &file_noryx_v1_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProgressRequest) ProtoMessage() {}

func (x *WatchProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProgressRequest.ProtoReflect.Descriptor instead.
func (*WatchProgressRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_progress_proto_rawDescGZIP(), []int{0}
}

func (x *WatchProgressRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type WatchProgressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The step the call is at: image (downloading the server image), container (creating
	// it), save (a running server writes its worlds), copy (copying data), archive (packing
	// a backup), restore (unpacking one), stop or start.
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// Bytes of the step done so far, and in all; total is 0 if unknown.
	Done          int64 `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Total         int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProgressResponse) Reset() {
	*x = WatchProgressResponse{}
	mi := &file_noryx_v1_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProgressResponse) ProtoMessage() {}

func (x *WatchProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProgressResponse.ProtoReflect.Descriptor instead.
func (*WatchProgressResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_progress_proto_rawDescGZIP(), []int{1}
}

func (x *WatchProgressResponse) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *WatchProgressResponse) GetDone() int64 {
	if x != nil {
		return x.Done
	}
	return 0
}

func (x *WatchProgressResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_noryx_v1_progress_proto protoreflect.FileDescriptor

const file_noryx_v1_progress_proto_rawDesc = "" +
	"\n" +
	"\x17noryx/v1/progress.proto\x12\bnoryx.v1\"9\n" +
	"\x14WatchProgressRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"U\n" +
	"\x15WatchProgressResponse\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x12\n" +
	"\x04done\x18\x02 \x01(\x03R\x04done\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total2e\n" +
	"\x0fProgressService\x12R\n" +
	"\rWatchProgress\x12\x1e.noryx.v1.WatchProgressRequest\x1a\x1f.noryx.v1.WatchProgressResponse0\x01B0Z.github.com/QwikByte/noryx/api/noryx/v1;noryxv1b\x06proto3"

var (
	file_noryx_v1_progress_proto_rawDescOnce sync.Once
	file_noryx_v1_progress_proto_rawDescData []byte
)

func file_noryx_v1_progress_proto_rawDescGZIP() []byte {
	file_noryx_v1_progress_proto_rawDescOnce.Do(func() {
		file_noryx_v1_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noryx_v1_progress_proto_rawDesc), len(file_noryx_v1_progress_proto_rawDesc)))
	})
	return file_noryx_v1_progress_proto_rawDescData
}

var file_noryx_v1_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_noryx_v1_progress_proto_goTypes = []any{
	(*WatchProgressRequest)(nil),  // 0: noryx.v1.WatchProgressRequest
	(*WatchProgressResponse)(nil), // 1: noryx.v1.WatchProgressResponse
}
var file_noryx_v1_progress_proto_depIdxs = []int32{
	0, // 0: noryx.v1.ProgressService.WatchProgress:input_type -> noryx.v1.WatchProgressRequest
	1, // 1: noryx.v1.ProgressService.WatchProgress:output_type -> noryx.v1.WatchProgressResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_noryx_v1_progress_proto_init() }
func file_noryx_v1_progress_proto_init() {
	if File_noryx_v1_progress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noryx_v1_progress_proto_rawDesc), len(file_noryx_v1_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noryx_v1_progress_proto_goTypes,
		DependencyIndexes: file_noryx_v1_progress_proto_depIdxs,
		MessageInfos:      file_noryx_v1_progress_proto_msgTypes,
	}.Build()
	File_noryx_v1_progress_proto = out.File
	file_noryx_v1_progress_proto_goTypes = nil
	file_noryx_v1_progress_proto_depIdxs = nil
}
