// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: noryx/v1/properties.proto

package noryxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServerPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerPropertiesRequest) Reset() {
	*x = GetServerPropertiesRequest{}
	mi := &file_noryx_v1_properties_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerPropertiesRequest) ProtoMessage() {}

func (x *GetServerPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_properties_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerPropertiesRequest.ProtoReflect.Descriptor instead.
func (*GetServerPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_properties_proto_rawDescGZIP(), []int{0}
}

func (x *GetServerPropertiesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetServerPropertiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False until the server started once and created the file.
	Exists     bool              `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Properties map[string]string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Properties the manager sets itself, which can't be changed. Secret values are left
	// out of properties.
	Locked        []*LockedProperty `protobuf:"bytes,3,rep,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerPropertiesResponse) Reset() {
	*x = GetServerPropertiesResponse{}
	mi := &file_noryx_v1_properties_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerPropertiesResponse) ProtoMessage() {}

func (x *GetServerPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_properties_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerPropertiesResponse.ProtoReflect.Descriptor instead.
func (*GetServerPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_properties_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerPropertiesResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetServerPropertiesResponse) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GetServerPropertiesResponse) GetLocked() []*LockedProperty {
	if x != nil {
		return x.Locked
	}
	return nil
}

type LockedProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockedProperty) Reset() {
	*x = LockedProperty{}
	mi := &file_noryx_v1_properties_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockedProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockedProperty) ProtoMessage() {}

func (x *LockedProperty) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_properties_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockedProperty.ProtoReflect.Descriptor instead.
func (*LockedProperty) Descriptor() ([]byte, []int) {
	return file_noryx_v1_properties_proto_rawDescGZIP(), []int{2}
}

func (x *LockedProperty) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LockedProperty) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateServerPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerPropertiesRequest) Reset() {
	*x = UpdateServerPropertiesRequest{}
	mi := &file_noryx_v1_properties_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerPropertiesRequest) ProtoMessage() {}

func (x *UpdateServerPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_properties_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerPropertiesRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_noryx_v1_properties_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateServerPropertiesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateServerPropertiesRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UpdateServerPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerPropertiesResponse) Reset() {
	*x = UpdateServerPropertiesResponse{}
	mi := &file_noryx_v1_properties_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerPropertiesResponse) ProtoMessage() {}

func (x *UpdateServerPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noryx_v1_properties_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerPropertiesResponse.ProtoReflect.Descriptor instead.
func (*UpdateServerPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_noryx_v1_properties_proto_rawDescGZIP(), []int{4}
}

var File_noryx_v1_properties_proto protoreflect.FileDescriptor

const file_noryx_v1_properties_proto_rawDesc = "" +
	"\n" +
	"\x19noryx/v1/properties.proto\x12\bnoryx.v1\"9\n" +
	"\x1aGetServerPropertiesRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\xfd\x01\n" +
	"\x1bGetServerPropertiesResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12U\n" +
	"\n" +
	"properties\x18\x02 \x03(\v25.noryx.v1.GetServerPropertiesResponse.PropertiesEntryR\n" +
	"properties\x120\n" +
	"\x06locked\x18\x03 \x03(\v2\x18.noryx.v1.LockedPropertyR\x06locked\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x0eLockedProperty\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xd4\x01\n" +
	"\x1dUpdateServerPropertiesRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12W\n" +
	"\n" +
	"properties\x18\x02 \x03(\v27.noryx.v1.UpdateServerPropertiesRequest.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x1eUpdateServerPropertiesResponse2\xe4\x01\n" +
	"\x11PropertiesService\x12b\n" +
	"\x13GetServerProperties\x12$.noryx.v1.GetServerPropertiesRequest\x1a%.noryx.v1.GetServerPropertiesResponse\x12k\n" +
	"\x16UpdateServerProperties\x12'.noryx.v1.UpdateServerPropertiesRequest\x1a(.noryx.v1.UpdateServerPropertiesResponseB<Z:github.com/QwikByte/mc-server-manager/api/noryx/v1;noryxv1b\x06proto3"

var (
	file_noryx_v1_properties_proto_rawDescOnce sync.Once
	file_noryx_v1_properties_proto_rawDescData []byte
)

func file_noryx_v1_properties_proto_rawDescGZIP() []byte {
	file_noryx_v1_properties_proto_rawDescOnce.Do(func() {
		file_noryx_v1_properties_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noryx_v1_properties_proto_rawDesc), len(file_noryx_v1_properties_proto_rawDesc)))
	})
	return file_noryx_v1_properties_proto_rawDescData
}

var file_noryx_v1_properties_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_noryx_v1_properties_proto_goTypes = []any{
	(*GetServerPropertiesRequest)(nil),     // 0: noryx.v1.GetServerPropertiesRequest
	(*GetServerPropertiesResponse)(nil),    // 1: noryx.v1.GetServerPropertiesResponse
	(*LockedProperty)(nil),                 // 2: noryx.v1.LockedProperty
	(*UpdateServerPropertiesRequest)(nil),  // 3: noryx.v1.UpdateServerPropertiesRequest
	(*UpdateServerPropertiesResponse)(nil), // 4: noryx.v1.UpdateServerPropertiesResponse
	nil,                                    // 5: noryx.v1.GetServerPropertiesResponse.PropertiesEntry
	nil,                                    // 6: noryx.v1.UpdateServerPropertiesRequest.PropertiesEntry
}
var file_noryx_v1_properties_proto_depIdxs = []int32{
	5, // 0: noryx.v1.GetServerPropertiesResponse.properties:type_name -> noryx.v1.GetServerPropertiesResponse.PropertiesEntry
	2, // 1: noryx.v1.GetServerPropertiesResponse.locked:type_name -> noryx.v1.LockedProperty
	6, // 2: noryx.v1.UpdateServerPropertiesRequest.properties:type_name -> noryx.v1.UpdateServerPropertiesRequest.PropertiesEntry
	0, // 3: noryx.v1.PropertiesService.GetServerProperties:input_type -> noryx.v1.GetServerPropertiesRequest
	3, // 4: noryx.v1.PropertiesService.UpdateServerProperties:input_type -> noryx.v1.UpdateServerPropertiesRequest
	1, // 5: noryx.v1.PropertiesService.GetServerProperties:output_type -> noryx.v1.GetServerPropertiesResponse
	4, // 6: noryx.v1.PropertiesService.UpdateServerProperties:output_type -> noryx.v1.UpdateServerPropertiesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_noryx_v1_properties_proto_init() }
func file_noryx_v1_properties_proto_init() {
	if File_noryx_v1_properties_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noryx_v1_properties_proto_rawDesc), len(file_noryx_v1_properties_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noryx_v1_properties_proto_goTypes,
		DependencyIndexes: file_noryx_v1_properties_proto_depIdxs,
		MessageInfos:      file_noryx_v1_properties_proto_msgTypes,
	}.Build()
	File_noryx_v1_properties_proto = out.File
	file_noryx_v1_properties_proto_goTypes = nil
	file_noryx_v1_properties_proto_depIdxs = nil
}
