// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcsm/v1/file.proto

package mcsmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directory     bool                   `protobuf:"varint,2,opt,name=directory,proto3" json:"directory,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedUnix  int64                  `protobuf:"varint,4,opt,name=modified_unix,json=modifiedUnix,proto3" json:"modified_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_mcsm_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetDirectory() bool {
	if x != nil {
		return x.Directory
	}
	return false
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModifiedUnix() int64 {
	if x != nil {
		return x.ModifiedUnix
	}
	return 0
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_mcsm_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directories first, then files, each sorted by name.
	Files []*FileInfo `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	// Set if the directory has more entries than the agent lists.
	Truncated     bool `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_mcsm_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_mcsm_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_mcsm_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*WriteFileRequest_Header
	//	*WriteFileRequest_Data
	Content       isWriteFileRequest_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_mcsm_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{5}
}

func (x *WriteFileRequest) GetContent() isWriteFileRequest_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetHeader() *WriteFileHeader {
	if x != nil {
		if x, ok := x.Content.(*WriteFileRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Content.(*WriteFileRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isWriteFileRequest_Content interface {
	isWriteFileRequest_Content()
}

type WriteFileRequest_Header struct {
	Header *WriteFileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type WriteFileRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*WriteFileRequest_Header) isWriteFileRequest_Content() {}

func (*WriteFileRequest_Data) isWriteFileRequest_Content() {}

type WriteFileHeader struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Path     string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Replace an existing file; otherwise writing to an existing file fails.
	Overwrite     bool `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileHeader) Reset() {
	*x = WriteFileHeader{}
	mi := &file_mcsm_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileHeader) ProtoMessage() {}

func (x *WriteFileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileHeader.ProtoReflect.Descriptor instead.
func (*WriteFileHeader) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFileHeader) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *WriteFileHeader) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileHeader) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_mcsm_v1_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFileResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type ArchiveDirectoryRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Path     string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Leaves out the files that only hold secrets, such as the RCON password, and replaces
	// the secrets in others, as for the panel's users. Moves need all of it.
	HideSecrets   bool `protobuf:"varint,3,opt,name=hide_secrets,json=hideSecrets,proto3" json:"hide_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveDirectoryRequest) Reset() {
	*x = ArchiveDirectoryRequest{}
	mi := &file_mcsm_v1_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveDirectoryRequest) ProtoMessage() {}

func (x *ArchiveDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ArchiveDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{8}
}

func (x *ArchiveDirectoryRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ArchiveDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ArchiveDirectoryRequest) GetHideSecrets() bool {
	if x != nil {
		return x.HideSecrets
	}
	return false
}

type ArchiveDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveDirectoryResponse) Reset() {
	*x = ArchiveDirectoryResponse{}
	mi := &file_mcsm_v1_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveDirectoryResponse) ProtoMessage() {}

func (x *ArchiveDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ArchiveDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{9}
}

func (x *ArchiveDirectoryResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryRequest) Reset() {
	*x = CreateDirectoryRequest{}
	mi := &file_mcsm_v1_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryRequest) ProtoMessage() {}

func (x *CreateDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDirectoryRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryResponse) Reset() {
	*x = CreateDirectoryResponse{}
	mi := &file_mcsm_v1_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryResponse) ProtoMessage() {}

func (x *CreateDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{11}
}

type MoveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFileRequest) Reset() {
	*x = MoveFileRequest{}
	mi := &file_mcsm_v1_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileRequest) ProtoMessage() {}

func (x *MoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileRequest.ProtoReflect.Descriptor instead.
func (*MoveFileRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{12}
}

func (x *MoveFileRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MoveFileRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MoveFileRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type MoveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFileResponse) Reset() {
	*x = MoveFileResponse{}
	mi := &file_mcsm_v1_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileResponse) ProtoMessage() {}

func (x *MoveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileResponse.ProtoReflect.Descriptor instead.
func (*MoveFileResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{13}
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_mcsm_v1_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFileRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_mcsm_v1_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_file_proto_rawDescGZIP(), []int{15}
}

var File_mcsm_v1_file_proto protoreflect.FileDescriptor

const file_mcsm_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x12mcsm/v1/file.proto\x12\amcsm.v1\"u\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdirectory\x18\x02 \x01(\bR\tdirectory\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12#\n" +
	"\rmodified_unix\x18\x04 \x01(\x03R\fmodifiedUnix\"C\n" +
	"\x10ListFilesRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"Z\n" +
	"\x11ListFilesResponse\x12'\n" +
	"\x05files\x18\x01 \x03(\v2\x11.mcsm.v1.FileInfoR\x05files\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"B\n" +
	"\x0fReadFileRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\":\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"g\n" +
	"\x10WriteFileRequest\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x18.mcsm.v1.WriteFileHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\acontent\"`\n" +
	"\x0fWriteFileHeader\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\":\n" +
	"\x11WriteFileResponse\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.mcsm.v1.FileInfoR\x04file\"m\n" +
	"\x17ArchiveDirectoryRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\fhide_secrets\x18\x03 \x01(\bR\vhideSecrets\".\n" +
	"\x18ArchiveDirectoryResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"I\n" +
	"\x16CreateDirectoryRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x19\n" +
	"\x17CreateDirectoryResponse\"R\n" +
	"\x0fMoveFileRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"\x12\n" +
	"\x10MoveFileResponse\"D\n" +
	"\x11DeleteFileRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x14\n" +
	"\x12DeleteFileResponse2\x93\x04\n" +
	"\vFileService\x12B\n" +
	"\tListFiles\x12\x19.mcsm.v1.ListFilesRequest\x1a\x1a.mcsm.v1.ListFilesResponse\x12A\n" +
	"\bReadFile\x12\x18.mcsm.v1.ReadFileRequest\x1a\x19.mcsm.v1.ReadFileResponse0\x01\x12D\n" +
	"\tWriteFile\x12\x19.mcsm.v1.WriteFileRequest\x1a\x1a.mcsm.v1.WriteFileResponse(\x01\x12Y\n" +
	"\x10ArchiveDirectory\x12 .mcsm.v1.ArchiveDirectoryRequest\x1a!.mcsm.v1.ArchiveDirectoryResponse0\x01\x12T\n" +
	"\x0fCreateDirectory\x12\x1f.mcsm.v1.CreateDirectoryRequest\x1a .mcsm.v1.CreateDirectoryResponse\x12?\n" +
	"\bMoveFile\x12\x18.mcsm.v1.MoveFileRequest\x1a\x19.mcsm.v1.MoveFileResponse\x12E\n" +
	"\n" +
	"DeleteFile\x12\x1a.mcsm.v1.DeleteFileRequest\x1a\x1b.mcsm.v1.DeleteFileResponseB:Z8github.com/QwikByte/mc-server-manager/api/mcsm/v1;mcsmv1b\x06proto3"

var (
	file_mcsm_v1_file_proto_rawDescOnce sync.Once
	file_mcsm_v1_file_proto_rawDescData []byte
)

func file_mcsm_v1_file_proto_rawDescGZIP() []byte {
	file_mcsm_v1_file_proto_rawDescOnce.Do(func() {
		file_mcsm_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsm_v1_file_proto_rawDesc), len(file_mcsm_v1_file_proto_rawDesc)))
	})
	return file_mcsm_v1_file_proto_rawDescData
}

var file_mcsm_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_mcsm_v1_file_proto_goTypes = []any{
	(*FileInfo)(nil),                 // 0: mcsm.v1.FileInfo
	(*ListFilesRequest)(nil),         // 1: mcsm.v1.ListFilesRequest
	(*ListFilesResponse)(nil),        // 2: mcsm.v1.ListFilesResponse
	(*ReadFileRequest)(nil),          // 3: mcsm.v1.ReadFileRequest
	(*ReadFileResponse)(nil),         // 4: mcsm.v1.ReadFileResponse
	(*WriteFileRequest)(nil),         // 5: mcsm.v1.WriteFileRequest
	(*WriteFileHeader)(nil),          // 6: mcsm.v1.WriteFileHeader
	(*WriteFileResponse)(nil),        // 7: mcsm.v1.WriteFileResponse
	(*ArchiveDirectoryRequest)(nil),  // 8: mcsm.v1.ArchiveDirectoryRequest
	(*ArchiveDirectoryResponse)(nil), // 9: mcsm.v1.ArchiveDirectoryResponse
	(*CreateDirectoryRequest)(nil),   // 10: mcsm.v1.CreateDirectoryRequest
	(*CreateDirectoryResponse)(nil),  // 11: mcsm.v1.CreateDirectoryResponse
	(*MoveFileRequest)(nil),          // 12: mcsm.v1.MoveFileRequest
	(*MoveFileResponse)(nil),         // 13: mcsm.v1.MoveFileResponse
	(*DeleteFileRequest)(nil),        // 14: mcsm.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),       // 15: mcsm.v1.DeleteFileResponse
}
var file_mcsm_v1_file_proto_depIdxs = []int32{
	0,  // 0: mcsm.v1.ListFilesResponse.files:type_name -> mcsm.v1.FileInfo
	6,  // 1: mcsm.v1.WriteFileRequest.header:type_name -> mcsm.v1.WriteFileHeader
	0,  // 2: mcsm.v1.WriteFileResponse.file:type_name -> mcsm.v1.FileInfo
	1,  // 3: mcsm.v1.FileService.ListFiles:input_type -> mcsm.v1.ListFilesRequest
	3,  // 4: mcsm.v1.FileService.ReadFile:input_type -> mcsm.v1.ReadFileRequest
	5,  // 5: mcsm.v1.FileService.WriteFile:input_type -> mcsm.v1.WriteFileRequest
	8,  // 6: mcsm.v1.FileService.ArchiveDirectory:input_type -> mcsm.v1.ArchiveDirectoryRequest
	10, // 7: mcsm.v1.FileService.CreateDirectory:input_type -> mcsm.v1.CreateDirectoryRequest
	12, // 8: mcsm.v1.FileService.MoveFile:input_type -> mcsm.v1.MoveFileRequest
	14, // 9: mcsm.v1.FileService.DeleteFile:input_type -> mcsm.v1.DeleteFileRequest
	2,  // 10: mcsm.v1.FileService.ListFiles:output_type -> mcsm.v1.ListFilesResponse
	4,  // 11: mcsm.v1.FileService.ReadFile:output_type -> mcsm.v1.ReadFileResponse
	7,  // 12: mcsm.v1.FileService.WriteFile:output_type -> mcsm.v1.WriteFileResponse
	9,  // 13: mcsm.v1.FileService.ArchiveDirectory:output_type -> mcsm.v1.ArchiveDirectoryResponse
	11, // 14: mcsm.v1.FileService.CreateDirectory:output_type -> mcsm.v1.CreateDirectoryResponse
	13, // 15: mcsm.v1.FileService.MoveFile:output_type -> mcsm.v1.MoveFileResponse
	15, // 16: mcsm.v1.FileService.DeleteFile:output_type -> mcsm.v1.DeleteFileResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_mcsm_v1_file_proto_init() }
func file_mcsm_v1_file_proto_init() {
	if File_mcsm_v1_file_proto != nil {
		return
	}
	file_mcsm_v1_file_proto_msgTypes[5].OneofWrappers = []any{
		(*WriteFileRequest_Header)(nil),
		(*WriteFileRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsm_v1_file_proto_rawDesc), len(file_mcsm_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcsm_v1_file_proto_goTypes,
		DependencyIndexes: file_mcsm_v1_file_proto_depIdxs,
		MessageInfos:      file_mcsm_v1_file_proto_msgTypes,
	}.Build()
	File_mcsm_v1_file_proto = out.File
	file_mcsm_v1_file_proto_goTypes = nil
	file_mcsm_v1_file_proto_depIdxs = nil
}
