// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: mcsm/v1/properties.proto

package mcsmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PropertiesService_GetServerProperties_FullMethodName    = "/mcsm.v1.PropertiesService/GetServerProperties"
	PropertiesService_UpdateServerProperties_FullMethodName = "/mcsm.v1.PropertiesService/UpdateServerProperties"
)

// PropertiesServiceClient is the client API for PropertiesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PropertiesService is served by every agent and edits the server.properties of game
// servers. Servers read the file when they start.
type PropertiesServiceClient interface {
	GetServerProperties(ctx context.Context, in *GetServerPropertiesRequest, opts ...grpc.CallOption) (*GetServerPropertiesResponse, error)
	// UpdateServerProperties sets the given properties and keeps the rest of the file,
	// including comments.
	UpdateServerProperties(ctx context.Context, in *UpdateServerPropertiesRequest, opts ...grpc.CallOption) (*UpdateServerPropertiesResponse, error)
}

type propertiesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertiesServiceClient(cc grpc.ClientConnInterface) PropertiesServiceClient {
	return &propertiesServiceClient{cc}
}

func (c *propertiesServiceClient) GetServerProperties(ctx context.Context, in *GetServerPropertiesRequest, opts ...grpc.CallOption) (*GetServerPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerPropertiesResponse)
	err := c.cc.Invoke(ctx, PropertiesService_GetServerProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertiesServiceClient) UpdateServerProperties(ctx context.Context, in *UpdateServerPropertiesRequest, opts ...grpc.CallOption) (*UpdateServerPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServerPropertiesResponse)
	err := c.cc.Invoke(ctx, PropertiesService_UpdateServerProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertiesServiceServer is the server API for PropertiesService service.
// All implementations must embed UnimplementedPropertiesServiceServer
// for forward compatibility.
//
// PropertiesService is served by every agent and edits the server.properties of game
// servers. Servers read the file when they start.
type PropertiesServiceServer interface {
	GetServerProperties(context.Context, *GetServerPropertiesRequest) (*GetServerPropertiesResponse, error)
	// UpdateServerProperties sets the given properties and keeps the rest of the file,
	// including comments.
	UpdateServerProperties(context.Context, *UpdateServerPropertiesRequest) (*UpdateServerPropertiesResponse, error)
	mustEmbedUnimplementedPropertiesServiceServer()
}

// UnimplementedPropertiesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertiesServiceServer struct{}

func (UnimplementedPropertiesServiceServer) GetServerProperties(context.Context, *GetServerPropertiesRequest) (*GetServerPropertiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerProperties not implemented")
}
func (UnimplementedPropertiesServiceServer) UpdateServerProperties(context.Context, *UpdateServerPropertiesRequest) (*UpdateServerPropertiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateServerProperties not implemented")
}
func (UnimplementedPropertiesServiceServer) mustEmbedUnimplementedPropertiesServiceServer() {}
func (UnimplementedPropertiesServiceServer) testEmbeddedByValue()                           {}

// UnsafePropertiesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertiesServiceServer will
// result in compilation errors.
type UnsafePropertiesServiceServer interface {
	mustEmbedUnimplementedPropertiesServiceServer()
}

func RegisterPropertiesServiceServer(s grpc.ServiceRegistrar, srv PropertiesServiceServer) {
	// If the following call panics, it indicates UnimplementedPropertiesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertiesService_ServiceDesc, srv)
}

func _PropertiesService_GetServerProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertiesServiceServer).GetServerProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertiesService_GetServerProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertiesServiceServer).GetServerProperties(ctx, req.(*GetServerPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertiesService_UpdateServerProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertiesServiceServer).UpdateServerProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertiesService_UpdateServerProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertiesServiceServer).UpdateServerProperties(ctx, req.(*UpdateServerPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertiesService_ServiceDesc is the grpc.ServiceDesc for PropertiesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertiesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcsm.v1.PropertiesService",
	HandlerType: (*PropertiesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerProperties",
			Handler:    _PropertiesService_GetServerProperties_Handler,
		},
		{
			MethodName: "UpdateServerProperties",
			Handler:    _PropertiesService_UpdateServerProperties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcsm/v1/properties.proto",
}
