// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcsm/v1/proxy.proto

package mcsmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProxySettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxySettingsRequest) Reset() {
	*x = GetProxySettingsRequest{}
	mi := &file_mcsm_v1_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxySettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxySettingsRequest) ProtoMessage() {}

func (x *GetProxySettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxySettingsRequest.ProtoReflect.Descriptor instead.
func (*GetProxySettingsRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *GetProxySettingsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetProxySettingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False until the proxy started once and created its configuration.
	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	// The configuration file, e.g. velocity.toml.
	File string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	// Settings by their path in the file, e.g. "advanced.compression-threshold" or
	// "listeners.0.motd", as JSON: strings, numbers, booleans and lists of strings.
	Settings map[string]string `protobuf:"bytes,3,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Settings the manager or the network decides, which can't be changed here.
	Locked        []*LockedProperty `protobuf:"bytes,4,rep,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxySettingsResponse) Reset() {
	*x = GetProxySettingsResponse{}
	mi := &file_mcsm_v1_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxySettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxySettingsResponse) ProtoMessage() {}

func (x *GetProxySettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxySettingsResponse.ProtoReflect.Descriptor instead.
func (*GetProxySettingsResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *GetProxySettingsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetProxySettingsResponse) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *GetProxySettingsResponse) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetProxySettingsResponse) GetLocked() []*LockedProperty {
	if x != nil {
		return x.Locked
	}
	return nil
}

type UpdateProxySettingsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// New values by path, as JSON of the same kind as the current value.
	Settings      map[string]string `protobuf:"bytes,2,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxySettingsRequest) Reset() {
	*x = UpdateProxySettingsRequest{}
	mi := &file_mcsm_v1_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxySettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxySettingsRequest) ProtoMessage() {}

func (x *UpdateProxySettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxySettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateProxySettingsRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProxySettingsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateProxySettingsRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateProxySettingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The proxy runs and reloaded its configuration.
	Reloaded      bool `protobuf:"varint,1,opt,name=reloaded,proto3" json:"reloaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxySettingsResponse) Reset() {
	*x = UpdateProxySettingsResponse{}
	mi := &file_mcsm_v1_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxySettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxySettingsResponse) ProtoMessage() {}

func (x *UpdateProxySettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxySettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateProxySettingsResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProxySettingsResponse) GetReloaded() bool {
	if x != nil {
		return x.Reloaded
	}
	return false
}

var File_mcsm_v1_proxy_proto protoreflect.FileDescriptor

const file_mcsm_v1_proxy_proto_rawDesc = "" +
	"\n" +
	"\x13mcsm/v1/proxy.proto\x12\amcsm.v1\x1a\x18mcsm/v1/properties.proto\"6\n" +
	"\x17GetProxySettingsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\x81\x02\n" +
	"\x18GetProxySettingsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12K\n" +
	"\bsettings\x18\x03 \x03(\v2/.mcsm.v1.GetProxySettingsResponse.SettingsEntryR\bsettings\x12/\n" +
	"\x06locked\x18\x04 \x03(\v2\x17.mcsm.v1.LockedPropertyR\x06locked\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x01\n" +
	"\x1aUpdateProxySettingsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12M\n" +
	"\bsettings\x18\x02 \x03(\v21.mcsm.v1.UpdateProxySettingsRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x1bUpdateProxySettingsResponse\x12\x1a\n" +
	"\breloaded\x18\x01 \x01(\bR\breloaded2\xc9\x01\n" +
	"\fProxyService\x12W\n" +
	"\x10GetProxySettings\x12 .mcsm.v1.GetProxySettingsRequest\x1a!.mcsm.v1.GetProxySettingsResponse\x12`\n" +
	"\x13UpdateProxySettings\x12#.mcsm.v1.UpdateProxySettingsRequest\x1a$.mcsm.v1.UpdateProxySettingsResponseB:Z8github.com/QwikByte/mc-server-manager/api/mcsm/v1;mcsmv1b\x06proto3"

var (
	file_mcsm_v1_proxy_proto_rawDescOnce sync.Once
	file_mcsm_v1_proxy_proto_rawDescData []byte
)

func file_mcsm_v1_proxy_proto_rawDescGZIP() []byte {
	file_mcsm_v1_proxy_proto_rawDescOnce.Do(func() {
		file_mcsm_v1_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsm_v1_proxy_proto_rawDesc), len(file_mcsm_v1_proxy_proto_rawDesc)))
	})
	return file_mcsm_v1_proxy_proto_rawDescData
}

var file_mcsm_v1_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mcsm_v1_proxy_proto_goTypes = []any{
	(*GetProxySettingsRequest)(nil),     // 0: mcsm.v1.GetProxySettingsRequest
	(*GetProxySettingsResponse)(nil),    // 1: mcsm.v1.GetProxySettingsResponse
	(*UpdateProxySettingsRequest)(nil),  // 2: mcsm.v1.UpdateProxySettingsRequest
	(*UpdateProxySettingsResponse)(nil), // 3: mcsm.v1.UpdateProxySettingsResponse
	nil,                                 // 4: mcsm.v1.GetProxySettingsResponse.SettingsEntry
	nil,                                 // 5: mcsm.v1.UpdateProxySettingsRequest.SettingsEntry
	(*LockedProperty)(nil),              // 6: mcsm.v1.LockedProperty
}
var file_mcsm_v1_proxy_proto_depIdxs = []int32{
	4, // 0: mcsm.v1.GetProxySettingsResponse.settings:type_name -> mcsm.v1.GetProxySettingsResponse.SettingsEntry
	6, // 1: mcsm.v1.GetProxySettingsResponse.locked:type_name -> mcsm.v1.LockedProperty
	5, // 2: mcsm.v1.UpdateProxySettingsRequest.settings:type_name -> mcsm.v1.UpdateProxySettingsRequest.SettingsEntry
	0, // 3: mcsm.v1.ProxyService.GetProxySettings:input_type -> mcsm.v1.GetProxySettingsRequest
	2, // 4: mcsm.v1.ProxyService.UpdateProxySettings:input_type -> mcsm.v1.UpdateProxySettingsRequest
	1, // 5: mcsm.v1.ProxyService.GetProxySettings:output_type -> mcsm.v1.GetProxySettingsResponse
	3, // 6: mcsm.v1.ProxyService.UpdateProxySettings:output_type -> mcsm.v1.UpdateProxySettingsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mcsm_v1_proxy_proto_init() }
func file_mcsm_v1_proxy_proto_init() {
	if File_mcsm_v1_proxy_proto != nil {
		return
	}
	file_mcsm_v1_properties_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsm_v1_proxy_proto_rawDesc), len(file_mcsm_v1_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcsm_v1_proxy_proto_goTypes,
		DependencyIndexes: file_mcsm_v1_proxy_proto_depIdxs,
		MessageInfos:      file_mcsm_v1_proxy_proto_msgTypes,
	}.Build()
	File_mcsm_v1_proxy_proto = out.File
	file_mcsm_v1_proxy_proto_goTypes = nil
	file_mcsm_v1_proxy_proto_depIdxs = nil
}
