// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcsm/v1/server.proto

package mcsmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerType int32

const (
	ServerType_SERVER_TYPE_UNSPECIFIED ServerType = 0
	ServerType_SERVER_TYPE_VANILLA     ServerType = 1
	ServerType_SERVER_TYPE_PAPER       ServerType = 2
	ServerType_SERVER_TYPE_PURPUR      ServerType = 3
	ServerType_SERVER_TYPE_FABRIC      ServerType = 4
	ServerType_SERVER_TYPE_FORGE       ServerType = 5
	ServerType_SERVER_TYPE_NEOFORGE    ServerType = 6
	// Proxies connect several servers to one network.
	ServerType_SERVER_TYPE_VELOCITY   ServerType = 7
	ServerType_SERVER_TYPE_BUNGEECORD ServerType = 8
)

// Enum value maps for ServerType.
var (
	ServerType_name = map[int32]string{
		0: "SERVER_TYPE_UNSPECIFIED",
		1: "SERVER_TYPE_VANILLA",
		2: "SERVER_TYPE_PAPER",
		3: "SERVER_TYPE_PURPUR",
		4: "SERVER_TYPE_FABRIC",
		5: "SERVER_TYPE_FORGE",
		6: "SERVER_TYPE_NEOFORGE",
		7: "SERVER_TYPE_VELOCITY",
		8: "SERVER_TYPE_BUNGEECORD",
	}
	ServerType_value = map[string]int32{
		"SERVER_TYPE_UNSPECIFIED": 0,
		"SERVER_TYPE_VANILLA":     1,
		"SERVER_TYPE_PAPER":       2,
		"SERVER_TYPE_PURPUR":      3,
		"SERVER_TYPE_FABRIC":      4,
		"SERVER_TYPE_FORGE":       5,
		"SERVER_TYPE_NEOFORGE":    6,
		"SERVER_TYPE_VELOCITY":    7,
		"SERVER_TYPE_BUNGEECORD":  8,
	}
)

func (x ServerType) Enum() *ServerType {
	p := new(ServerType)
	*p = x
	return p
}

func (x ServerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerType) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsm_v1_server_proto_enumTypes[0].Descriptor()
}

func (ServerType) Type() protoreflect.EnumType {
	return &file_mcsm_v1_server_proto_enumTypes[0]
}

func (x ServerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerType.Descriptor instead.
func (ServerType) EnumDescriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{0}
}

// RestartPolicy decides when the node starts a server on its own.
type RestartPolicy int32

const (
	// Same as RESTART_POLICY_ALWAYS.
	RestartPolicy_RESTART_POLICY_UNSPECIFIED RestartPolicy = 0
	// Start with the node and after a crash, unless the server was stopped.
	RestartPolicy_RESTART_POLICY_ALWAYS RestartPolicy = 1
	// Start again after a crash.
	RestartPolicy_RESTART_POLICY_ON_CRASH RestartPolicy = 2
	// Only start when asked to.
	RestartPolicy_RESTART_POLICY_NEVER RestartPolicy = 3
)

// Enum value maps for RestartPolicy.
var (
	RestartPolicy_name = map[int32]string{
		0: "RESTART_POLICY_UNSPECIFIED",
		1: "RESTART_POLICY_ALWAYS",
		2: "RESTART_POLICY_ON_CRASH",
		3: "RESTART_POLICY_NEVER",
	}
	RestartPolicy_value = map[string]int32{
		"RESTART_POLICY_UNSPECIFIED": 0,
		"RESTART_POLICY_ALWAYS":      1,
		"RESTART_POLICY_ON_CRASH":    2,
		"RESTART_POLICY_NEVER":       3,
	}
)

func (x RestartPolicy) Enum() *RestartPolicy {
	p := new(RestartPolicy)
	*p = x
	return p
}

func (x RestartPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsm_v1_server_proto_enumTypes[1].Descriptor()
}

func (RestartPolicy) Type() protoreflect.EnumType {
	return &file_mcsm_v1_server_proto_enumTypes[1]
}

func (x RestartPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartPolicy.Descriptor instead.
func (RestartPolicy) EnumDescriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{1}
}

type ServerState int32

const (
	ServerState_SERVER_STATE_UNSPECIFIED ServerState = 0
	ServerState_SERVER_STATE_STOPPED     ServerState = 1
	ServerState_SERVER_STATE_STARTING    ServerState = 2
	ServerState_SERVER_STATE_RUNNING     ServerState = 3
)

// Enum value maps for ServerState.
var (
	ServerState_name = map[int32]string{
		0: "SERVER_STATE_UNSPECIFIED",
		1: "SERVER_STATE_STOPPED",
		2: "SERVER_STATE_STARTING",
		3: "SERVER_STATE_RUNNING",
	}
	ServerState_value = map[string]int32{
		"SERVER_STATE_UNSPECIFIED": 0,
		"SERVER_STATE_STOPPED":     1,
		"SERVER_STATE_STARTING":    2,
		"SERVER_STATE_RUNNING":     3,
	}
)

func (x ServerState) Enum() *ServerState {
	p := new(ServerState)
	*p = x
	return p
}

func (x ServerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerState) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsm_v1_server_proto_enumTypes[2].Descriptor()
}

func (ServerState) Type() protoreflect.EnumType {
	return &file_mcsm_v1_server_proto_enumTypes[2]
}

func (x ServerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerState.Descriptor instead.
func (ServerState) EnumDescriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{2}
}

type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type  ServerType             `protobuf:"varint,3,opt,name=type,proto3,enum=mcsm.v1.ServerType" json:"type,omitempty"`
	// Minecraft version, e.g. "1.21.4" or "LATEST".
	Version  string      `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	MemoryMb uint32      `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Port     uint32      `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	State    ServerState `protobuf:"varint,7,opt,name=state,proto3,enum=mcsm.v1.ServerState" json:"state,omitempty"`
	// Storage location of the server's data on the node.
	Storage string `protobuf:"bytes,8,opt,name=storage,proto3" json:"storage,omitempty"`
	// Java version of game servers, e.g. "21"; empty for the newest.
	Java          string        `protobuf:"bytes,9,opt,name=java,proto3" json:"java,omitempty"`
	RestartPolicy RestartPolicy `protobuf:"varint,10,opt,name=restart_policy,json=restartPolicy,proto3,enum=mcsm.v1.RestartPolicy" json:"restart_policy,omitempty"`
	// Use the JVM flags recommended by Aikar for Paper and its forks.
	AikarFlags bool `protobuf:"varint,11,opt,name=aikar_flags,json=aikarFlags,proto3" json:"aikar_flags,omitempty"`
	// Additional JVM options, e.g. "-Dfile.encoding=UTF-8".
	JvmOptions []string `protobuf:"bytes,12,rep,name=jvm_options,json=jvmOptions,proto3" json:"jvm_options,omitempty"`
	// CPU limit in thousandths of a core; 0 means no limit.
	CpuMillis     uint32 `protobuf:"varint,13,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_mcsm_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetType() ServerType {
	if x != nil {
		return x.Type
	}
	return ServerType_SERVER_TYPE_UNSPECIFIED
}

func (x *Server) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Server) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *Server) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Server) GetState() ServerState {
	if x != nil {
		return x.State
	}
	return ServerState_SERVER_STATE_UNSPECIFIED
}

func (x *Server) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *Server) GetJava() string {
	if x != nil {
		return x.Java
	}
	return ""
}

func (x *Server) GetRestartPolicy() RestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return RestartPolicy_RESTART_POLICY_UNSPECIFIED
}

func (x *Server) GetAikarFlags() bool {
	if x != nil {
		return x.AikarFlags
	}
	return false
}

func (x *Server) GetJvmOptions() []string {
	if x != nil {
		return x.JvmOptions
	}
	return nil
}

func (x *Server) GetCpuMillis() uint32 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{1}
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *ListServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type CreateServerRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     ServerType             `protobuf:"varint,2,opt,name=type,proto3,enum=mcsm.v1.ServerType" json:"type,omitempty"`
	Version  string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	MemoryMb uint32                 `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Port     uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	// The operator must accept the Minecraft EULA (https://aka.ms/MinecraftEULA).
	AcceptEula bool `protobuf:"varint,6,opt,name=accept_eula,json=acceptEula,proto3" json:"accept_eula,omitempty"`
	// Storage location for the server's data; empty means the default location.
	Storage       string `protobuf:"bytes,7,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *CreateServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServerRequest) GetType() ServerType {
	if x != nil {
		return x.Type
	}
	return ServerType_SERVER_TYPE_UNSPECIFIED
}

func (x *CreateServerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateServerRequest) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateServerRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreateServerRequest) GetAcceptEula() bool {
	if x != nil {
		return x.AcceptEula
	}
	return false
}

func (x *CreateServerRequest) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

type CreateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerResponse) Reset() {
	*x = CreateServerResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResponse) ProtoMessage() {}

func (x *CreateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResponse.ProtoReflect.Descriptor instead.
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *CreateServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type StartServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServerRequest) Reset() {
	*x = StartServerRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerRequest) ProtoMessage() {}

func (x *StartServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServerRequest.ProtoReflect.Descriptor instead.
func (*StartServerRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *StartServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServerResponse) Reset() {
	*x = StartServerResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerResponse) ProtoMessage() {}

func (x *StartServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServerResponse.ProtoReflect.Descriptor instead.
func (*StartServerResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{6}
}

type StopServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServerRequest) Reset() {
	*x = StopServerRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServerRequest) ProtoMessage() {}

func (x *StopServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServerRequest.ProtoReflect.Descriptor instead.
func (*StopServerRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *StopServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServerResponse) Reset() {
	*x = StopServerResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServerResponse) ProtoMessage() {}

func (x *StopServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServerResponse.ProtoReflect.Descriptor instead.
func (*StopServerResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{8}
}

type RestartServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServerRequest) Reset() {
	*x = RestartServerRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServerRequest) ProtoMessage() {}

func (x *RestartServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServerRequest.ProtoReflect.Descriptor instead.
func (*RestartServerRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *RestartServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RestartServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServerResponse) Reset() {
	*x = RestartServerResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServerResponse) ProtoMessage() {}

func (x *RestartServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServerResponse.ProtoReflect.Descriptor instead.
func (*RestartServerResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{10}
}

type UpdateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	MemoryMb      uint32                 `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Java          string                 `protobuf:"bytes,6,opt,name=java,proto3" json:"java,omitempty"`
	RestartPolicy RestartPolicy          `protobuf:"varint,7,opt,name=restart_policy,json=restartPolicy,proto3,enum=mcsm.v1.RestartPolicy" json:"restart_policy,omitempty"`
	AikarFlags    bool                   `protobuf:"varint,8,opt,name=aikar_flags,json=aikarFlags,proto3" json:"aikar_flags,omitempty"`
	JvmOptions    []string               `protobuf:"bytes,9,rep,name=jvm_options,json=jvmOptions,proto3" json:"jvm_options,omitempty"`
	CpuMillis     uint32                 `protobuf:"varint,10,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateServerRequest) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *UpdateServerRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *UpdateServerRequest) GetJava() string {
	if x != nil {
		return x.Java
	}
	return ""
}

func (x *UpdateServerRequest) GetRestartPolicy() RestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return RestartPolicy_RESTART_POLICY_UNSPECIFIED
}

func (x *UpdateServerRequest) GetAikarFlags() bool {
	if x != nil {
		return x.AikarFlags
	}
	return false
}

func (x *UpdateServerRequest) GetJvmOptions() []string {
	if x != nil {
		return x.JvmOptions
	}
	return nil
}

func (x *UpdateServerRequest) GetCpuMillis() uint32 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

type UpdateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerResponse) Reset() {
	*x = UpdateServerResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerResponse) ProtoMessage() {}

func (x *UpdateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerResponse.ProtoReflect.Descriptor instead.
func (*UpdateServerResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerResponse) Reset() {
	*x = DeleteServerResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResponse) ProtoMessage() {}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{14}
}

type StreamLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Number of past lines to send first, at most 1000.
	Tail          uint32 `protobuf:"varint,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{15}
}

func (x *StreamLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamLogsRequest) GetTail() uint32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type StreamLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamLogsResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{16}
}

func (x *StreamLogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type SendCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A single console command, e.g. "say Hello". A leading slash is optional.
	Command       string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{17}
}

func (x *SendCommandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SendCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{18}
}

func (x *SendCommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ConfigureNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Shared secret of Velocity's modern forwarding. Required for proxies.
	ForwardingSecret string `protobuf:"bytes,2,opt,name=forwarding_secret,json=forwardingSecret,proto3" json:"forwarding_secret,omitempty"`
	// Backends of a proxy, in the order players are sent to them.
	Backends      []*NetworkBackend `protobuf:"bytes,3,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureNetworkRequest) Reset() {
	*x = ConfigureNetworkRequest{}
	mi := &file_mcsm_v1_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureNetworkRequest) ProtoMessage() {}

func (x *ConfigureNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureNetworkRequest.ProtoReflect.Descriptor instead.
func (*ConfigureNetworkRequest) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{19}
}

func (x *ConfigureNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigureNetworkRequest) GetForwardingSecret() string {
	if x != nil {
		return x.ForwardingSecret
	}
	return ""
}

func (x *ConfigureNetworkRequest) GetBackends() []*NetworkBackend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type NetworkBackend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name players use, e.g. in /server lobby.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*NetworkBackend_ServerId
	//	*NetworkBackend_Address
	Target        isNetworkBackend_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkBackend) Reset() {
	*x = NetworkBackend{}
	mi := &file_mcsm_v1_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBackend) ProtoMessage() {}

func (x *NetworkBackend) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBackend.ProtoReflect.Descriptor instead.
func (*NetworkBackend) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{20}
}

func (x *NetworkBackend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkBackend) GetTarget() isNetworkBackend_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *NetworkBackend) GetServerId() string {
	if x != nil {
		if x, ok := x.Target.(*NetworkBackend_ServerId); ok {
			return x.ServerId
		}
	}
	return ""
}

func (x *NetworkBackend) GetAddress() string {
	if x != nil {
		if x, ok := x.Target.(*NetworkBackend_Address); ok {
			return x.Address
		}
	}
	return ""
}

type isNetworkBackend_Target interface {
	isNetworkBackend_Target()
}

type NetworkBackend_ServerId struct {
	// A server on the same node as the proxy.
	ServerId string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3,oneof"`
}

type NetworkBackend_Address struct {
	// host:port of a server on another node.
	Address string `protobuf:"bytes,3,opt,name=address,proto3,oneof"`
}

func (*NetworkBackend_ServerId) isNetworkBackend_Target() {}

func (*NetworkBackend_Address) isNetworkBackend_Target() {}

type ConfigureNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureNetworkResponse) Reset() {
	*x = ConfigureNetworkResponse{}
	mi := &file_mcsm_v1_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureNetworkResponse) ProtoMessage() {}

func (x *ConfigureNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsm_v1_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureNetworkResponse.ProtoReflect.Descriptor instead.
func (*ConfigureNetworkResponse) Descriptor() ([]byte, []int) {
	return file_mcsm_v1_server_proto_rawDescGZIP(), []int{21}
}

var File_mcsm_v1_server_proto protoreflect.FileDescriptor

const file_mcsm_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x14mcsm/v1/server.proto\x12\amcsm.v1\"\x9a\x03\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.mcsm.v1.ServerTypeR\x04type\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\rR\bmemoryMb\x12\x12\n" +
	"\x04port\x18\x06 \x01(\rR\x04port\x12*\n" +
	"\x05state\x18\a \x01(\x0e2\x14.mcsm.v1.ServerStateR\x05state\x12\x18\n" +
	"\astorage\x18\b \x01(\tR\astorage\x12\x12\n" +
	"\x04java\x18\t \x01(\tR\x04java\x12=\n" +
	"\x0erestart_policy\x18\n" +
	" \x01(\x0e2\x16.mcsm.v1.RestartPolicyR\rrestartPolicy\x12\x1f\n" +
	"\vaikar_flags\x18\v \x01(\bR\n" +
	"aikarFlags\x12\x1f\n" +
	"\vjvm_options\x18\f \x03(\tR\n" +
	"jvmOptions\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\r \x01(\rR\tcpuMillis\"\x14\n" +
	"\x12ListServersRequest\"@\n" +
	"\x13ListServersResponse\x12)\n" +
	"\aservers\x18\x01 \x03(\v2\x0f.mcsm.v1.ServerR\aservers\"\xd8\x01\n" +
	"\x13CreateServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.mcsm.v1.ServerTypeR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\rR\bmemoryMb\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12\x1f\n" +
	"\vaccept_eula\x18\x06 \x01(\bR\n" +
	"acceptEula\x12\x18\n" +
	"\astorage\x18\a \x01(\tR\astorage\"?\n" +
	"\x14CreateServerResponse\x12'\n" +
	"\x06server\x18\x01 \x01(\v2\x0f.mcsm.v1.ServerR\x06server\"$\n" +
	"\x12StartServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13StartServerResponse\"#\n" +
	"\x11StopServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12StopServerResponse\"&\n" +
	"\x14RestartServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15RestartServerResponse\"\xb8\x02\n" +
	"\x13UpdateServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\rR\bmemoryMb\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12\x12\n" +
	"\x04java\x18\x06 \x01(\tR\x04java\x12=\n" +
	"\x0erestart_policy\x18\a \x01(\x0e2\x16.mcsm.v1.RestartPolicyR\rrestartPolicy\x12\x1f\n" +
	"\vaikar_flags\x18\b \x01(\bR\n" +
	"aikarFlags\x12\x1f\n" +
	"\vjvm_options\x18\t \x03(\tR\n" +
	"jvmOptions\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\n" +
	" \x01(\rR\tcpuMillis\"?\n" +
	"\x14UpdateServerResponse\x12'\n" +
	"\x06server\x18\x01 \x01(\v2\x0f.mcsm.v1.ServerR\x06server\"%\n" +
	"\x13DeleteServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteServerResponse\"7\n" +
	"\x11StreamLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\rR\x04tail\"(\n" +
	"\x12StreamLogsResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\">\n" +
	"\x12SendCommandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"-\n" +
	"\x13SendCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"\x8b\x01\n" +
	"\x17ConfigureNetworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11forwarding_secret\x18\x02 \x01(\tR\x10forwardingSecret\x123\n" +
	"\bbackends\x18\x03 \x03(\v2\x17.mcsm.v1.NetworkBackendR\bbackends\"i\n" +
	"\x0eNetworkBackend\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\tserver_id\x18\x02 \x01(\tH\x00R\bserverId\x12\x1a\n" +
	"\aaddress\x18\x03 \x01(\tH\x00R\aaddressB\b\n" +
	"\x06target\"\x1a\n" +
	"\x18ConfigureNetworkResponse*\xf0\x01\n" +
	"\n" +
	"ServerType\x12\x1b\n" +
	"\x17SERVER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SERVER_TYPE_VANILLA\x10\x01\x12\x15\n" +
	"\x11SERVER_TYPE_PAPER\x10\x02\x12\x16\n" +
	"\x12SERVER_TYPE_PURPUR\x10\x03\x12\x16\n" +
	"\x12SERVER_TYPE_FABRIC\x10\x04\x12\x15\n" +
	"\x11SERVER_TYPE_FORGE\x10\x05\x12\x18\n" +
	"\x14SERVER_TYPE_NEOFORGE\x10\x06\x12\x18\n" +
	"\x14SERVER_TYPE_VELOCITY\x10\a\x12\x1a\n" +
	"\x16SERVER_TYPE_BUNGEECORD\x10\b*\x81\x01\n" +
	"\rRestartPolicy\x12\x1e\n" +
	"\x1aRESTART_POLICY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESTART_POLICY_ALWAYS\x10\x01\x12\x1b\n" +
	"\x17RESTART_POLICY_ON_CRASH\x10\x02\x12\x18\n" +
	"\x14RESTART_POLICY_NEVER\x10\x03*z\n" +
	"\vServerState\x12\x1c\n" +
	"\x18SERVER_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SERVER_STATE_STOPPED\x10\x01\x12\x19\n" +
	"\x15SERVER_STATE_STARTING\x10\x02\x12\x18\n" +
	"\x14SERVER_STATE_RUNNING\x10\x032\x8d\x06\n" +
	"\rServerService\x12H\n" +
	"\vListServers\x12\x1b.mcsm.v1.ListServersRequest\x1a\x1c.mcsm.v1.ListServersResponse\x12K\n" +
	"\fCreateServer\x12\x1c.mcsm.v1.CreateServerRequest\x1a\x1d.mcsm.v1.CreateServerResponse\x12H\n" +
	"\vStartServer\x12\x1b.mcsm.v1.StartServerRequest\x1a\x1c.mcsm.v1.StartServerResponse\x12E\n" +
	"\n" +
	"StopServer\x12\x1a.mcsm.v1.StopServerRequest\x1a\x1b.mcsm.v1.StopServerResponse\x12N\n" +
	"\rRestartServer\x12\x1d.mcsm.v1.RestartServerRequest\x1a\x1e.mcsm.v1.RestartServerResponse\x12K\n" +
	"\fDeleteServer\x12\x1c.mcsm.v1.DeleteServerRequest\x1a\x1d.mcsm.v1.DeleteServerResponse\x12K\n" +
	"\fUpdateServer\x12\x1c.mcsm.v1.UpdateServerRequest\x1a\x1d.mcsm.v1.UpdateServerResponse\x12G\n" +
	"\n" +
	"StreamLogs\x12\x1a.mcsm.v1.StreamLogsRequest\x1a\x1b.mcsm.v1.StreamLogsResponse0\x01\x12H\n" +
	"\vSendCommand\x12\x1b.mcsm.v1.SendCommandRequest\x1a\x1c.mcsm.v1.SendCommandResponse\x12W\n" +
	"\x10ConfigureNetwork\x12 .mcsm.v1.ConfigureNetworkRequest\x1a!.mcsm.v1.ConfigureNetworkResponseB:Z8github.com/QwikByte/mc-server-manager/api/mcsm/v1;mcsmv1b\x06proto3"

var (
	file_mcsm_v1_server_proto_rawDescOnce sync.Once
	file_mcsm_v1_server_proto_rawDescData []byte
)

func file_mcsm_v1_server_proto_rawDescGZIP() []byte {
	file_mcsm_v1_server_proto_rawDescOnce.Do(func() {
		file_mcsm_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsm_v1_server_proto_rawDesc), len(file_mcsm_v1_server_proto_rawDesc)))
	})
	return file_mcsm_v1_server_proto_rawDescData
}

var file_mcsm_v1_server_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mcsm_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_mcsm_v1_server_proto_goTypes = []any{
	(ServerType)(0),                  // 0: mcsm.v1.ServerType
	(RestartPolicy)(0),               // 1: mcsm.v1.RestartPolicy
	(ServerState)(0),                 // 2: mcsm.v1.ServerState
	(*Server)(nil),                   // 3: mcsm.v1.Server
	(*ListServersRequest)(nil),       // 4: mcsm.v1.ListServersRequest
	(*ListServersResponse)(nil),      // 5: mcsm.v1.ListServersResponse
	(*CreateServerRequest)(nil),      // 6: mcsm.v1.CreateServerRequest
	(*CreateServerResponse)(nil),     // 7: mcsm.v1.CreateServerResponse
	(*StartServerRequest)(nil),       // 8: mcsm.v1.StartServerRequest
	(*StartServerResponse)(nil),      // 9: mcsm.v1.StartServerResponse
	(*StopServerRequest)(nil),        // 10: mcsm.v1.StopServerRequest
	(*StopServerResponse)(nil),       // 11: mcsm.v1.StopServerResponse
	(*RestartServerRequest)(nil),     // 12: mcsm.v1.RestartServerRequest
	(*RestartServerResponse)(nil),    // 13: mcsm.v1.RestartServerResponse
	(*UpdateServerRequest)(nil),      // 14: mcsm.v1.UpdateServerRequest
	(*UpdateServerResponse)(nil),     // 15: mcsm.v1.UpdateServerResponse
	(*DeleteServerRequest)(nil),      // 16: mcsm.v1.DeleteServerRequest
	(*DeleteServerResponse)(nil),     // 17: mcsm.v1.DeleteServerResponse
	(*StreamLogsRequest)(nil),        // 18: mcsm.v1.StreamLogsRequest
	(*StreamLogsResponse)(nil),       // 19: mcsm.v1.StreamLogsResponse
	(*SendCommandRequest)(nil),       // 20: mcsm.v1.SendCommandRequest
	(*SendCommandResponse)(nil),      // 21: mcsm.v1.SendCommandResponse
	(*ConfigureNetworkRequest)(nil),  // 22: mcsm.v1.ConfigureNetworkRequest
	(*NetworkBackend)(nil),           // 23: mcsm.v1.NetworkBackend
	(*ConfigureNetworkResponse)(nil), // 24: mcsm.v1.ConfigureNetworkResponse
}
var file_mcsm_v1_server_proto_depIdxs = []int32{
	0,  // 0: mcsm.v1.Server.type:type_name -> mcsm.v1.ServerType
	2,  // 1: mcsm.v1.Server.state:type_name -> mcsm.v1.ServerState
	1,  // 2: mcsm.v1.Server.restart_policy:type_name -> mcsm.v1.RestartPolicy
	3,  // 3: mcsm.v1.ListServersResponse.servers:type_name -> mcsm.v1.Server
	0,  // 4: mcsm.v1.CreateServerRequest.type:type_name -> mcsm.v1.ServerType
	3,  // 5: mcsm.v1.CreateServerResponse.server:type_name -> mcsm.v1.Server
	1,  // 6: mcsm.v1.UpdateServerRequest.restart_policy:type_name -> mcsm.v1.RestartPolicy
	3,  // 7: mcsm.v1.UpdateServerResponse.server:type_name -> mcsm.v1.Server
	23, // 8: mcsm.v1.ConfigureNetworkRequest.backends:type_name -> mcsm.v1.NetworkBackend
	4,  // 9: mcsm.v1.ServerService.ListServers:input_type -> mcsm.v1.ListServersRequest
	6,  // 10: mcsm.v1.ServerService.CreateServer:input_type -> mcsm.v1.CreateServerRequest
	8,  // 11: mcsm.v1.ServerService.StartServer:input_type -> mcsm.v1.StartServerRequest
	10, // 12: mcsm.v1.ServerService.StopServer:input_type -> mcsm.v1.StopServerRequest
	12, // 13: mcsm.v1.ServerService.RestartServer:input_type -> mcsm.v1.RestartServerRequest
	16, // 14: mcsm.v1.ServerService.DeleteServer:input_type -> mcsm.v1.DeleteServerRequest
	14, // 15: mcsm.v1.ServerService.UpdateServer:input_type -> mcsm.v1.UpdateServerRequest
	18, // 16: mcsm.v1.ServerService.StreamLogs:input_type -> mcsm.v1.StreamLogsRequest
	20, // 17: mcsm.v1.ServerService.SendCommand:input_type -> mcsm.v1.SendCommandRequest
	22, // 18: mcsm.v1.ServerService.ConfigureNetwork:input_type -> mcsm.v1.ConfigureNetworkRequest
	5,  // 19: mcsm.v1.ServerService.ListServers:output_type -> mcsm.v1.ListServersResponse
	7,  // 20: mcsm.v1.ServerService.CreateServer:output_type -> mcsm.v1.CreateServerResponse
	9,  // 21: mcsm.v1.ServerService.StartServer:output_type -> mcsm.v1.StartServerResponse
	11, // 22: mcsm.v1.ServerService.StopServer:output_type -> mcsm.v1.StopServerResponse
	13, // 23: mcsm.v1.ServerService.RestartServer:output_type -> mcsm.v1.RestartServerResponse
	17, // 24: mcsm.v1.ServerService.DeleteServer:output_type -> mcsm.v1.DeleteServerResponse
	15, // 25: mcsm.v1.ServerService.UpdateServer:output_type -> mcsm.v1.UpdateServerResponse
	19, // 26: mcsm.v1.ServerService.StreamLogs:output_type -> mcsm.v1.StreamLogsResponse
	21, // 27: mcsm.v1.ServerService.SendCommand:output_type -> mcsm.v1.SendCommandResponse
	24, // 28: mcsm.v1.ServerService.ConfigureNetwork:output_type -> mcsm.v1.ConfigureNetworkResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_mcsm_v1_server_proto_init() }
func file_mcsm_v1_server_proto_init() {
	if File_mcsm_v1_server_proto != nil {
		return
	}
	file_mcsm_v1_server_proto_msgTypes[20].OneofWrappers = []any{
		(*NetworkBackend_ServerId)(nil),
		(*NetworkBackend_Address)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsm_v1_server_proto_rawDesc), len(file_mcsm_v1_server_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcsm_v1_server_proto_goTypes,
		DependencyIndexes: file_mcsm_v1_server_proto_depIdxs,
		EnumInfos:         file_mcsm_v1_server_proto_enumTypes,
		MessageInfos:      file_mcsm_v1_server_proto_msgTypes,
	}.Build()
	File_mcsm_v1_server_proto = out.File
	file_mcsm_v1_server_proto_goTypes = nil
	file_mcsm_v1_server_proto_depIdxs = nil
}
