import {
  BooksIcon,
  BugIcon,
  ChatsCircleIcon,
  CoinsIcon,
  CompassIcon,
  CpuIcon,
  FlowerIcon,
  ForkKnifeIcon,
  GameControllerIcon,
  GearSixIcon,
  type Icon,
  LightningIcon,
  MagicWandIcon,
  MountainsIcon,
  PackageIcon,
  SkullIcon,
  SwordIcon,
  ToolboxIcon,
  TrainIcon,
  WrenchIcon,
} from "@phosphor-icons/react"
import { msg } from "@/lib/i18n"

/** The categories of plugins and mods on Modrinth, with their labels in English. */
export const categories: Record<string, { label: string; icon: Icon }> = {
  adventure: { label: msg("Adventure"), icon: CompassIcon },
  cursed: { label: msg("Cursed"), icon: SkullIcon },
  decoration: { label: msg("Decoration"), icon: FlowerIcon },
  economy: { label: msg("Economy"), icon: CoinsIcon },
  equipment: { label: msg("Equipment"), icon: SwordIcon },
  food: { label: msg("Food"), icon: ForkKnifeIcon },
  "game-mechanics": { label: msg("Game mechanics"), icon: GearSixIcon },
  library: { label: msg("Library"), icon: BooksIcon },
  magic: { label: msg("Magic"), icon: MagicWandIcon },
  management: { label: msg("Management"), icon: WrenchIcon },
  minigame: { label: msg("Minigame"), icon: GameControllerIcon },
  mobs: { label: msg("Mobs"), icon: BugIcon },
  optimization: { label: msg("Optimization"), icon: LightningIcon },
  social: { label: msg("Social"), icon: ChatsCircleIcon },
  storage: { label: msg("Item storage"), icon: PackageIcon },
  technology: { label: msg("Technology"), icon: CpuIcon },
  transportation: { label: msg("Transportation"), icon: TrainIcon },
  utility: { label: msg("Utility"), icon: ToolboxIcon },
  worldgen: { label: msg("World generation"), icon: MountainsIcon },
}
